### ISSUE TITLE
Requests for <profile-service>/profile/$profileId return 404

### ISSUE THREAD

**Issue by ben3000** [AtlasOfLivingAustralia/profile-hub#107]
Profile-hub requests to /opus/$opusId/profile/$profileId get handled by ProfileController.show(), which uses ProfileService.getProfile(profileId) to request &lt;profile-service>/profile/$profileId, which returns a 404.

Either update ProfileService.getProfile to request &lt;profile-service>/opus/$opusId/profile/$profileId or add another url mapping to the Profile Service app for:

"/profile/$profileId" controller: "profile", action: [ GET: "getByUuid" ]

**Comment by m-r-c** [comment]
You may be looking at an old version of the profile-hub code. URLs were modified to include the opus a while ago.

**Comment by ben3000** [comment]
Yes, I noticed that after checking in this issue, but the issue remains after getting the latest versions of both profile-hub and profile-service.

Specifically, a profile-hub URL such as http://dev.ala.org.au:8080/profile-hub/opus/e3bd4859-3f83-4d6f-aeb0-ec1585bd70cd/profile/10c171f3-5cfe-454a-a6b1-f8eb1d689a65 displays "The requested page does not exist", showing the following in profile-service's logs:

`java.io.FileNotFoundException: http://localhost:8081/profile-service/profile/10c171f3-5cfe-454a-a6b1-f8eb1d689a65
	at java.net.URLConnection.getContent(URLConnection.java:748)
...
`

**Comment by ben3000** [comment]
Yep, had an old version on my machine, this can be closed.
