### ISSUE TITLE
I just tried editing the FNSW profile page for Meliaceae, to promote a better image to the top. I can do this, but after Save the old image is still displayed in the edit view – I have to go to Public view to see the change. This is a bit confusing for an editor. Kevin Thiele

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#112]
http://www.bugherd.com/projects/58735/tasks/95

**Comment by m-r-c** [comment]
This is due to the way the angular js controllers are working - most of them fetch their own copy of the profile. We need to change them to use the same copy. It should be possible to cache the profile in the ProfileService class.

**Comment by m-r-c** [comment]
This is due to the way the angular js controllers are working - most of them fetch their own copy of the profile. We need to change them to use the same copy. It should be possible to cache the profile in the ProfileService class.

This will also help with page load performance by reducing the number of server calls.

**Comment by chrisala** [comment]
Created a shared instance of the profile in the ProfileService that is returned by the getProfile and updateProfile calls.
https://upsource.ala.org.au/profiles/review/PRFLS-CR-34

**Comment by chrisala** [comment]
Most other controllers are currently only using the shared profile for access to the guid, uuid & scientific name.  If the name is changed there is a page reload so I haven't (at least yet) been able to find an instance where this change will introduce problems.

**Comment by chrisala** [comment]
Reopened because I noticed I broke the attribute audit trail.
https://upsource.ala.org.au/profiles/review/PRFLS-CR-37
