### ISSUE TITLE
IE caches profile page

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#142]
IE caches the profile page, so updates do not always appear.

e.g.

Create a new profile -> enter some attribute data -> save -> Public View. The attribute data may not be visible. Force refresh in IE (hold down Shift and click the browser Refresh button) and it will appear.

**Comment by m-r-c** [comment]
I have added no-cache headers. Needs testing to see if this fixes it.

**Comment by chrisala** [comment]
Setting the app.view.noCache config item to true fixes this issue on IE9.  Are we supporting IE8?

**Comment by m-r-c** [comment]
Nope. Only 9 and above.

**Comment by chrisala** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-20
