### ISSUE TITLE
Add support for including bracketed keys in the PDF

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#149]
Supporting bracketed keys in the UI will be covered by #173

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-18

**Comment by pwscsiro** [comment]
Acceptance Test (How we can tell the story has been implemented):

**Comment by pwscsiro** [comment]
As a counterpoint to the above, when we follow the same process for a profile with no Keybase profile, the Key checkbox will not appear in the download dialog and we will still be able to download a PDF containing the attributes selected.

**Comment by pwscsiro** [comment]
Export as PDF Dialog Box
![pdf export dialog](https://cloud.githubusercontent.com/assets/17239936/13237064/d8de7482-da1c-11e5-9a07-09374bbaa12f.png)

**Comment by pwscsiro** [comment]
Example of successful bracket format Key attribute inclusion in PDF
![key in pdf](https://cloud.githubusercontent.com/assets/17239936/13237088/0989b416-da1d-11e5-9958-1ee53bc23c23.png)
