### ISSUE TITLE
Distribution map:
I think it is necessary to differentiate occurrences on the map (e.g. by colour or symbol) that are confirmed by the author of the treatment as belonging to that taxon from those that are unconfirmed. In the course of preparing a treatment authors will rarely be able to see all of the specimens of a taxon in Australian herbaria. A proportion of those, hopefully small, are likely to be mis-identified. Therefore distinguishing authoritatively identified occurrences from those with a lower level of confidence is important. At the moment the map seems simply to show all records in AVH under a particular name.

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#155]
http://www.bugherd.com/projects/58735/tasks/108

**Comment by ala-bugherd** [comment]
Thanks for your email,

I am currently out of the office and will be returning on Tuesday 6th October.

Please send all MERIT related enquiries to
For programme related enquiries:   merit@environment.gov.au
for technical and system related enquiries:  sat01a@csiro.au

For all BDRS (Field Data) enquires, please send an email to support_bdrs@ala.org.au.

Regards,

Peter Brenton
Atlas of Living Australia
Email: peter.brenton@csiro.au
Web: www.ala.org.au

**Comment by m-r-c** [comment]
This should be solved by the combination of #339, #156, #340, #222, #221.
