### ISSUE TITLE
Distribution map:
I think it is necessary to distinguish cultivated records from wild ones, e.g. by colour and/or symbol.

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#156]
http://www.bugherd.com/projects/58735/tasks/109

**Comment by ala-bugherd** [comment]
Thanks for your email,

I am currently out of the office and will be returning on Tuesday 6th October.

Please send all MERIT related enquiries to
For programme related enquiries:   merit@environment.gov.au
for technical and system related enquiries:  sat01a@csiro.au

For all BDRS (Field Data) enquires, please send an email to support_bdrs@ala.org.au.

Regards,

Peter Brenton
Atlas of Living Australia
Email: peter.brenton@csiro.au
Web: www.ala.org.au

**Comment by m-r-c** [comment]
#156, #340, #307, #222, #221 are all related

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/ala-map-plugin/review/AMP-CR-13
https://upsource.ala.org.au/profiles/review/PRFLS-CR-78
