### ISSUE TITLE
Admin editing of "Attribute vocabulary"

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/profile-hub#17]

**Comment by m-r-c** [comment]
Done.

The Edit Opus page allows you to maintain the terms for the Opus' vocabulary. Terms can be deleted, but if they are being used then a replacement term needs to be provided.
The vocabulary can be set as 'strict', meaning the Attribute Titles on the Profile Edit page must come from the list, and new terms can only be added through the Edit Opus page. 'Not strict' means any value can be used as an Attribute Title (new values are automatically added to the vocabulary).
