### ISSUE TITLE
Allow images to be uploaded and displayed within Attributes

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#171]
Support for:

* images

Sound and movies will be covered under #266

**Comment by chrisala** [comment]
Start with images, appended to the attribute after the text. Needs to appear in the PDF with appropriate wrapping. If possible, embed the image in the correct location in the text.

Other media types to be done as separate tasks later.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-53

**Comment by m-r-c** [comment]
Re-opening: works fine for local images, not so well for remote images
