### ISSUE TITLE
Rewrite WebService class

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#172]
In both Profile Hub and Profile Service

This would be a good candidate to add to the 'grails-rest-extensions' plugin.

**Comment by pwscsiro** [comment]
The current Grails recommended option is Rest-client-builder [https://grails.org/plugin/rest-client-builder](url) which appears to have been rolled into Grail's core data library in version 3. An example starting point:
 
 org.springframework.http.HttpStatus reindexCollection(GString gString, LinkedHashMap linkedHashMap) {
        RestBuilder restBuilder = new RestBuilder(connectTimeout:30000, readTimeout:30000)
        RestResponse restResponse = restBuilder.post("${grailsApplication.config.profile.service.url}/admin/search/reindex", [:])
        restResponse.responseEntity.statusCode
    }
//maybe get the dependency injection working too

**Comment by m-r-c** [comment]
rest-client-builder has too many issues:

- double encodes any url that is already encoded (this can obviously be avoided by removing the first encoding)
- open bugs about encoding &s
- multipart request handling is ugly and limited
- I found issues with sending JSON in a generic way - some calls in profile-hub worked, others did not, whereas we didn't have that problem with the previous implementation, and we do not have the problem when using HTTPBuilder. I didn't look into why.

So, I have rewritten the class using HTTP Builder.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-63

**Comment by m-r-c** [comment]
Here's a version using the rest client plugin for future reference.

[WebServiceWithRestBuilder.txt](https://github.com/AtlasOfLivingAustralia/profile-hub/files/194625/WebServiceWithRestBuilder.txt)
