### ISSUE TITLE
Stats from Google Analytics are not right

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#178]
* There have been more than 6 unique visitors to the profiles-dev FOA collection
* Downloads are not being counted - the URL pattern for the GA lookup is probably wrong

**Comment by sbearcsiro** [comment]
No analytics calls were being generated for the publication or PDF downloads.

I experimented with using both server side and client side analytics for tracking downloads.  The server side impl ended up cleaner than the client side (I have the client impl stashed but not committed).  Happy to discuss further if required.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-23

**Comment by m-r-c** [comment]
When snapshot versions are downloaded, the URL goes directly to the Profile Service.

It might be worth counting these separately to the ad-hoc PDF downloads (but adding the count on the UI), since they are intended as a cited reference rather than a random download.

Would it be possible to duplicate the server-side GA record on the profile-service too? Alternatively, we could change the code so that the snapshot downloads go via the profile-hub.
