### ISSUE TITLE
Clicking on “Glossary” gives me the error message “You do not have the necessary permissions to perform this action”. Assuming the glossary hasn't been imported yet? I've forgotten

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#187]
http://www.bugherd.com/projects/58735/tasks/129

**Comment by m-r-c** [comment]
Cannot replicate.

**Comment by ala-bugherd** [comment]
Cannot replicate.

**Comment by ala-bugherd** [comment]
Thanks for your email,

I am currently out of the office and will be returning on Monday 8th February.

Please send all MERIT related enquiries to:
merit@environment.gov.au for programme related enquiries.
merit@ala.org.au for technical and system related enquiries.

For all BioCollect enquires, please send an email to biocollect-support@ala.org.au.

For all BDRS (Field Data) enquires, please send an email to support_bdrs@ala.org.au.

Regards,

Peter Brenton
Atlas of Living Australia
Email: peter.brenton@csiro.au
Web: www.ala.org.au
