### ISSUE TITLE
What is the required format for the “Date Taken” field when uploading images from the EFlora platform? I tried all sorts, including American and Military and with/without the time in several formats but it always “greyed out” the “OK” button. The only way I could proceed was to leave the “Date Taken” field blank.

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#189]
http://www.bugherd.com/projects/58735/tasks/131

**Comment by m-r-c** [comment]
The format is in placeholder text, but it could be cleared to show it below/beside the field, too. There is also a problem with clearing the value:

1. Enter an invalid date (33/33/2015)
1. The save button is disabled
1. Fix the date
1. The save button is (at least sometimes) still disabled.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-6

**Comment by m-r-c** [comment]
Getting a JS error on the Recent Updates report:
```
Cannot read property 'datepickerAppendToBody' of undefined
```
