### ISSUE TITLE
Support "copy-from" functions between selected Opui

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/profile-hub#19]
Quick notes for now.

In the admin screen for an Opus, we need to support the ability to specify other Opus to include in a profile where content isnt available.

We also need to support the ability to copy an existing Attribute from one Profile into another (for the same taxon).

Lets discuss.

**Comment by m-r-c** [comment]
A first cut of this has been implemented.
In the Edit Opus screen, you can now specify a list of 'supporting collections', which are opuses to fetch missing attributes from. 
In the Profile screens, attributes that exist in the same profile from a 'supporting collection' but not in the current profile are also displayed, with a 'source: <opus title>' element. When editing, these attributes can be copied into the current profile.

I'll leave this task open for a while until we get some feedback.
