### ISSUE TITLE
Flora of Australia - specimen URL error: When I added the URL of a specimen record from ALA, a message came up “Invalid URL. The URL must be of the form specified above”. The URL looked all right to me, so I saved it, and the save was successful. I then went to public view and clicked on the URL, and the correct page duly appeared.
For example: Albizia lebbeck profile (in FoA). The URL is http://biocache.ala.org.au/occurrences/2ca05f37-dea4-4606-a02c-e8335971f50b
When I pasted this URL into the “Specimens” attribute, I got the error message as below, but then when I hit “Save”, the save was successful.


### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#195]
http://www.bugherd.com/projects/58735/tasks/137

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-1

**Comment by ala-bugherd** [comment]
Thanks for your email,

I am currently out of the office and will be returning on Monday 8th February.

Please send all MERIT related enquiries to:
merit@environment.gov.au for programme related enquiries.
merit@ala.org.au for technical and system related enquiries.

For all BioCollect enquires, please send an email to biocollect-support@ala.org.au.

For all BDRS (Field Data) enquires, please send an email to support_bdrs@ala.org.au.

Regards,

Peter Brenton
Atlas of Living Australia
Email: peter.brenton@csiro.au
Web: www.ala.org.au
