### ISSUE TITLE
Add error pages to profile-service

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#196]
URLs that go directly to the profile-service (e.g. pdf downloads for versions) show the standard tomcat or grails error pages. We need to show a page like profile-hub's, that hides implementation details.

E.g. try to access an api-key protected action on profile-service without a key: you will get tomcat's 403 page.

**Comment by ben3000** [comment]
Commit 456e3f726f7999e54f1c716bbeb73152437c0607 contains the fix for this.
