### ISSUE TITLE
Sandbox integration for the inclusion of other occurrence sources

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/profile-hub#20]
Ajax upload making use of existing sandbox upload services for upload.
Dependent on auth work around the sandbox.
Details to follow.

**Comment by rp-ala** [comment]
see also #252 Map enhancements re desire for private occurrence records for Indigenous communities

**Comment by m-r-c** [comment]
Given the IEK privacy requirements for the profile collection, and the absence of authentication & authorisation for the sandbox, I think the best approach here would be to install an instance of sandbox alongside profiles with no external visibility, then change the Profiles interface to allow data to be uploaded through Profiles into Sandbox. This should allow us to block access to sandbox data for private collections.

Profiles will need to be changed to fetch data from both Biocache (for public data and images) and from the Profiles-Sandbox instance.

We may need to look at beefing up the Profiles servers for this.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-94

There is some doco on the setup and the approach taken in the profiles wiki:
https://github.com/AtlasOfLivingAustralia/profile-hub/wiki/Project-Setup#sandbox-integration
https://github.com/AtlasOfLivingAustralia/profile-hub/wiki/Sandbox-integration
