### ISSUE TITLE
A list of subordinate taxa should be included on each profile page

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#217]
1. platform Architecture and navigation 

Addressed via a hierarchical side bar (#250)?

We could (should?) also add a dedicated tab for subordinate taxa?

**Comment by m-r-c** [comment]
Wait until the hierarchical sidebar is done, then see if a separate tab (or some other display) is required.

**Comment by chrisala** [comment]
Should a list of subordinate taxa be included in the pdf (just as a list, not as separate profiles)?

**Comment by m-r-c** [comment]
KT 10/3/16: Note that a PDF page for a taxon does not need to include subordinates, unless they're included in a multi-ranked page

**Comment by m-r-c** [comment]
1.07b

**Comment by m-r-c** [comment]
Requires confirmation - may not need any further work

**Comment by m-r-c** [comment]
Subordinate taxa are available in the breadcrumb, the taxonomy attribute and the hierarchy side bar. The only outstanding issue is whether all subordinates or just the immediate children should be displayed - this will be covered under #337.
