### ISSUE TITLE
Ability to subset the eFlora to a set of pages for e.g. geographic area searches (subsetting the Flora to a Florula) 

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#218]
1. platform Architecture and navigation 

E.g. use AVH to get a list of taxa within a geographic region, then get eFlora to subset those and only those taxa in all respects (navigation, keys etc)

**Comment by m-hope** [comment]
The essence of this issue to allow a taxonomist to restrict their 'view' of a collection to a specific set of taxa (whether this taxa is regionally defined (eg: all vascular plants occurring in SE WA) or taxonomically (eg: all Acacias)).  The task then is (a) to work out how to restrict any profiles displayed to only those on the list (and manage how this is flagged, etc), and (b) how to set that list in the first place (this could initially be just an imported list, eg: from the ALA or Spatial Portal).

I have adjusted the estimate to 3 days for the December sprint... for this sprint the requirement is just to investigate the feasibility and ensure that any future work doesn't preclude this functionality... It is assumed that the investigation will give a better estimate to actually implement the functionality.

**Comment by m-hope** [comment]
Closing this issue as it is the same as #412.
