### ISSUE TITLE
UI - Identify - Show icons for keybase filters

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#219]
\3. keys management and integration

**Comment by m-r-c** [comment]
Need to review this now that the ala-keys keyplayer plugin is being used. It supports filtering - does that cover the requirement?

**Comment by RobinaSanderson** [comment]
These icons work but you can't tell what they're meant to do.

![image](https://cloud.githubusercontent.com/assets/23368496/23531929/ff54e00e-fffc-11e6-9c0a-b62a3c96942a.png)

![image](https://cloud.githubusercontent.com/assets/23368496/23531982/3d371aea-fffd-11e6-9224-0f655828c87d.png)

**Comment by RobinaSanderson** [comment]
This should be done in conjunction with #457

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-137
