### ISSUE TITLE
Could maps automatically zoom to the distribution?

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#221]
\4. Mapping

Wait until the ala-map plugin is being used (#210)

**Comment by rp-ala** [comment]
Consider also implications of this for other uses - preference for leaving the map centred on the location specified by the Admin by default, with zoom option.

**Comment by m-r-c** [comment]
The admin screen already allows the collection admin to specify the default centre and zoom level. We would need to add another option to zoom to the profile distribution.

Before that, though, we need to work out how to get the bounding box for the distribution (the current implementation renders a WMS layer from the biocache, which I don't think specifies the bounds) - needs some investigation.

**Comment by m-r-c** [comment]
4.03

**Comment by m-r-c** [comment]
#156, #340, #222, #221 are all related

**Comment by m-r-c** [comment]
Use this service to get the bounds for the WMS layer: http://biocache.ala.org.au/ws/mapping/bounds.json?q=

**Comment by m-r-c** [comment]
Collection admins can now choose to zoom to the bounds of the data by default (with a max zoom) or not.

The maps also have a new icon on them to allow users to toggle between the full view and the data bounds.

https://upsource.ala.org.au/ala-map-plugin/review/AMP-CR-12
https://upsource.ala.org.au/profiles/review/PRFLS-CR-73
