### ISSUE TITLE
Exporting a pdf - would be useful to have the option to select "all items" (attributes)

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#228]

**Comment by m-r-c** [comment]
The export dialog has been changed to select all options by default. Is this sufficient, or do we need a De-select All/Select All option as well?

**Comment by RobinaSanderson** [comment]
Closing this issue as default seems to work for now. If issue allowing all attributes to be toggled on and off is implemented this would become useful.
