### ISSUE TITLE
Would be good to be able to duplicate an entire profile – some taxa are very similar, and duplicate-then-edit will be more efficient than write-from-scratch

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#231]

**Comment by m-r-c** [comment]
7.06

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-77

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-81

**Comment by m-hope** [comment]
Reopened this job as it appears that while a duplicate profile is created, it doesn't copy in the user defined attribute data.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-103
