### ISSUE TITLE
It should be clear where the data are integrated from. For example, it’s not currently clear that keys come from Keybase, or where the conservation data comes from (legal basis) – also taxonomy data, and which tree this is using (e.g. APC/ other)

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#239]
We can add some attribution/credit text for each of the sections that pull content from another source.

e.g. below the keyplayer would be text like “Source: Keybase” with a link (in fact this already exists, but is obviously not prominent enough).

The following sections will have this:
-	Keys (will be handled under #173)
-	Map (already exists)
-	Images (already exists)
-	Conservation status
-	Feature lists
-       Taxonomy

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-17

**Comment by pwscsiro** [comment]
These are examples of the resulting output:
![feature list source](https://cloud.githubusercontent.com/assets/17239936/13166473/760e07d0-d71c-11e5-951b-3f260d1ae203.png)
![conservation status source](https://cloud.githubusercontent.com/assets/17239936/13166511/d8c2e40e-d71c-11e5-99c7-b4841dc96acb.png)
![taxonomy source](https://cloud.githubusercontent.com/assets/17239936/13166555/4b849f6e-d71d-11e5-98d0-b8dda234950d.png)
NB: To trigger the taxonomy update you will need to cause the profile to update for example edit it, edit name, check name, update name.
