### ISSUE TITLE
Allow files to be attached to a collection and to profiles

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#240]
Inclusion of non-profile information, such as introductory essays/ explanatory text, at any level (including both to profile pages (see e.g. introductory essays in the Flora of Australia Proteaceae volume) and to the Flora as a whole (e.g. introductory chapters in Volume 1 of the Flora of Australia).

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-19

**Comment by pwscsiro** [comment]
Acceptance Criteria (How we know the issue is addressed)
Given:
When:
Then:

**Comment by m-r-c** [comment]
Rules:

Collection level documents:
* Only ALA or Collection Administrators can Add/Edit/Delete documents
* All users should be able to see and download documents

Profile level documents:
* The tab should only be visible on the read-only view if there are documents attached to the profile
* The tab should always be visible on the Edit view
* Only Admins and Editors can add/edit/delete documents
* When a profile is locked for major edit (aka draft), documents uploaded during the draft should only be visible to Admins and Editors
* Changes made during the draft (edits, new attachments, deletes) should be discarded when the draft changes are discarded
* All changes made during the draft should become visible to all users when the draft changes are published
* The profile revision history should list changes to documents.

Both:
* The document Title should be a link that downloads the document
* The second column should contain the description and the attribution (rights etc) for the document

**Comment by pwscsiro** [comment]
Only PDFs are currently supported

**Comment by pwscsiro** [comment]
Screenshot of PDF Attachment download screen
[Pdf Attachment download.pdf](https://github.com/AtlasOfLivingAustralia/profile-hub/files/143657/Pdf.Attachment.download.pdf)

**Comment by pwscsiro** [comment]
Screenshot of PDF attachment download screen
![pdf attachment download](https://cloud.githubusercontent.com/assets/17239936/13271061/88187096-dae6-11e5-9871-ce45c382c25e.png)
