### ISSUE TITLE
Include attached documents in the snapshot

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#241]
Following on from #240

Change the snapshot to a zip file with all attached documents.

**Comment by pwscsiro** [comment]
Acceptance Criteria (How we know the story is done):
Given: A profile with attached PDFs
When: An admin user creates a snapshot
Then: The snapshot will be a zip file containing the profile and the PDFs

**Comment by pwscsiro** [comment]
Screenshot of creating snapshot version
![snapshot version](https://cloud.githubusercontent.com/assets/17239936/13306747/78425734-dbba-11e5-82f4-979fdb909530.png)

**Comment by pwscsiro** [comment]
Ready for QA. Intention is that a Profile with no attachments will continue to be versioned as a PDF, while a Profile with attachments will be versioned as a zipfile containing 2 or more PDFs. Both types will be available for download.

**Comment by pwscsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-26
