### ISSUE TITLE
Browse by category improvements

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#251]
1. Add a filter box to each section to filter the list so it is easier to find items (similar to #259)
1. When selecting an item from the list, automatically scroll to the top of the results table.

**Comment by m-r-c** [comment]
Each rank in the classification now includes an input field for filtering by name:
* filters as you type
* the filter is a case-insensitive 'starts with' match on the name

Clicking any item in the browse lists will also automatically scroll you to the top of the results table.

https://upsource.ala.org.au/profiles/review/PRFLS-CR-27

**Comment by pwscsiro** [comment]
Screenshot of Browse by Category Filter
![browse by category filters](https://cloud.githubusercontent.com/assets/17239936/13446294/4938693c-e066-11e5-9d02-646f6eef8363.png)
