### ISSUE TITLE
Name based searching

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#254]
Ideas:

1. 'broad search' - scatter-gun approach, looks up any possible names (synonyms, common names, etc etc) for the provided text and searches for all of them.
1. 'taxonomic search' - specific name searching, only using currently accepted synonyms etc

**Comment by KevinThiele** [comment]
think of "broad search" as a google-like word search? - looks up any words anywhere on the page, not just names

**Comment by m-r-c** [comment]
These are just early thoughts at this stage - we'll go into more detail when work starts.

The first cut of a free text search has been implemented under an earlier task, but has not been deployed yet. The free text search searches for the provided text in any attribute in the profile, as well as in the profile name. Matches against the profile name will be ranked first, but otherwise ranking is based on general relevance scoring.

The logic behind the 'broad name search' would be quite different: it would assume that the provided text is meant to be some sort of name, and so would:

1. Query both the NSL and the ALA for any other known forms of that name (common names, synonyms, etc)
1. Search against just the Profile Name, Matched Name and attributes with 'name' in the title (e.g. common name) for any of the possible name forms
1. Rank matches of the provided name higher than matches of the alternate names
1. Rank matches against the Profile Name higher than against the Matched Name, which would rank higher than matches in 'name' attributes.

So for example, entering Acacia dealbata would actually end up searching for
* Acacia dealbata
* Racosperma dealbata
* Silver wattle
* etc

even if the word 'racosperma' for example never actually appears on the page.

This would be different from the 'taxonomic search', which would follow much more precise logic.

**Comment by KevinThiele** [comment]
This one will need to be considered carefully in the context of the names issue - for further discussion.

**Comment by KevinThiele** [comment]
Related to #245

**Comment by KevinThiele** [comment]
Searching in an eFlora is complex. A complete set of searches would be:

(1) Search on an accepted name (the name of a profile) - should return the profiles(s) that match. E.g. search on Adenanthos pungens returns Adenanthos pungens, Adenanthos pungens subsp. pungens and Adenanthos pungens subsp. effusus.
(2) Search on a synonym - should return the profile(s) that the synonym resolves to. E.g. search on Adenanthos procumbens should return Adenanthos apiculatus, search on Adenanthos sericea var. brevifolia should return Adenanthos macropodianus; note that some synonyms will be pro parte - that is, one synonym resolves to several possible accepted names e.g. search on Adenanthos sericeus should return A. sericeus, A. cygnorum and A. macropodianus (see APC for all these).
(3) Search by common name - should return all profiles that have that name in their Common Names attribute (e.g. Silver Wattle returns Acacia dealbata and any other matching profiles).
(4) Search by key word - performs a google-type search of all words anywhere on the page. E.g. search for "vine cordate pink" should return Parsonsia straminea (see Description attribute) and any other profiles that have the words "vine", "cordate" and "pink" anywhere on the page.

Currently, only (1) is well catered for, using the pull-out search.

One possibility would be to have a set of checkbox options to specify exactly what to search on - options would be "Accepted Names", "Synonyms", "Common Names", "All Words" (any one or more boxes could be checked)

**Comment by m-r-c** [comment]
The first pass of a dedicated name search has been implemented.

- the search field now has a drop down to select between a text and a name search
- the seach primarily relies on the ALA BIE to follow synonyms etc to the accepted name
- the examples in points 1-3 from the previous comment work, except for Adenanthos sericea var. brevifolia which will be resolved in the new BIE

This initial implementation is available on the test site.

**Comment by m-r-c** [comment]
Closing this task - have raised #354 to cover the remaining work in integrating with a new NSL search service.
