### ISSUE TITLE
Allow editors to specify the taxonomic hierarchy when there is no matched name

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#258]
* Only available when the profile does not have a matched name.
* Name matching will _always_ override any manually entered taxonomy.

Needs further discussion.

**Comment by rp-ala** [comment]
For IEK, users want to organise material in ways that are relevant to Indigenous people. This issue may help support - for further discussion.

**Comment by m-r-c** [comment]
10.01

**Comment by m-r-c** [comment]
The Browse by Category and the taxonomic hierarchy side bar need to reflect any custom classifications.

**Comment by m-r-c** [comment]
When the use creates a profile, or edits the name of an existing profile, the will have the option to specify the hierarchy when the name they enter does NOT match a known name or profile.

When creating the hierarchy:

* Rank is mandatory at each step
* The text field will autocomplete _profile names_, but you can enter a Name that has no profile, or something completely unknown
* If you enter the name of an existing profile, then the hierarchy from that point on will be set to the hierarchy of the selected profile (i.e. the editor cannot change the hierarchy beyond that point) 
* Likewise if you enter a Name that has no profile: the hierarchy will be set to the Name's hierarchy

The rank list is currently fixed, but a future enhancement would be to allow collection admins to define the list of ranks their collection should deal with.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-82
