### ISSUE TITLE
PDF reports do not contain symbols

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/profile-hub#262]
See sample that demonstrates how to fix this here: https://github.com/sbearcsiro/test-jasper.

Note that using a non default font in the profiles-hub grails-app causes our itext library to crash.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-33

**Comment by pwscsiro** [comment]
Screenshot of Rich Text and editor menu
![richtextsymbols](https://cloud.githubusercontent.com/assets/17239936/13586363/8870ac42-e514-11e5-8472-00d3052518b1.png)

**Comment by pwscsiro** [comment]
Screenshot of successful "Export as PDF":
![exportsymbols](https://cloud.githubusercontent.com/assets/17239936/13586515/7cbd46fc-e515-11e5-9c24-0c7f99a4f5a9.png)
