### ISSUE TITLE
Review and test key integration 

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/profile-hub#264]
Update with recent GitHub version, and use the new `renderItemLink`` callback.

There is also a bug on the collection home page: the first time you go to the page and click the identify tab, the key is not displayed. After refreshing, it works.

**Comment by RobinaSanderson** [comment]
Changing this task to be checking that keys are working correctly:
* no errors
* confirm integration between profiles and keybase APIs

**Comment by m-hope** [comment]
This task also needs to include a review of all Keybase calls and ensure we are using the new versions of all these calls...

I have asked Niels to provide a list of the new calls.

**Comment by RobinaSanderson** [comment]
All known issues with keys are documented separately. If anything else emerges we'll need to create separate issues.
