### ISSUE TITLE
Make sure thumbnail images are being used rather than full size images to improve page load performance

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#265]
This covers both images from ALA Images (which will always have an appropriate thumbnail), and private/staged images (which are not currently being 'thumbnailed'). 

Use the ALA image-utils library to create the thumbnail (https://github.com/AtlasOfLivingAustralia/image-utils/blob/master/src/main/java/au/org/ala/images/thumb/ImageThumbnailer.java)

**Comment by pwscsiro** [comment]
Sub tasks:
1. Check we are requesting the smallest thumbnail size when requesting images from ALA image Service
2.  For uploaded images, when we save the image tiles, also save a thumbnail of the image
3. Check the directory structure still makes sense and efficiently supports retrieval and deletion
4. Display the thumbnails in place of larger images unless the user chooses to view or download the full image

**Comment by pwscsiro** [comment]
I've run across a couple of issues running locally with retrieving images:
1. When the image query has encodeUrl applied against it I get no images back, removing this step returns images successfully.
2. Acacia paradoxa ? ?  seems a problem : "errorMessage" -> "org.apache.solr.search.SyntaxError: Cannot parse 'Acacia paradoxa \? \? Acacia verniciflua AND (data_resource_uid:)': Encountered " ")" ") "" at line 1, column 64.

**Comment by pwscsiro** [comment]
<img class="thumbnail ng-scope" ng-if="image.largeImageUrl &amp;&amp; image.type.name == 'OPEN'" ng-src="http://images.ala.org.au/image/proxyImageThumbnailLarge?imageId=bd878e8d-31b4-413e-9523-fa55bb63752a" src="http://images.ala.org.au/image/proxyImageThumbnailLarge?imageId=bd878e8d-31b4-413e-9523-fa55bb63752a">

**Comment by pwscsiro** [comment]
Sub Task 1Check that the url we use for display list of images is the small thumbnail:
This appears to be the options returned from biocache service -
"imageUrl" -> "http://images.ala.org.au/image/proxyImage?imageId=bd878e8d-31b4-413e-9523-fa55bb63752a"
"thumbnailUrl" -> "http://images.ala.org.au/image/proxyImageThumbnail?imageId=bd878e8d-31b4-413e-9523-fa55bb63752a"
"largeImageUrl" -> "http://images.ala.org.au/image/proxyImageThumbnailLarge?imageId=bd878e8d-31b4-413e-9523-fa55bb63752a"
"smallImageUrl" -> "http://images.ala.org.au/image/proxyImageThumbnail?imageId=bd878e8d-31b4-413e-9523-fa55bb63752a"

We were using ThumbnailLarge, have changed to Thumbnail.

**Comment by pwscsiro** [comment]
There exist 3 possible paths when uploading a new image determined by the settings that the collection Administrator has set up.
1. Normally an uploaded image is sent straight to the bio cache and is therefore available via the ALA services
2. However if the administrator has elected not to publish images then the images are instead stored in a local image directory as determined by the profile-hub property image.private.dir, currently something like /data/profile-hub/private-images;
3. Alternatively if the administrator has elected to publish images but the profile is currently in draft/major revision mode the images will be staged, i.e. held in an intermediate location, until the draft is released at which point they will be removed from the staged location and sent to the bio cache. The staging location is determined by the profile-hub property image.staging.dir, and is normally something like /data/profile-hub/staged-images.

**Comment by pwscsiro** [comment]
How to elect not to publish images:
Login as Administrator, click Configure Your Profile Collection, navigate to Image Options, set image visibility to 'Do not push images'

**Comment by pwscsiro** [comment]
Sub-task 2: Directory structure for private and staged images
Mark suggested adding an image directory level to the structure.
Current directory structure is /data/profile-hub/private-images (config) + /profileId/imageJPG + /profileId/tiles/ (source Code).
Propose we change the non-config part to something like /collectionId/profileId/imageId/image.jpg .. /tiles/ .. /thumbnails.  This accurately reflects the domain model, is extendable, and caters for deletion/copying etc at any level. Hopefully would handle anything else unexpected that crops up later.

**Comment by pwscsiro** [comment]
Note to self: I need to be careful here as adding depth to the directory structure can run foul of the way mkdir works and we don't want to clobber existing data

**Comment by pwscsiro** [comment]
Sub-task 2: Changed directory structure for private images, retaining backward compatibility with old structure. Impacted image retrieval, display, addition, deletion and PDF generation.

**Comment by pwscsiro** [comment]
Sub-task 3: Create Thumbnails - example usage of Thumbnail utility [https://github.com/AtlasOfLivingAustralia/image-utils/blob/master/src/test/java/au/org/ala/images/thumb/ImageThumbnailerTest.java](url)

**Comment by pwscsiro** [comment]
Sub-task 3: Create Thumbnails, done.

**Comment by pwscsiro** [comment]
Sub-task 4: Use Thumbnails when available done.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-52

**Comment by m-r-c** [comment]
Deleting draft & private images doesn't work (no error, but the image is not deleted).

**Comment by pwscsiro** [comment]
![collectionconfiguration_imageoptions](https://cloud.githubusercontent.com/assets/17239936/13831623/45e0de12-ec29-11e5-9095-4a34e9bd7ee8.png)
