### ISSUE TITLE
ProfileService (profile-service) dirty check on embedded entities will always succeed.

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/profile-hub#267]
While looking into #177 I noticed that saving a profile will sometimes cause the uuids of embedded objects to change, even if they had not been edited (and a different section was saved).

The ProfileService has a few dirty checks of the form:
if (json.containsKey("links") && json.links != profileOrDraft(profile).bhlLinks) 

These will tend to always return true a JSONObject.equals will return false if the other object is not also a JSONObject.

This is a fairly minor impact, but we should probably either fix the dirty check or remove it.

**Comment by ben3000** [comment]
See #368 for changes I made in similar code that gets run when saving an opus.

**Comment by ben3000** [comment]
The fix I implemented in #368 works perfectly for primitives, but for a child list of objects, such as the list of bibliography entries, the incoming list needs to be merged with the current list.

**Comment by sbearcsiro** [comment]
Hi @ben3000 could you link the upsource review for this task here please?

**Comment by ben3000** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-144

**Comment by RobinaSanderson** [comment]
Hi @ben3000 - I'm not sure how to test this. Could you give me a call on 02 6214 2907 if you have time?

**Comment by ben3000** [comment]
Hi @RobinaSanderson I have an email that provided some help on this, I'll dig it up.

**Comment by ben3000** [comment]
@RobinaSanderson actually, this comment explains it: https://github.com/AtlasOfLivingAustralia/profile-hub/issues/368#issuecomment-228510207

**Comment by RobinaSanderson** [comment]
Thanks @ben3000 - I'll follow the steps there.

**Comment by m-hope** [comment]
I haven't seen a case of the {} brackets appearing in a Collection settings (or in profile attributes for a while) so will assume this is fixed and will reopen if it occurs again.
