### ISSUE TITLE
Snapshot version downloads not included in GA stats

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#269]
When snapshot versions are downloaded, the URL goes directly to the Profile Service.

It might be worth counting these separately to the ad-hoc PDF downloads (but adding the count on the UI), since they are intended as a cited reference rather than a random download.

Would it be possible to duplicate the server-side GA record from #178 on the profile-service too? Alternatively, we could change the code so that the snapshot downloads go via the profile-hub.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-40

**Comment by sbearcsiro** [comment]
Publication downloads are now proxied through profile-hub, attachment downloads weren't touched but could be but should that be a separate ticket?
