### ISSUE TITLE
Mechanism for grouping Opui

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/profile-hub#27]
As discussed we need a mechanism to support a listing of Opui.

This could be a "type" field on Opus, or a separate domain class with one-to-many links to Opui.

This would enable a page that lists all Flora for example.

**Comment by m-r-c** [comment]
The easiest thing here would probably be to allow collection administrators to add 'tags' to their collection. Tags would include Flora, Fauna, Fungi etc. Tags could then be selected from the Profiles landing page to narrow down the number of visible profiles. It might also be possible to colour code the collection thumbnails (icon, border. background of the text or something) based on these fixed system tags - e.g. all collections tagged with Flora could have a green icon. The system tags could be configured by an ALA Admin (via the system admin page).

We could also allow admins to add their own tags (probably safest to have a maximum number) - these custom tags could also be selectable from the landing page to assist with searchign.

**Comment by m-r-c** [comment]
This has been partially implemented under https://github.com/AtlasOfLivingAustralia/profile-hub/issues/358. Tags can now be created by ALA Admins, and Opus admins can select tags that are suitable for their collection. There is currently no filtering option available in Profiles though - the implementation of 358 used the tags to extract indigenous profiles to display in the BIE.

**Comment by RobinaSanderson** [comment]
The use case for this is for the ALA admin to be able to group their view of collections within an environment. Probably need more collections to get value from this.
