### ISSUE TITLE
JS error when loading nomenclature for some profiles

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#274]
E.g. Acacia acanthoclada

TypeError: Cannot read property 'citationHtml' of undefined
    at bundle-bundle_profiles_defer.js:3580
    at bundle-bundle_angular_defer.js:112
    at l.$eval (bundle-bundle_angular_defer.js:125)
    at l.$digest (bundle-bundle_angular_defer.js:122)

**Comment by chrisala** [comment]
I can't reproduce this, the most likely cause was the NSL name search not returning a primary instance (although this doesn't line up with the bundle line numbers in dev or locally).
We probably need to handle this more gracefully.

**Comment by m-r-c** [comment]
Can't reproduce it either now....I have added a null check around the primary instance.
