### ISSUE TITLE
Images may not tile correctly

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/profile-hub#279]
Images on the profile page may not tile correctly if the content of the title + caption + attribute text is not the same height:

![image](https://cloud.githubusercontent.com/assets/1750790/13485971/0fb41a70-e161-11e5-99aa-024329a1eebc.png)

Probably requires something like this: http://getbootstrap.com/css/#grid-responsive-resets or flexbox to fix.

**Comment by m-r-c** [comment]
Something like this might be a good way to go: http://andrekoenig.info/angular-deckgrid/#/

**Comment by sbearcsiro** [comment]
This effect not longer occurs on the sample page above (Acacia genus profile) but I have added a bootstrap clearfix anyway and visually confirmed that it corrects the problem by adding a manually extended caption to images.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-65
