### ISSUE TITLE
consider cross-links between species pages and the eFlora. This was suggested by Ailsa Holland, QLD Herbarium. Can we have a capability to move between the species pages and a corresponding eFlora page (choose e.g. Qld profile, FoA profile etc for that species), and vice versa (from an eFlora profile to a species page)?

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#28]
http://www.bugherd.com/projects/58735/tasks/14

**Comment by ala-bugherd** [comment]
In Phase 1 can add a link from flora profile to ALA species page. Further consideration in a ltaer phase

**Comment by rp-ala** [comment]
Also a priority for other applications of Profiles tool in addition to eFlora implementation.

**Comment by m-r-c** [comment]
#359 introduced a new service on profiles which can be queried with a variety of parameters to fetch profiles for integration with the species pages. This service is currently (as of the June 2016 IEK sprint) being used to populate the Indigenous Information tab on the species page.

I think we can close this issue: a future BIE change could see Flora of Australia profiles, example, displayed on the species page using the same service, with no additional changes required in the Profiles code.
