### ISSUE TITLE
Common names on the view page

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#294]
The system finds any attribute with a title similar to common name (Commonname, common name, common names, etc) and displays it below the page title on the view page, as well as in the list of attributes.

Two changes are required:
1. Change the logic to pick out any attribute with "name" in the title and display them as a common-separated string below the name
2. Hide the corresponding attribute blocks

**Comment by chrisala** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-47
