### ISSUE TITLE
Remove the "Show content from supporting collections" option from the view page, leave it on the edit page and allow the editor to save it

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#301]
The editor should be able to select that flag and save it, which will then control the view page.

**Comment by chrisala** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-50
I've implemented the toggle as an auto-save which is inconsistent with the behaviour of the other sections but thought an explicit save button and section seemed like overkill for a single toggle.
