### ISSUE TITLE
Custom colour schemes for identity

### ISSUE THREAD

**Issue by rp-ala** [AtlasOfLivingAustralia/profile-hub#304]

**Comment by m-r-c** [comment]
Is this referring to the ability for a collection admin to select a predefined colour theme to replace the various shades of blue in the current implementation, or something different?

**Comment by rp-ala** [comment]
Yes, that's right.

**Comment by m-r-c** [comment]
See DigiVol - it apparently lets you derive a colour scheme from the logo. Somehow.

**Comment by RobinaSanderson** [comment]
The theme colours for a collection are now configurable.
