### ISSUE TITLE
Name matching not working on dev due to mixed content warning.

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/profile-hub#306]
I presume the config on dev (maybe also the ansible inventory?) needs to be updated to access the bie over https.

**Comment by m-r-c** [comment]
BIE doesn't currently support https. I think it might be best to proxy the name autocomplete through the profile-hub.

**Comment by m-r-c** [comment]
BIE has just been updated to handle https, so the inventories have been modified to use https for the bie calls. The autocomplete on the name lookup works now.
