### ISSUE TITLE
Stretching of image thumbnails

### ISSUE THREAD

**Issue by KevinThiele** [AtlasOfLivingAustralia/profile-hub#308]
Look at images for Adenanthera pavonina https://profiles-dev.ala.org.au/opus/foa/profile/Adenanthera%20pavonina. The thumbnail (e.g. the seedling, first image) are stretched - open the image and you'll see this. 

Probably just need to remove the min-width.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-55
