### ISSUE TITLE
Move author and acknowledgements text to bottom of page

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#313]
On the view page only - leave the edit fields where they are.

The authors & acks should be listed in a single line just above the page footer, in the format:

**Profile Contributors**: Author(s): ...; [Ack Category 1]: ...; [Ack Category 2]: ....

Make sure the table of contents still works.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-54

**Comment by pwscsiro** [comment]
![acknowledgements](https://cloud.githubusercontent.com/assets/17239936/13867757/6acef16c-ed16-11e5-9c87-90883f281c4f.png)

**Comment by pwscsiro** [comment]
Screenshot of final version:
![acknowledgementsfinal](https://cloud.githubusercontent.com/assets/17239936/13907930/fad6abe6-ef4c-11e5-8438-2872976dc916.png)
