### ISSUE TITLE
Italics in the bibliography are lost in the conversion to pdf

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#321]
The bibliography section of Profile PDFs don't italicize species names, even though they are correct in the actual profile (eg: create a PDF of this profile https://profiles-dev.ala.org.au/opus/078c22bf-a3f4-4dce-8710-4a636dfa8f6e/profile/Stylosanthes%20hamata).

**Comment by m-r-c** [comment]
This seems to be caused by bibliography entries that were created a while ago, before changes to the way html elements are being handled. I re-entered one of the entries from that profile, and the PDF shows the correct formatting.

Any newly-entered data will render correctly.
