### ISSUE TITLE
Allow images to pulled from a URL in the 'Upload image' modals

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#326]
The only way to add a new image to the system is to upload it from file. The Upload Image form should be modified to accept a URL or a file. If a URL is entered, then the image is downloaded and processed the same way as an upload (i.e. thumbnails, tiles, etc)

**Comment by m-hope** [comment]
Would this feature allow images to be included from other sources (eg: Flickr)?

**Comment by m-r-c** [comment]
Kind of. You would be able to add any image from any accessible URL, but with this solution the image would still be copied into the Profiles application, just like an uploaded image.

That might be good enough, but it would be nice to explore being able to link directly to images in flickr etc without having to copy them, the same way we do for ALA images. No idea what would be involved in that, though (or if it is even feasible).

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-83
