### ISSUE TITLE
Error occurs when you add then immediately delete an Attribute

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#327]
1. Edit a profile
1. Add a new Attribute. DO NOT REFRESH
1. Click Delete

The attributeId sent to the server is undefined. If you refresh then try again, the id is defined. 

The Delete URL should be updated with the attribute's UUID after creation.

**Comment by m-r-c** [comment]
May also happen when you add then immediately edit an attribute, too.

**Comment by chrisala** [comment]
The issue is the ala-ws-plugin is omitting the response body when the status code is != 200 (for a create 201 is being (correctly) returned).

**Comment by chrisala** [comment]
https://upsource.ala.org.au/ala-ws-plugin/review/AWP-CR-4
https://upsource.ala.org.au/profiles/review/PRFLS-CR-66
