### ISSUE TITLE
Keyplayer loading bugs

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#335]
```
jquery-1.11.1.min.js:4 Mixed Content: The page at 'https://profiles-dev.ala.org.au/opus/foa' was loaded over HTTPS, but requested an insecure script 'http://keybase.rbg.vic.gov.au/ws/keyJSON?callback=jQuery111103336361476947849_1461209919541&key_id=8&_=1461209919542'. This request has been blocked; the content must be served over HTTPS.
```

Sometimes the keyplayer does not load after clicking the Identify tab on the collection home page (not related to the https error above).

**Comment by chrisala** [comment]
Implemented lazy loading of the keyplayer and proxied access to the keybase server to avoid the mixed content error.
https://upsource.ala.org.au/profiles/review/PRFLS-CR-67
