### ISSUE TITLE
simplifying access to profiles within a collection

### ISSUE THREAD

**Issue by rp-ala** [AtlasOfLivingAustralia/profile-hub#350]
When you first come to profiles page, display a list (with photo tiles?) of all the species profiles the collection hasa already done, and then have an option (tab) to search etc. At the moment to find past entries is complicated as you have to search through scientific classification terms eg genus, family etc to find them and people don't know what these mean.

**Comment by m-r-c** [comment]
I have changed the search tab to list all profiles alphabetically by name by default. Results are still paged. Searching will override this list, but clicking Search when the text field is empty will reproduce it.

https://upsource.ala.org.au/profiles/review/PRFLS-CR-87
