### ISSUE TITLE
Cancelling a draft will update the last published date on a profile

### ISSUE THREAD

**Issue by sbearcsiro** [AtlasOfLivingAustralia/profile-hub#351]
Bug related to change #243 

1. Note last updated date on public profile page.
2. Create a draft version of the profile
3. Cancel the draft version of the profile
4. Note last updated date on public profile page, it is different from the date in step 1.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-105 

Reviewer please test this scenarios if in doubt about Integration Tests:

Draft created
Draft updated
Draft discarded
Draft published
Profile updated without draft.
