### ISSUE TITLE
Add autocomplete to the search field when the search type is Name

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#352]
Auto complete on the profile names, but do not prevent entering other values.

**Comment by RobinaSanderson** [comment]
Action: review where we use and don't use name autocomplete, see if there are other places we should apply it.

**Comment by RobinaSanderson** [comment]
We already have autocomplete on the Quick Search available on the Browse page, this is also a name search.
We should have autocomplete available on the name search in the menu bar.

**Comment by RobinaSanderson** [comment]
Apply the ALA "Contains" autocomplete search to the name searches, This includes:
- the search page name search
- the menu bar name search

These searches currently look first in the collections internal profile profile names, then the ALA names then (if selected) the NSL names. this functionality needs to be retained.

**Comment by ChrisPalmer1** [comment]
High priority

**Comment by RobinaSanderson** [comment]
@m-hope Hi Michael - Patricia and 1I have been thinking about this issue and we don't think the ALA and NSL needs to be included in providing autocomplete options.
For auto complete, the autocomplete suggestions should display names for profiles in the collection only, we don't want the autocomplete to include names if there is not a profile available.
That means that the names that could be suggested should either be the profile name for the concept in this collection, or a name that has been matched to a profile in this collection. So when we are looking for autocomplete suggestions we should stay within the collection and look at the profile names and matched names. Once a matched concept is displayed in the search results it will need to be identified as matched to the search term.

**Comment by m-hope** [comment]
Agreed, if it is possible to limit the autocomplete to only those profiles and their matched names without too much extra work, then that is more appropriate.

**Comment by RobinaSanderson** [comment]
After discussion with @m-hope it was agreed the autocomplete will provide suggestions based on the phrase entered rather than individual words, e.g. entering the search phrase "acacia dealbata" will suggest "xxx acacia dealbata xxx" not "xxx dealbata xxx acacia xxx" (where xxx may be no letters or any combination of letters).

**Comment by patkyn** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-141

**Comment by RobinaSanderson** [comment]
Tested for scientific name search in both header and on search page.

Found items using combined terms (as a phrase) rather than individual terms as expected.

Issue resolved.
