### ISSUE TITLE
BIE - Importing Vernacular name

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/profile-hub#356]

**Comment by m-r-c** [comment]
Issue moved to [AtlasOfLivingAustralia/bie-plugin #38](https://github.com/AtlasOfLivingAustralia/bie-plugin/issues/38) via [**ZenHub**](https://www.zenhub.com/)

**Comment by TaniaGLaity** [comment]
vernacular names being dealt with via taxonomy project
