### ISSUE TITLE
Profiles - Embed video (Youtube and Vimeo) 

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/profile-hub#361]

**Comment by javier-molina** [comment]
There are some styling issues yet to be addressed but functionality and code wise this is ready for review
https://upsource.ala.org.au/profiles/review/PRFLS-CR-90
https://upsource.ala.org.au/document-preview-plugin/review/DPP-CR-1


The styling issues can be sumarised in the screenshots below, the idea is that the document preview in profiles resembles more the layout of MDBA.

![image](https://cloud.githubusercontent.com/assets/8326394/15952435/11612fe8-2f04-11e6-8339-e87130b977cb.png)


![image](https://cloud.githubusercontent.com/assets/8326394/15952439/18e199ce-2f04-11e6-856a-14246f40e30c.png)

**Comment by javier-molina** [comment]
Layout and styling finished.

Layout remains vertical as there is not enough real estate to show horizontally.
![image](https://cloud.githubusercontent.com/assets/8326394/16027668/3512d3dc-321b-11e6-901f-73060e152122.png)

**Comment by javier-molina** [comment]
https://github.com/AtlasOfLivingAustralia/profile-hub/pull/379
