### ISSUE TITLE
BIE- Ability to render embedded videos

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/profile-hub#363]

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/bie-plugin/review/BP-CR-3
https://upsource.ala.org.au/profiles/review/PRFLS-CR-95

Reviewer please keep in mind that query in profile-services will change once the review comments for 361 are addressed.

**Comment by javier-molina** [comment]
https://github.com/AtlasOfLivingAustralia/bie-plugin/pull/36
