### ISSUE TITLE
Saving items in the Collection Admin screen sometimes results in blank fields being assigned a value of {}

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#368]

**Comment by ben3000** [comment]
I'm having trouble reproducing this in recent dev versions. Anyone still seeing this?

**Comment by m-r-c** [comment]
The map configuration section seems particularly prone to this. Create a new collection, then edit the config and change 1 field in the map section & save. Then refresh. Some of the other fields will now show {}.
