### ISSUE TITLE
After creating a new collection, the Site Overview cannot be edited

### ISSUE THREAD

**Issue by ben3000** [AtlasOfLivingAustralia/profile-hub#369]
After creating a new collection, the block containing input#dataResource is hidden in the form and (perhaps as a result) opusCtrl.opus.dataResource is null, causing the Save button to be disabled permanently.

**Comment by m-r-c** [comment]
That was good timing...I think I just fixed that.

**Comment by m-r-c** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-91
