### ISSUE TITLE
Administrators should not be able to delete the Author term from the acknowledgements vocabulary

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#374]
Edit Configuration
Acknowledgements vocabulary
Delete Author

This should not be possible, as all profiles have at least the Author acknowledgement category

**Comment by patkyn** [comment]
Before deletion, the system now checks for usages in the profile. This is now implemented in https://github.com/AtlasOfLivingAustralia/profile-hub/issues/375.
