### ISSUE TITLE
Name search: include the relationship between a profile matched to synonym etc and the search term

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#380]
Users can select the Name search, and then enter a related name such as a synonym and get back a profile matched to the accepted name.

E.g.
- there is a profile for Acacia dealbata and a profile for Acacia leucolobia
- the user can search for Acacia dealbata, and the results will include both profiles
- there should be something to tell the user why A. leucolobia was included (it was included because Acacia dealbata A.Cunn. is a misapplied name for A. leucolobia, while Acacia dealbata Link is the accepted name)

The NSL search service (see #354) includes this relationship information. We need to somehow incorporate that info into the elasticsearch results.

**Comment by RobinaSanderson** [comment]
Minor issue but part of public UI. Need decision on whether required for production release.

**Comment by ChrisPalmer1** [comment]
Yes, high priority for launch.

**Comment by patkyn** [comment]
According to the NSL name search by Acacia Dealbata  https://biodiversity.org.au/nsl/services/api/name/taxon-search.json?tree=AOC&q=Acacia+dealbata, can taxonomic status be used to explain why Acacia Leucolobia is also included in the result, in this case, it is taxonomic synonym?

**Comment by ChrisPalmer1** [comment]
When you search the NSL for Acacia dealbata, the name Acacia leucolobia also comes up, in the following statement: CHAH (2006), Australian Plant Census: - taxonomic synonym of: Acacia leucolobia Sweet. This means that the Council of Heads of Australian Herbaria have agreed that A leucolobia is a synonym for A dealbata; i.e. both have been names for the same organism, although only one is the currently accepted name for that organism; you can only have one current name for an organism.

**Comment by RobinaSanderson** [comment]
Waiting on mapping of NSL terms to preferred wording to be supplied by Russell Barrett

**Comment by KevinThiele** [comment]
I think this may perhaps be best done simply using "=" signs like the APC does; e.g. a search on "Acacia dealbata" should give the result:

<Acacia dealbata> Link
Acacia dealbata A.Cunn. nom. illeg. = <Acacia leucolobia> Sweet

<sharp brackets indicate the hyperlinks>

This is returned by the APC, so should be straightforward to implement?

It seems to me that simply using an = sign like this to indicate a redirection will be more informative to users than listing all the returned names with some type of suffixed nomenclatural designation. There is for example no need for users of a Flora to differentiate (at this point) between nomenclatural and taxonomic synonyms. What they will want to know is "I typed in name x, and the search is telling me that name x = name y"

**Comment by m-hope** [comment]
Need to consider:
- changing the search result text for each profile to the displayed profile name (ie: for matched profiles this includes the authorship)
- include the 'taxonomicStatus' field in the searche result (note: in the future this may change to what Kevin is indicating above)
 - where the search term directly matches a profile's name or matched name:
                 - if the search term matches the profile name and it is a APC concept put "(APC)" after the search result listing (as per taxonomicStatus)
                 - if the search term doesn't match the profile name or the name isn't an APC concept put ""(internally matched)" after the search result listing.

Note: I need to clarify the actual display for the last item above.

**Comment by RobinaSanderson** [comment]
From Michael:
I think we can simplify this (maybe) to the following (I’ve given two examples… first one is a synonym and the second is a misapplication… but we treat them the same way):

Search term is: Acacia dealbata
Acacia dealbata Link  (accepted name)
Acacia leucolobia Sweet  (accepted name for Acacia dealbata A.Cunn.)
Acacia notaapcname (internally matched to Acacia dealbata Link)

Search term is: Acacia acinacea
Acacia acinacea Lindl. (accepted name)
Acacia triquetra Benth. (accepted name for Acacia acinacea Lindl.)
Acacia anothername (internally matched to Acacia acinacea Lindl.)

The first case in both examples, is where the profile matches the search term and the NSL (or ALA???) determine it is the accepted name for the search term (ie: for the NSL it is in the acceptedName tree of the NSL JSON return and the taxonomicStatus is “ApcConcept” or “accepted”) and is built using: [<i>profile name</i> + profile authorship + “ (accepted name)”]

The second case is for any profile that matches the synonym.acceptedNameUsage field found in the top level Synonym tree of the NSL JSON return (regardless of the taxonomicStatus), and is built using: [<i>profile name</i> + profile authorship + “ (accepted name for “ + [<i>canonicalName</i> + scientificNameAuthorship+”)”]

The last case is where a profile has been manually matched to another (ALA accepted name) and the matched name matches the search term (need to explore this condition a bit…), and is built using: [<i>profile name</i> + “ (internally matched to ” + <i>profile matched name</i> + profile matched author + “)”]

Note: the actual link to the profile will only highlight the profile name + profile author part of the display.

**Comment by KevinThiele** [comment]
The following is a list of all unique values in the APC TaxonomicStatus field, with proposed mappings to the text that should go in parenthesis in the above scheme. ?? means either I don't understand the term (e.g. DeclaredBt), or we should not deal with these e.g. common and trade names. In almost all cases the mapping is to "accepted name for" except for all doubtful cases, which should be prefixed with "probable" :

ApcConcept -> "accepted name"
ApcExcluded -> Note - this is equivalent to a null result. it should result in a no match
basionym -> "accepted name for"
common name ??
DeclaredBt ??
doubtful misapplied -> "probable accepted name for"
doubtful nomenclatural synonym -> "probable accepted name for"
doubtful pro parte misapplied -> "probable accepted name for"
doubtful pro parte taxonomic synonym -> "probable accepted name for"
doubtful taxonomic synonym -> "probable accepted name for"
isonym -> "accepted name for"
misapplied -> "accepted name for"
nomenclatural synonym -> "accepted name for"
orthographic variant -> "accepted name for"
pro parte misapplied -> "accepted name for"
pro parte nomenclatural synonym -> "accepted name for"
pro parte taxonomic synonym -> "accepted name for"
replaced synonym -> "accepted name for"
taxonomic synonym -> "accepted name for"
trade name ??

**Comment by afuchs1** [comment]
DeclaredBT - declared broader than (we are working to remove these)
Ignore - trade names, to do with PBR etc (Cultivars, Plant breeder rights names etc)

Can we think of this as {search name}
output:
**{search name}** and nothing more if 'APCconcept' - it is the same
{search name} = **{APC name}** for isonyms, basionyms etc...
{search name} probably **{APC name}** for all 'doubtful'

**Comment by patkyn** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-146

**Comment by RobinaSanderson** [comment]
Hi @m-hope  - I created a profile in the ALA Test collection with the name Arabidella newnamia and matched it to Arabidella Trisecta. When you see it in the search results it has (accepted name) next to it when it has been internally matched to the accepted name. I think this may be an issue, what do you think?

**Comment by RobinaSanderson** [comment]
Issue complete.
