### ISSUE TITLE
ALA Admin users cannot see profiles in the search results or browse tabs in private collections

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#382]
ALA Admin users should be able to do everything, even in private collections.

When a collection is private, even ALA Admins need to be added to the list of collection users before the search results or the lists on the browse tab will show profiles.

**Comment by RobinaSanderson** [comment]
This may be fixed. Michael to confirm.

**Comment by m-hope** [comment]
Can confirm that as an ALA Admin, I can see and edit any (Public or Private) collections even if I am not in the collection user list.
