### ISSUE TITLE
Externalise the log4j config

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#383]
Log4j config (specifically the log level) is controlled in the Config.groovy, so you can't change it on the fly, and you can't have different settings in different environments (e.g. profiles-dev DEBUG, prod INFO).

This should be externalised so it can be changed without a code change, and ideally without a restart, and prod should be set to INFO.

**Comment by ben3000** [comment]
It looks like this requirement can be met with a change to the web.xml template in Grails 2.x, see http://www.tothenew.com/blog/externalize-and-reload-grails-log4j-configuration/
