### ISSUE TITLE
UI - Taxon view - Distribution tab - apply the facet name translation to the legend title

### ISSUE THREAD

**Issue by m-r-c** [AtlasOfLivingAustralia/profile-hub#384]
we need to apply the facet name translation to the legend title (eg: in profile: https://profiles.ala.org.au/opus/alatest/profile/Acacia%20hystrix, if you go to the Distribution Tab, the map legend is set to "Institution_uid"... this needs to be translated to "Institution" as per the Biocache view: http://biocache.ala.org.au/occurrences/search?q=lsid:http://id.biodiversity.org.au/node/apni/2909097#tab_mapView).

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-106

**Comment by m-hope** [comment]
Have reopened this issue as we need to apply the facet name translation to the legend title (eg: in profile: https://profiles.ala.org.au/opus/alatest/profile/Acacia%20hystrix, if you go to the Distribution Tab, the map legend is set to "Institution_uid"... this needs to be translated to "Institution" as per the Biocache view: http://biocache.ala.org.au/occurrences/search?q=lsid:http://id.biodiversity.org.au/node/apni/2909097#tab_mapView).

**Comment by RobinaSanderson** [comment]
Need to include legend in view, then fix if still applies.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-156

**Comment by m-hope** [comment]
Confirmed fixed... need to note that the editor needs to set a facet to colour the map dots by before the legend will appear.
