### ISSUE TITLE
"Loading..." message and spinner displayed forever on external service error

### ISSUE THREAD

**Issue by ben3000** [AtlasOfLivingAustralia/profile-hub#392]
The "Loading..." message and associated spinner displays forever on external service error, especially for NSL requests. The error should be detected and a message placed in the panel to indicate that the service is unavailable. For extra points, the message should contain a button to permit the request to be retried.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-108
