### ISSUE TITLE
Map zoom setting

### ISSUE THREAD

**Issue by KevinThiele** [AtlasOfLivingAustralia/profile-hub#395]
On a PC screen, setting the default map zoom level in Admin to level 4 gives a map with Australia a bit too small; setting it to 5 makes it a bit large (southern Tasmania gets cut off). The level functions as an integer (even though it accepts a decimal value). Can this be tweaked so there's a level where the whole of Australia fits well.
Note that the fit differs on different devices - setting the level for a PC screen means that it doesn't fit on a tablet or phone - hence this issue relates to small-screen responsiveness issues.

**Comment by RobinaSanderson** [comment]
The requirement to set the zoom level to the whole of Australia without Papua New Guinea and part of Indonesia showing was investigated and can't be done with the current map technology.

This will be closed.
