### ISSUE TITLE
Enabling/disabling attribute boxes

### ISSUE THREAD

**Issue by KevinThiele** [AtlasOfLivingAustralia/profile-hub#396]
Would be good to have a checkbox option "Enable attribute content boxes". With this on the attributes would be boxed with a header as they are at present. With this checked off the attributes would not be boxed - see the design doc.

**Comment by RobinaSanderson** [comment]
Relate to mockups. This may be a way of getting around concatenating attributes see #179

**Comment by RobinaSanderson** [comment]
Need to decide if this is the way we will go or close this issue.

**Comment by RobinaSanderson** [comment]
This issue is covered in #179
