### ISSUE TITLE
Formatting buttons not displaying properly in Firefox browser (okay in Chrome)

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#399]
![image](https://cloud.githubusercontent.com/assets/8856025/17843161/34bd7a16-686e-11e6-99ec-9bbe51cb791b.png)

See attached image... in Firefox the format buttons when editing profile attributes aren't displaying, although the buttons themselves work okay.

**Comment by m-hope** [comment]
Format buttons also don't display properly in Microsoft IE either.

**Comment by sat01a** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-104

**Comment by sbearcsiro** [comment]
IE dealt with in ticket #411
