### ISSUE TITLE
Private image issues

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#402]
Need to fix a number of bugs:
 - when saving private image metadata you get a 'Permission Error' however the image appears to still save.
 - Deleting a private image doesn't work (the image reappears if you re-edit the 
 - Image settings don't save (ie: when you hit the save button, the settings for each image (eg: Display on public view) revert to original values.
 - system kicks you out when trying to add image captions

**Comment by m-hope** [comment]
You can also only select the main/primary image from the first page of images (you can select images from other pages, but when you save the setting is lost.

**Comment by m-hope** [comment]
Further info... 
- saving private images - can't currently recreate this on my PC, but I definitely saw this happening to Zoe... I'll have to chase Zoe to get exact details.
- deleting private images - using this profile: https://profiles.ala.org.au/opus/alatest/profile/Cynoglossum%20creticum, if you try to delete the first image (the ALA logo), you'll get the prompt "Loading images" but the ALA logo remains.
- Image settings - using the above profile, try to set the "Display on Public View" option for the ALA logo to "No"... once you hit the Save button, the setting reverts to "Yes". Note: this problem also seems to affect Repository images as well, but the "Use as Main Image" option for both private and repository images seems to work okay.
- adding image captions - I suspect this issue is related to Zoe's permission error... I'll chase.
- setting main image from page 2 - use this profile: https://profiles.ala.org.au/opus/alatest/profile/Acacia%20dealbata, in edit mode, select the first image (a landscape image of the whole tree) as main image and Save... works fine... then switch to page 2 of the images and select the last image (portrait image of a acacia flower) as main image... once you hit Save, the screen redraws, the images displayed have reverted back to page 1, even though the page buttons at the bottom indicate page 1 (you will note that the first image is correctly set to not be the main image, even though it still is at the top of the page).  If you refresh the page, the page indicators at the bottom of the images corrects itself to indicate it is on page 1 and if you move to page 2, the last image has the "Use as Main Image" setting correct, however the image at the top of the page is still the  first image (the landscape whole tree).

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-115
