### ISSUE TITLE
Allow formatting on any manually entered text, including: image captions, links, specimens, BHL references, Bibliography,etc)

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#404]
As many cases where text can be entered into a profile contains species names (eg: image captions, etc), we need to allow formatting of the text to handle italicized names, etc.

**Comment by m-hope** [comment]
Note: has the potential to allow each image for a profile to have different style for the caption...

**Comment by m-hope** [comment]
Note: only Italics, Bold and Underline format options are required for this functionality and only those locations specified in the title of this issue.

**Comment by m-hope** [comment]
Depending on how easy it is to do, we may want to include Superscript and Subscript format options as well..

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-127
