### ISSUE TITLE
Allow configuration of 'Editor' permissions…

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#405]
At the moment, editors can delete and publish profiles, but adding options (at the collection settings level)  to restrict 'editor' functions (eg: remove the ability to delete and publish profiles) would instigate a 'workflow' that may resolve a number of issues around the reversal of critical functions, instead editors (sub-editors) need to email an admin (or editor) in order to publish or delete a profile.  This would negate the need for a soft-delete option ( #237 ), additional reports and potentially an alert function ( #73 ).

An alternative solution could be to include a new sub-editor category with the reduced permissions...

**Comment by m-hope** [comment]
Concensus is to go with the alternate solution of having two separate roles: super editor and basic editor.

**Comment by sat01a** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-111
