### ISSUE TITLE
Current image captions appear to have a 256 char limit... can this be increased?

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#408]
There are a number of examples in Flora of Australia where an image caption needs to be quite long to describe the full taxonomy for a particular image.

**Comment by m-hope** [comment]
Agreed that the new size limit should be set to 1024 chars.

**Comment by sat01a** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-112
