### ISSUE TITLE
Allow a user to limit/filter the profiles viewed in a collection to a specific region or taxonomic group

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#412]
As discussed with Kevin:

"So the idea in its most complete form (asking for the gold version here) is as follows:

Someone could, from within the eFlora of Australia, specify a simple 2-part query filter “I’m interested in this taxonomic group in this area” e.g. 
“I’m interested in Myrtaceae in an area centred on Kalgoorlie with a radius of 200 km”
“I’m interested in all flowering plants in the Geraldton Sandplains IBRA region” 
“I’m interested in Acacia within 50 km of my home”
“I’m interested in Asteraceae in the whole of Australia”

Each query would thus comprise a taxonomic group at some level above species, and a defined area.

The eFlora would pass the query to AVH, the ALA or some other source, which would return a list of taxa. Note that for some queries this list would comprise species in a genus (e.g. “Acacia within 50 km of my home”) but in other cases would comprise a deeper taxonomy (e.g. “All flowering plants in the Geraldton Sandplains”.

With the filter in effect, the only taxa available in the eFlora (now an eFlorula) will be those in the list. Searching, browsing, using the keys, the classification hierarchies etc. will now be constrained to the checklisted taxa only. The filter could be subsequently cleared, and we would be back to the whole Flora.

Note it will be most useful if the filters can be stored and used in subsequent sessions, because particular users may want to use the eFlora as an eFlorula for multiple sessions (or forever, if they don’t get out much). It will be best for this purpose to somehow store the query not the checklist, so that the eFlorula will remain current as new records are added to AVH etc.

The easy part I think is passing the query and getting the checklist. The two things we need to think about carefully are how to apply the filter within a session, and how to store between sessions.

Regarding this – note that Niels has done this for KeyBase, including the filtering and the storage of filters (which means that the keys part, which otherwise would have been hardest, is easy). Would be worth talking it through with him."

**Comment by RobinaSanderson** [comment]
@m-hope In our review of these issues, we thought we probably need a design meeting about how we could do this. Who should be invited to that meeting?

**Comment by RobinaSanderson** [comment]
This story deals with the application of a set of taxa to the functions of the eFlora regardless of how the set is defined, stored and made available to the eFlora (see #480 for how this might be done). This may be done at collection level for all profiles in the collection (either generated or manually populated), and a user will be able to define a set of taxa to be used in the following functions:
- search 
- browse
- keys
- adding children to .pdf output
- breadcrumbs
- tree button on taxon profile
- ?? (there may be more)

Business requirements:
1. The collection administrator (default option) or user defines the set of taxa to be used and this is stored in the system.
2. All system funcitonality is restricted to this set. This includes:
- Search results - name search, text search, menu bar name search, menu bar text search (Note: not sure whether a full search would be done followed by filtering to the set of taxa, or whether just the profiles in the set are searched?)
- Browse - left hand taxon level browse pane, browse results, quick browse of collection profiles
- Keys - only key trees supporting the taxa in the set would display, for example, if a  set only contained conifers, all keys relating to other types of plants would be hidden
- .pdf - when a user selected to include children taxa in a .pdf, only children present in the specified set would be included
- breadcrumbs - the drop down lists available in breadcrumbs to navigate to other taxa at that level, will only display items from the specified set
- the tree button on a taxa page will only display items from the specified set.

**Comment by RobinaSanderson** [comment]
Closed by mistake (Doh!)

**Comment by ChrisPalmer1** [comment]
Very high priority

**Comment by RobinaSanderson** [comment]
If there is a profile in the system for a taxa that is not in the collection master list (perhaps the taxa is no longer recognised or has been renamed), and the user defines a list which includes the taxa, should the system display the profile? My guess is yes.
@ChrisPalmer1 do you have an opinion?

**Comment by RobinaSanderson** [comment]
Spoke to Chris and got answers for the outstanding questions, these have been added to the requirements comment.

**Comment by m-hope** [comment]
Linked to issue #512 which provides the list that can be selected by the functionality in this issue.

**Comment by m-hope** [comment]
I'm closing this issue as the Filter functionality has been implemented and is working.  The improvements and enhancements to this functionality around the generation or selection of appropriate lists is covered in other issues (eg: #512, #548)
