### ISSUE TITLE
"Export as PDF" function doesn't work if Taxonomy is selected as a component of the PDF.

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#413]
Using the profile: https://profiles-dev.ala.org.au/opus/foa/profile/Acacia%20dealbata as an example, if you try to export a PDF (under the Options button) and 'Taxomony' is selected as an item to export to the PDF, the user will get an error message as follows:

![image](https://cloud.githubusercontent.com/assets/8856025/18190852/e9ef72ac-7108-11e6-9b80-1fbfd370bc49.png)

(they may also get a dialog box asking to allow download of multiple files) and the PDF is not created.  If Taxonomy is not selected to include in the PDF, it works fine.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-109
