### ISSUE TITLE
Editing - UI - problem with persisting "Show information from supporting collections" option

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#414]
Firstly, if a profile is in draft mode ("Lock for major revision") then the "Show information from supporting collections:" switch doesn't remain persistent unless the user publishes the draft changes.

Steps to recreate:
1. use this profile: https://profiles-dev.ala.org.au/opus/bfb23cb2-0459-4223-b943-225331016411/profile/Acacia%20abbatiana that is in Draft mode... 
2. go into Edit mode, 
3. click on the show info from supporting collections... 
4. click on "Public View"... 
5. go back into Edit mode - you will need to reclick the Supporting collections button. 

#440 is related and deals with viewing supporting collections information with the same attribute from this collection. however, this issue should be fixed first.

**Comment by RobinaSanderson** [comment]
Split this into 2 issues

**Comment by RobinaSanderson** [comment]
Needs to be persistent when you click the use "supporting collections" option.

Currently only persistent when you have saved another attribute.

**Comment by ben3000** [comment]
See #535 for a related problem I exposed while working on this issue.

**Comment by ben3000** [comment]
There is currently no showLinkedOpusAttributes property on a DraftProfile, which prevents this setting from being saved correctly. Adding that property permits it to be saved. However, the status of showLinkedOpusAttributes needs to be copied across to the main profile once the profile's draft changes are published or discarded, otherwise the problem returns again.

**Comment by ben3000** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-167

**Comment by m-hope** [comment]
Tested using this profile: https://profiles-dev.ala.org.au/opus/mlh/profile/Bixa%20orellana, and collection is allowed to use supporting collection data.
 - edited profile and set to draft mode
 - checked the use supporting collection option (and no other buttons)
 - left edit mode and into public view
 - re-entered edit mode and confirmed the supporting collection option was still turned on
 - turned supporting collections button off
 - left edit mode
 - re-entered edit mode and confirmed supporting collections option was off.

Test complete, this issue can be closed once code review done.
