### ISSUE TITLE
Name matching issues...

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#417]
Not sure if these two issues are related, but in the new release of code to Prod and Dev, but there seem to be two names based issues:
1. Creating a new profile doesn't seem to place the profile in the hierarchy correctly even though the name of the profile is recognised and matched to an APC accepted name. eg: https://profiles.ala.org.au/opus/alatest/profile/Acacia%20arrecta (note: the breadcrumb starts at acacia arrecta).
2. A profile with an unmatched name seems to generate errors ("Error calling /nsl/listConcepts/null, response: 500. Please refresh the page.") if it is displayed (either in Public View or Edit mode).  As it is possible to have profiles that do not match the ALA or NSL indexes this error should not be displayed.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-114
https://upsource.ala.org.au/ala-install/review/AI-CR-16
https://github.com/AtlasOfLivingAustralia/ansible-inventories/commit/ba87aa73d778f3c588ab88937b23d0fd299eeebe

**Comment by m-hope** [comment]
I'm going to reopen this issue as a bug...

While the new profile is picking up the taxonomy correctly, this doesn't seem to be translating to the breadcrumb and the keybase key properly.
Using this profile as an example: https://profiles.ala.org.au/opus/alatest/profile/Emmenosperma
1) with the breadcrumb, in Public view there are no drop down links even though there are species profiles related to this profile, and in edit mode the system reports that "The taxonomy for this profile is unknown."
2) this problem may be related: even though there are Emmenosperma species in the loaded keybase databse, it doesn't seem to be picking this up and creating the Key tab for this profile.

**Comment by RobinaSanderson** [comment]
These issues appear to have been fixed with the last release.

We'll close this issue and create new ones if further problems are found.
