### ISSUE TITLE
Image issues cont.

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/profile-hub#419]
**Draft images**
CRUD operations need to be supported for draft image files, currently only metadata is supported.

For example, currently deleting an a draft image will remove the image file for the published image.

**Publishing to external repositories**
 Publishing an image externally (to biocache) will override any previous images.
This is at least true for a Biocache instance storing images locally.
Biocache issue: https://github.com/AtlasOfLivingAustralia/biocache-service/issues/110

**Setting an image as primary from another page other than the first**
TBC if this is still an issue.

**Comment by m-hope** [comment]
Can confirm that setting a primary image from another page is still not possible and is still an issue.

**Comment by m-hope** [comment]
Can confirm that the issue of selecting images from other than page 1 is still a problem... known problems are (use https://profiles-dev.ala.org.au/opus/bfb23cb2-0459-4223-b943-225331016411/profile/Caryophyllaceae as an example):
 - any images selected on page 2 or higher will not display (even though the switch to display the image is saved), regardless of whether the image is set as the primary image or not.
 - selecting any image to display from a page will deselect images on any other pages.

**Comment by patkyn** [comment]
Turn off images in page 2 causes page 1 switch to be turned on

**Comment by sbearcsiro** [comment]
@patkyn could you create an upsource review for this task please?

**Comment by patkyn** [comment]
@sbearcsiro here it is https://upsource.ala.org.au/profiles/review/PRFLS-CR-122

Thanks

**Comment by patkyn** [comment]
Gallery tab - if some of the images in a page has been turned off, the Page Navigation went missing
Every page should show images consistently (no empty page)

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-125
