### ISSUE TITLE
Image bug

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/profile-hub#420]
The image bug in Profiles that I mentioned is causing images not to load and the following error to be returned, unless the first image in the list is toggled to ‘show in public view’. Once this is done, the images seem to work as expected. It would be helpful for our Yugul Mangi partners working in Profiles at the moment, if this bug could be fixed.

**Comment by javier-molina** [comment]
![error_loading_images](https://cloud.githubusercontent.com/assets/8326394/19987926/ac9d40a6-a271-11e6-9369-744ff176853c.png)

**Comment by javier-molina** [comment]
Trivial fix:
https://upsource.ala.org.au/profiles/review/PRFLS-CR-116

Steps to test:

Before change a call to the service below will cause an error (NPE in the backend) if no primary image is defined but there are images for the profile

https://profiles.ala.org.au/opus/abd4d7ae-37f9-4770-95d3-19a5286bd6c0/profile/df2e1951-5bbe-43bb-8cbf-ea2f163692ec/primaryImage 


After the fix, the same call will return an empty JSON object {}

**Comment by javier-molina** [comment]
@sathishala if you could review this just for completeness it would be great.

I am preparing the build in the meantime

Ta
