### ISSUE TITLE
Name matching bug

### ISSUE THREAD

**Issue by sat01a** [AtlasOfLivingAustralia/profile-hub#421]
Bug is occurring with name matching. If a profile is named with a common/language name (e.g. Jupi) rather than the scientific name, the option to match it to a scientific name (while still displaying the language name as the profile title) is not working. This is also an important bug for Yugul Mangi rangers to have fixed, as they are titling their profiles with language names but want to be able to link to the species information that the matching to scientific name provides.

**Comment by javier-molina** [comment]
https://github.com/AtlasOfLivingAustralia/ansible-inventories/commit/801ff3e4cd688cf3ec4d4fef4bebb62cc711f93d
