### ISSUE TITLE
Release non snapshot 2.1 version to prod

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/profile-hub#422]
Currently profiles-hub depends on asset-pipeline:2.11.2-SNAPSHOT, but there is no release version available for that plugin which hold us from tagging a release.

Using asset-pipeline 2.11.0 breaks the build.

More investigation is needed to find a suitable version of asset pipeline.

**Comment by RobinaSanderson** [comment]
Talking to Javier, this needs to be fixed before we launch the product in June. So I will add this to the To Do column.

**Comment by sbearcsiro** [comment]
This is not technically true, a snapshot dependency does not prevent a release build being generated.

On the other hand a grails 2 asset pipeline v2.12.4 plugin has been released to the main Grails plugin portal.

**Comment by RobinaSanderson** [comment]
Hi @sbearcsiro. Do you think it should stay in for the next sprint?

**Comment by RobinaSanderson** [comment]
Seems like a good idea to do, can back out.
