### ISSUE TITLE
Question: Does it make sense to set an image as primary even if it won't be displayed publicly?

### ISSUE THREAD

**Issue by javier-molina** [AtlasOfLivingAustralia/profile-hub#423]
In the screenshot below it is possible to define a non-displayed image as primary, yet the image will only be visible only if set to Display on public view. 

As a user I find that confusing but if I am missing a business case where this works as per design I am happy to hear.

![screen shot 2016-11-03 at 2 51 49 pm](https://cloud.githubusercontent.com/assets/8326394/19990881/409e77e4-a285-11e6-8390-aed651e934cb.png)

**Comment by ben3000** [comment]
I would find that confusing.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-123
