### ISSUE TITLE
Indication of number of images for a profile is incorrect for selected images.

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#424]
If an author selects only a number of images from all available, the profile still reports the number of images as the full amount and has a page selection tab at the bottom of the section.  EG: use https://profiles-dev.ala.org.au/opus/bfb23cb2-0459-4223-b943-225331016411/profile/Caryophyllaceae as an example... you'll need to lock the profile for revision (separate bug #425) to see all the images, but if you select 3 and mark on a the primary image, save that, then go into Public View mode, the image section says there are (81) images available (even though only 3 are displayed) and the page selector is visible.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-126
