### ISSUE TITLE
Taxa hierarchy is only recognised if a profile is locked for revision...

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#425]
If a profile is not locked for revision, the breadcrumb at the top of the page indicates the profile taxonomy is unknown... if you go into edit mode, images will not be available unless you are in lock for revision mode.

**Comment by m-hope** [comment]
Probably should be addressed in conjunction with #417.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-119

Review in conjunction with #430
