### ISSUE TITLE
Name matching failing if there is a homonym (same name for different taxa)

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#426]
Name matching is failing if the profile name is a homonym (eg: Stellaria which is both a shellfish (Stellaria Möller) and a plant (Stellaria L), both names are correct and legal)... it might be possible the shellfish name is returned first and presumably ignored by eFlora as it is in the wrong kingdom...
Need to check what is returned by the ALA names index and then either:
    - intelligently pick the plant, or:
    - allow the profile author to select the correct taxonomic name...

**Comment by m-hope** [comment]
This issue could be grouped under a general 'name matching review' as there are still a number of issues around the general name matching function...

**Comment by m-hope** [comment]
In talking to Doug, the issue is that if a supplied name is a homonym, then an error is returned by the ALA names service saying that the name can't be resolved to a single name.   This is then interpreted by Profiles to be that there is no matching name when in fact the issue is that there are too many.

This could be partially solved (or at least reducing the instances where this issue would occur) by having a configuration field at a collection level which could limit the name matching to a particular kingdom and this info would be passed in the name matching request...

**Comment by m-hope** [comment]
Potentially should be addressed at the same time as #417.

**Comment by nickdos** [comment]
Arenaria another name to test

**Comment by sbearcsiro** [comment]
@nickdos Could you create an upsource review for this task please?

**Comment by nickdos** [comment]
@sbearcsiro done - assigned to you.

**Comment by m-hope** [comment]
Testing with Stellaria, Arenaria and Zieria all work correctly.
