### ISSUE TITLE
Save All button confused when Map is edited

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#428]
EG: see https://profiles.ala.org.au/opus/alatest/profile/Stellaria%20angustifolia%20subsp.%20angustifolia.

If you go into edit mode and then "Edit Map Configuration", if you make a change to the map query, the Save All button appears at the bottom of the page, but doesn't disappear if clicked... for each click of the Save All button the view of the map changes (going from edit mode to non-edit mode and back again).

There are cases where it gets so confused the only way out is to 'Leave the page without saving'...

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-118
