### ISSUE TITLE
Map Snapshot is not visible if no images present

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#429]
If a profile does not have images available then the map snapshot image is not displayed in Public View (eg: https://profiles.ala.org.au/opus/foa/profile/Stellaria%20papillata), but it is displayed if there are images in the gallery (eg: https://profiles.ala.org.au/opus/foa/profile/Stellaria%20pungens).

**Comment by m-hope** [comment]
probably need to be looked at when examining #419...

**Comment by patkyn** [comment]
Map snapshot seems to be loaded fine in profile-dev for the profile without images. 
https://profiles-dev.ala.org.au/opus/bfb23cb2-0459-4223-b943-225331016411/profile/Stellaria%20angustifolia%20subsp.%20angustifolia

However, when we try to Publish the profile and take a Snapshot before publish, there is an error 500

```
016-12-08 16:24:13,853 DEBUG [AccessControlFilters] User null is not authorised to access action ProfileController.retrieveLocalThumbnailImage
2016-12-08 16:24:13,964 ERROR [GrailsExceptionResolver] IOException occurred when processing request: [POST] /opus/bfb23cb2-0459-4223-b943-225331016411/profile/4d74f532-d30d-46b4-b832-1a0d697b90f0/publishDraft
Server returned HTTP response code: 403 for URL: https://profiles-dev.ala.org.au/opus/bfb23cb2-0459-4223-b943-225331016411/profile/4d74f532-d30d-46b4-b832-1a0d697b90f0/image/thumbnail/mapSnapshot.jpg?type=PRIVATE. Stacktrace follows:
java.io.IOException: Server returned HTTP response code: 403 for URL: https://profiles-dev.ala.org.au/opus/bfb23cb2-0459-4223-b943-225331016411/profile/4d74f532-d30d-46b4-b832-1a0d697b90f0/image/thumbnail/mapSnapshot.jpg?type=PRIVATE
```

**Comment by m-hope** [comment]
I think the issue only occurs when the collection is set to display with a tabbed format... the primary image (and the map snapshot) are supposed to be visible down the right hand side.  Eg: this profile is supposed to be what it looks like: https://profiles-dev.ala.org.au/opus/b409cc1e-4c07-435b-8678-fc6c958662be/profile/Stellaria.
... but this is what happens if there is no images to display: https://profiles-dev.ala.org.au/opus/b409cc1e-4c07-435b-8678-fc6c958662be/profile/Stellaria%20multiflora.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-124
