### ISSUE TITLE
Breadcrumb drop downs not always showing

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#430]
The original intention of the breadcrumb is that for each taxon rank in the breadcrumb there would be a drop down box which listed all the profiles available under that taxa (eg: see the breadcrumb on the profile page: https://profiles.ala.org.au/opus/alatest/profile/Acacia%20dealbata, under ACACIA you can see all the Acacia genera and species... you can also click on the ACACIA name and be taken to the Acacia profile page).

But for some profiles (potentially all new ones) these features are not available on the breadcrumb (eg: see https://profiles.ala.org.au/opus/alatest/profile/Acacia%20abrupta from the same collection)?

Is this related to the problems we are having matching the name for new profiles?

**Comment by KevinThiele** [comment]
While fixing this bug, can you also look into restricting the items in each dropdown list to the next taxonomic level only. Thus, the dropdown for Fabaceae should list only genera of Fabaceae (not species). In addition to being a more sensible (hierarchical) navigation option, this will have the added and important benefit of reducing these often over-long lists to a more reasonable length, thus improving the breadcrumb's utility for navigation.

**Comment by m-hope** [comment]
Agree with Kevin that drop downs should only include immediate child taxa not all sub taxa.
Could also look at #397 unless it is a lot more work then leave it until later...

**Comment by m-hope** [comment]
For testing I seem to be able to create the issue using this profile: https://profiles-dev.ala.org.au/opus/bfb23cb2-0459-4223-b943-225331016411/profile/Cynoglossum. 

If this profile is in Public view, the breadcrumb has the error : "The taxonomy for this profile is unknown."
If this profile is placed in normal edit mode, the breadcrumb has the error : "The taxonomy for this profile is unknown."
If the profile is placed in Draft mode (Lock for major revision) then the breadcrumb becomes visible, but without the links for each 'crumb' element.
Returning to Public mode will bring back the error.  Also If you re-enter Edit mode again you will still see the error... the only way to see the breadcrumb is to discard or publish the draft changes (in Edit mode) and then re "Lock for major revision" (ie; the breadcrumb is only visible when you first enter Draft mode).

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-119

Review in conjunction with #425
