### ISSUE TITLE
Need to be able to differentiate between an editor and a contributor

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#431]
Need the ability to recognise and editor (someone who copies in information from another source) and a contributer who provides the information..  Ie need to be able to attribute the source of the content. (eg: https://profiles.ala.org.au/opus/foa/profile/Stellaria%20graminea shows Russell Barrett as the contributor, when in fact he was the editor that copied (uploaded) the text from the original Flora of Australia)...

Need to also consider the date the original source was published?

**Comment by RobinaSanderson** [comment]
This needs to be addressed in the screen mockups (to be done)

**Comment by RobinaSanderson** [comment]
This issue is now covered in #458
