### ISSUE TITLE
Height of attribute boxes when editing (perhaps collection setting?)

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#432]
Can a property be set by admin to specify the height of individual text boxes in the editor view? Currently all edit boxes are the same height, but many consistently only need a line or two of text, so there is a lot of unnecessary scrolling for editors

**Comment by ben3000** [comment]
This might be better accomplished as a javascript that makes individual text boxes as large (or a bit larger) than their content.

**Comment by sbearcsiro** [comment]
I've added an "autogrow" plugin to the attribute rich text editors, which makes them start out at 1 line but automatically grow to wrap the content.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-131
