### ISSUE TITLE
keybase keys are not appearing for profiles

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#435]
Keybase keys are supposed to be automatically inherited for profiles where a matched name is available in the appropriate key...

Specific examples to follow.

**Comment by m-hope** [comment]
For example the Acacia profile: https://profiles-dev.ala.org.au/opus/foa/profile/Acacia. There should be a  Key tab that lets the user select a species from the keybase data.  This may be an issue with names matching that no longer connects the profile with an available name in Keybase.

**Comment by nickdos** [comment]
Looks like an issue with keybase server. Niels fixed a broken web service endpoint but its still not returning the correct results and so some keys don't load. Waiting on un update as Niels is in the US right now. 

I can confirm that keys do show on profile pages now:

![image](https://cloud.githubusercontent.com/assets/532845/21212388/5301d84c-c2e0-11e6-9dd5-45b0eff6ed47.png)
