### ISSUE TITLE
Keys related error message when opening collection

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#437]
When opening a collection the following error message displays:
![image](https://cloud.githubusercontent.com/assets/23368496/21912947/5d12fb96-d97d-11e6-8058-6bfdb9106cad.png)

this occurs with at least the Flora of Australia collection, the ALA Test and ALA Test Design collections. I haven't checked the others.

**Comment by m-hope** [comment]
This has now been resolved... it was a change in the Keybase API call, which for the time being has been restored in Keybase.

However, long term, all Keybase calls from within eFlora need to be reviewed and updated to the new APIs.  I have modified issue #264 to include this component.
