### ISSUE TITLE
Name search related issue

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#438]
I'm getting an error message in the Flora of australia collection when I do a name search using the term "arenaria" (this is one of the names identified by Russell Barrett as having a homonym). I can create the profile in the ALA test design collection and search by text in the Flora of Australia collection, but get the following when I search by name:
![image](https://cloud.githubusercontent.com/assets/23368496/21916994/6e996286-d998-11e6-8852-f60dbff0f2a9.png)

**Comment by ChrisPalmer1** [comment]
High priority

**Comment by RobinaSanderson** [comment]
Check once new names index is released (currently being updated).

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-135

**Comment by m-hope** [comment]
Confirm searching for Arenaria no longer generates an error and correctly returns the Arenaria profile if it exists.
