### ISSUE TITLE
Text box and scroll problems when editing in Firefox

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#439]
Steps to recreate"

1. Open ALA test design in Firefox (I am using version 50.1.0)
2. Select a profile to edit (I used "Arabidella Nasturtium")
3. Place cursor in text box

Problem: as soon as you place your cursor in the text box, it resizes off the browser page and you lose your scroll bar.

You need to use tab to move to other text boxes. Saving the page resets the text box sizes, but clicking into one to edit causes the problem again.

**Comment by RobinaSanderson** [comment]
![image](https://cloud.githubusercontent.com/assets/23368496/22086944/6fbffce2-de2f-11e6-9f28-a6d8b80b8a66.png)

**Comment by RobinaSanderson** [comment]
Should also check IE and any other major browsers.

**Comment by m-hope** [comment]
I can confirm this also occurs on my Mac Firefox... a quick Google indicates there is a difference in the way Chrome and Firefox interpret the CSS 'padding' commands....

**Comment by ben3000** [comment]
Confirmed in Firefox 53.0.2 (Linux, 64bit).

**Comment by ben3000** [comment]
Firefox generates an Assertion Failed error in webcomponents-0.7.22.min.js when Chrome doesn't, which may point to a cause. The component that is apparently affected by the issue is ckeditor, so I'm not sure how the two are related.

**Comment by sbearcsiro** [comment]
@patkyn Max height of 600 seems overly large - the text boxes default to a height of 400, so perhaps makes that that the max height?

**Comment by ChrisPalmer1** [comment]
Hi, went into the profile for Arabidella nasurtium in Firefox, and it worked fine. Was able to place cursor into all the text boxes and scroll bar was present throughout. Tried other profiles (Berberis darwinii, Anemone crassifolia, Eupomatia bennettii) and also worked fine for them.

**Comment by RobinaSanderson** [comment]
Scroll bar worked fine both within an individual attribute and for the page as a whole. Text box maintained size during editing and save and when reopened in edit.
