### ISSUE TITLE
Genus "Acacia" not displaying in Search tab results, but is in Browse tab quick search

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#441]
Steps to recreate:

using https://profiles-dev.ala.org.au/opus/design-test/profile/Acacia

1. on search tab, select search by text
2. enter "Acacia"
3. no results
![image](https://cloud.githubusercontent.com/assets/23368496/22673680/b600e0d6-ed2f-11e6-8de4-7de50472567f.png)

4. on browse tab, enter "acacia" into quick search
5. Acacia is found
![image](https://cloud.githubusercontent.com/assets/23368496/22673662/990f8ffe-ed2f-11e6-8bf3-a20de1852f5a.png)

6. clicking on the link takes you to the taxon page
![image](https://cloud.githubusercontent.com/assets/23368496/22673689/cdc3b1c6-ed2f-11e6-9f87-f255fd6c14ec.png)

**Comment by m-hope** [comment]
I think this was an artifact of the fact that the Acacia is the most common profile used in testing... I have rematched the name for the Acacia profile, and the test search now correctly lists the Acacia profile in the search results.  I have also tested the Import-test collection and it also correctly lists the Acacia profile when a text search for Acacia is performed.
