### ISSUE TITLE
UI - Browse - Display taxon at selected level even if it has no children

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#442]
Include in browse results pane the selected taxon if it has a profile (either populated or stub). 

Eg: currently if you select "Genus" level in the browse pane on the left, you get a list of all the genera that have profiles for child taxa below the heading... But when you select one of these genera, you can only access profiles with ranks below that level (ie: species or below). If you want to access the Acacia genus page, you have to select Family level, then Fabaceae and then select the Acacia profile page...  This issue would now make the profile for Acacia appear as the top item in the browse results for the genus Acacia.

The side effect of this change is that under each browse category (Family, Genus, etc) you should also get taxa listed that have no children but where the profile for that taxon is available.  Ie: Include in the browse pane, taxa that have a profile (either populated profiles or stubs) but without children (currently only taxa with children with a profile are included).

**Comment by ChrisPalmer1** [comment]
High priority

**Comment by RobinaSanderson** [comment]
Needs to refer to master list so that stubs are included in the browse view

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-151
https://upsource.ala.org.au/profiles/review/PRFLS-CR-152

**Comment by RobinaSanderson** [comment]
Checked in both collections with and without a masterlist:
1. Genus with no children taxa are listed in the Genus drop down pane
2. Once a genus is selected it's children profiles appear on the right and the where a profile exists for the genus the Genus name becomes a link to the profile.

Checked also family level and order.

Issue complete.
