### ISSUE TITLE
Editing - can't delete snapshot of map

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#443]
Steps to recreate:
1. Edit a species
2. Create snapshot of map
3. Publish change
4. Edit same species
5. Delete snapshot (including clicking on yes to whether you want to remove the snapshot and just allow the live map feed)
6. Save change
7. publish or shift to public view
8. Snapshot still displays

![image](https://cloud.githubusercontent.com/assets/23368496/22804168/ecec8b84-ef6b-11e6-9480-413524d708e8.png)

**Comment by RobinaSanderson** [comment]
The workaround is to replace the snapshot with a current view rather than delete. Please don't spend more than half a day for the eFlora production release.

**Comment by ChrisPalmer1** [comment]
High priority

**Comment by ben3000** [comment]
@RobinaSanderson how do you create a snapshot of a map?

**Comment by RobinaSanderson** [comment]
Hi @ben3000 You'll need to have the editing permission in a collection. 
- open a profile (it needs to be a matched profile so the map will come in from the ALA)
- select Options
- select Edit
- the editing view will open with the map displayed at the top of the page
- Select Edit map configuration
![image](https://cloud.githubusercontent.com/assets/23368496/25642588/29497062-2fde-11e7-8892-7256c1d5f7d0.png)
- The map editing view will open
- Select Create snapshot image
![image](https://cloud.githubusercontent.com/assets/23368496/25642621/60f63cca-2fde-11e7-8164-f91b2489a85d.png)
- Dialogue will open asking if you want to create a snapshot choose Yes
- You will be returned to the editing page
- Select public view and you will see the snapshot

If you navigate back to editing the map configuration there will be an option to delete snapshot. Select this option and save - it appears to work. However, when you return to the public view you still get the snapshot rather than the "live" view from the ALA of occurrences.

I'll be in meetings today from 11.00 until 2.00 our time, but if you have further questions try to get me via hipchat.

**Comment by ben3000** [comment]
@RobinaSanderson hmm, the "Create snapshot image" button isn't coming up for me, despite following your directions. I'll have to dig a bit further.

**Comment by ben3000** [comment]
Ah, I had to enable map snapshots under the opus' map configuration.

**Comment by ben3000** [comment]
The reason this is failing is that the snapshot image is being saved to disk, but not to the profile, thus when it is later deleted, there is no reference to it available to the code that deletes the image (ImageService.deletePrivateImage).

@sbearcsiro should a map snapshot be saved to the profile like other images, or is this type of image supposed to exist solely outside the profile (model)?

**Comment by RobinaSanderson** [comment]
Sorry @ben3000 - I hadn't even thought of the collection configuration as I've been using the previously set up collection. As an aside, if the snapshot is not stored with the profile, does it get deleted when the profile is deleted?

**Comment by ben3000** [comment]
@RobinaSanderson it looks like the answer is **no**. Only the model is deleted, as far as I can tell.

**Comment by ChrisPalmer1** [comment]
Checked this with Banksia aemula and it looks like it's fixed now (snapshot gone after deleting, and map then displays the live feed. Also worked when tested on Aleurites moluccanus.

**Comment by RobinaSanderson** [comment]
Tested in ALA Test Collection and is working as expected.
