### ISSUE TITLE
UI - Create new home page

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#445]
As a General user 
Need to see a page I can easily identify with a relevant collection
So that I can quickly confirm I am accessing the right collection and can start my work.

Business requirements:

1. Clicking on a collection should take the user to the new collection home page. 
2. There will be a section for explanatory text at the top left of the home page.
3. This section should be populated from a text field allowing markup that the collection administrator can edit in the collections settings page.

Note: Need to check if we need to modify logo or banner. 

Further elements in the new home page are covered in other stories.
see #446 #447 #448

**Comment by RobinaSanderson** [comment]
Hi @m-hope I've written this so that the explanatory text section is editable. I think in the long run that will save us headaches rather than having to make changes on behalf of the Floras. If you want me to, I'll remove that requirement.

**Comment by m-hope** [comment]
I agree, this text should be easily added to the collection settings screen.

**Comment by m-hope** [comment]
General feedback from Hannah based on the original mock-ups is paraphrased as follows:
     - As far as ALA branding goes, we should stick with the "Powered by ALA" approach.
     - Keep the colours fairly neutral, with highlights based on the final logo image
     - Hannah agrees the landing page with a small amount of explanatory text and the navigation buttons is a good approach
     - Whatever we decide for the navigation icons (text or icons or both) it needs to be clear what they are for... note the example from the Atlas of Living Scotland site: https://scotland.nbnatlas.org/
     - It was suggested that instead of down the page, the navigation buttons should be across the page to reduce the need to scroll to access all the buttons (see the Atlas of Living Scotland site above).
     - Accessibility: the ALA is now required to meet CSIRO's accessibility guidelines, Hannah is happy to arrange a meeting with CSIRO's accessibility specialist if required....

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-142
https://upsource.ala.org.au/profiles/review/PRFLS-CR-143

**Comment by RobinaSanderson** [comment]
Initial implementation is complete- the home page is being refined in other stories.
