### ISSUE TITLE
UI - Home page - Navigation for commonly used functions

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#446]
As an eflora user 
I need prominent navigation to common functions
So that I can easily identify where I am and what can I do

Business requirements
1. There will be prominent navigation for:
- Search - leads to the search page
- Browse - leads to the browse page
- Identify - leads to the keys page
- Filter - restricts all responses to a specified list of taxa
- Context - provides additional explanatory information for the eFlora
2. If there is no Keybase project associated with this collection (on the configuration administration page), the Identify icon/button should not display.
3. Hover text will provide additional information about each selection.
4. Hover text should be configurable by the Collection Administrator.

Initial hover text:
Search 
You can search by name to find sub species, species and higher taxa. Alternately, you can search the text of profiles to find profiles with matching keywords.
Browse
You can browse taxonomic classification to see species and their related higher and lower taxa. you can either drill down the classification tree or enter a known taxa in the quick browse and see related taxa.
Identify
You can identify plant based on answering questions about their characteristics (keys). 
Filter
You can enter a list of species and restrict the functions of the eFlora to the species in that list.
Context
You can access explanatory information and reference material relating to the eFlora.

**Comment by m-hope** [comment]
A number of people have commented that having the buttons go across the page might be better than down the page:
     - it puts the buttons front and center on the page as they will be what most users will want to use after the first visit.
     - It reduces the need to scroll down to see all the options

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-142
https://upsource.ala.org.au/profiles/review/PRFLS-CR-143

**Comment by ChrisPalmer1** [comment]
Suggest the following updated hover text:
Search
You can search by name to find sub species, species and higher taxa. Alternately, you can search the text of profiles to find profiles with matching keywords.
Browse
You can browse taxonomic classification to see species and their related higher and lower taxa. you can either drill down the classification tree or enter a known taxa in the quick browse and see related taxa.
Identify
You can identify plant based on answering questions about their characteristics (keys).
Filter
You can enter a list of species and restrict the functions of the eFlora to the species in that list.
Context
You can access explanatory information and reference material relating to the eFlora.

**Comment by RobinaSanderson** [comment]
Hi @ChrisPalmer1 - an admin to the Flora of Australia will be able to change the hover text as you need. The context page was originally to provide a space for uploading the Flora of Australia introductory material and appendicies. It was also suggested some information could be provided or linked to about taxonomy in general. However, the content is completely up to you.
