### ISSUE TITLE
UI - Home page - Updates section

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#447]
Minimum requirement is a section on the Configuration Admin page that can be edited and includes basic mark up for formatting. This would display on the home page in the Updates section.

No versions being kept.

Other option might be to link to a blog via plug in?

**Comment by ChrisPalmer1** [comment]
Updates section High priority for the launch. Blog functionality for a later time.

**Comment by m-hope** [comment]
Peggy advises that ZoaTrack uses the WordPress blog and was very easy to implement.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-142
https://upsource.ala.org.au/profiles/review/PRFLS-CR-143

**Comment by RobinaSanderson** [comment]
Issue complete.
