### ISSUE TITLE
UI - Home page - Image slider

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#448]
Probably need to do some research to find best plug in/option.

Needs to enable multiple images. Administrator needs to be able to configure which images are used (either upload the images on the administration configuration page or link to image urls from same page).

Don't spend more than 1 day to research and implement.

Screen mockups: https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release

**Comment by sbearcsiro** [comment]
Bootstrap, the UI library the underpins the site provides a built in image carousel.  There is an out of the box solution that theoretically we can pick up from existing libraries used in the project that would work like this:

http://angular-ui.github.io/bootstrap/versioned-docs/0.12.0/#/carousel

**Comment by ChrisPalmer1** [comment]
High priority for first sprint. Image carousel example in link above looks good.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-142
https://upsource.ala.org.au/profiles/review/PRFLS-CR-143

**Comment by RobinaSanderson** [comment]
Initial implementation is complete. home page is being refined in other stories.
