### ISSUE TITLE
UI - Menu bar in header

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#449]
Once individual pages (search, browse etc.) are created, this story should include creating the website structure. And things like the menu bar in the header across pages, will it be consistent across all pages or will some pages need different options?

Need to consider help pages as well as function pages.

If the collection does not have a keybase project associated with it (on the configuration administration tab), the Identify option should not be visible in the header.

**Comment by temi** [comment]
As discussed in today's standup - "Need to consider help pages as well as function pages." will be added as a separate ticket once requirements are clearer.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-142
https://upsource.ala.org.au/profiles/review/PRFLS-CR-143

**Comment by RobinaSanderson** [comment]
Issue complete.
