### ISSUE TITLE
UI - Footer - Include ISSN and license information for collection

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#450]
As the collection administrator
I want to enter the text for the ISSN and the text and links for the licence statement and have them appear in the footer
So that users can look up the licence conditions and reference the ISSN.

Business Requirements
1. On the collection administration page, provide a field for the licence statement. It needs to be 100 characters long and needs to be able to accept links
2. Values entered into this field should display in the footer.
3. On the collection administration page, provide a field for the ISSN. It needs to be 30 characters long. and should accept numbers and huyphens.
4. Values entered into this field should display in the footer.

https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release

**Comment by RobinaSanderson** [comment]
From Russell Barrett:
I think that is about right. Looking at other similar sites, I think we will want to say something like “All material CC-BY unless otherwise stated” – with links to the full licence statement on the about page and to the CC-BY page.

**Comment by RobinaSanderson** [comment]
Hi @temi, @m-hope and @ChrisPalmer1 - I discussed the licence statements with Russell. he has suggested that ABRS will want a licence statement on the inside front cover of the .PDFs that is in addition to the footer statement, but shorter than the full statement to be held on the about page, or as part of the wordpress help.
I think we would need to have a configurable field for the collection called "PDF Licence statement". This would be in the branding section of the collection configuration page. The collection administrator could enter text up to 500 characters using all punctuation. This text would appear on the inside front cover of the .pdf when generated.
Temi, could you give a rough idea whether this can be done in the estimate for the story or how much longer it will take.

**Comment by temi** [comment]
@RobinaSanderson the estimate is between 0.5 and 1.

**Comment by RobinaSanderson** [comment]
@Thanks. After talking to Michael will go ahead with this.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-148
https://upsource.ala.org.au/profiles/review/PRFLS-CR-149

**Comment by RobinaSanderson** [comment]
Tested in dev environment, ALA Test collection. License statement field and ISSN field is available for entry in configuration and displays in footer.
Issue complete.
