### ISSUE TITLE
UI - Search page

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#451]
As a taxonomist
I want a consistent interface with standard headings
So that I can quickly identify functions and navigate between them.

- Make the "Search for profile(s)" heading formatting consistent with the Browse and Identify pages.
- In the search box where the user selects which type of search (name or text) change:
-- "with text" to "containing text"
-- "with name" to “by name” 
- Remove tabs

Screen mockup: https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release

**Comment by m-hope** [comment]
Estimate has been changed as this task is now about rewording the text on the currently existing page.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-158

**Comment by ChrisPalmer1** [comment]
Search page formatting as outlined at the top looks to be fixed up. Suggest refining the text that the user sees when hovering over the Search button as follows: 'You can search by name to find species, subspecies [one word] and higher taxa. Alternatively, you can find profiles by keyword search.'

**Comment by RobinaSanderson** [comment]
Hi @ChrisPalmer1 - I'm looking at the ALA test collection in the dev environment. There is no mouseover text over the search button on the search page. There is the ability to configure mouseover text on the search button on the *homepage*. I'm wondering if instead of trying to put a useful explanation in mouseover text on the search page we would be better to link to the wordpress help site?
