### ISSUE TITLE
UI - Browse page

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#452]
As a taxonomist
I want a consistent interface with standard headings
So that I can quickly identify functions and navigate between them.

- Make the "Browse by category" heading formatting consistent with the Search and Identify pages.
- Remove tabs
- Move quick search to underneath the browse by categories area
- Rename the "Quick search" to "Quick browse" (note: this task was originally covered in #472 which is now closed as a duplicate).
- Change the text to read:

    |   Browse using the navigation pane to the left. You can jump to a particular taxon by typing the start of the Taxon name into the quick browse option at the bottom of the pane.

- Include the selected taxon in the browse results when a profile page exists for the taxon.
(note: this issue is covered by #442 which deals with both including the selected taxon in the results and changing the browse display to include profiled taxa in the display whether or not their children have profiles)

**Comment by m-hope** [comment]
Also need to confirm what is displayed under each browse heading... eg: currently if you select "Genus" level you get a list of all the genera below the heading, but when you select a genus, you can only access profiles with ranks below that level (ie: species or below).  If you want to access the Acacia genus page, you have to select Family level, then Fabaceae and then select the Acacia profile page...

**Comment by ChrisPalmer1** [comment]
Maybe 'quick browse' can be re-named..?

**Comment by m-hope** [comment]
need to consider adding a 'Species' level as a Browse catagory... if takes too long just complete word changes

**Comment by m-hope** [comment]
Estimate changed to only consider changing wording on existing page.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-157

**Comment by ChrisPalmer1** [comment]
Browse by category page now appears to be consistent with the others. 
Suggest refining the text on the browse page with the following 3 paras: 'Browse the taxonomic hierarchy using the navigation pane to the left. You can also jump to a particular taxon in the hierarchy by typing the beginning of the name into the 'Quick browse' option at the bottom of the pane. 

Alternatively, you can select the 'Search' navigator at the top of this page and perform a text or name-based search. 

The 'Identify' button on the homepage will help you select the appropriate profile using dichotomous keys.

**Comment by RobinaSanderson** [comment]
Hi @ChrisPalmer1 I would like to close this issue and create a separate one for the text change as the story has been completed as it was specified. This means the text change is unlikely to get into the work that can be done this week. Please give me a call if you'd like to discuss further.
