### ISSUE TITLE
UI - Identify page

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#457]
1. Provide heading to the page consistent with the Search and Browse pages.

> Identify via keys

2. Add the following text as a hover prompt under a ? symbol:
    
> Select  key attributes (keys) of the plant you wish to identify. Matching taxa will be displayed on the right. The path you have chosen will be displayed underneath as links back to those steps.

3. Remove tab navigation. 
4. Change unlinked text e.g. "Flora of New South Wales: Tracheophyta" text colour to black 
5. This page will not exist for collections without associated keybase project.

Screen mockup: https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release

**Comment by ChrisPalmer1** [comment]
High priority

**Comment by RobinaSanderson** [comment]
do in conjunction with #219

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-137

**Comment by temi** [comment]
@RobinaSanderson The help text says "Select key attributes (keys) of the plant you with to identify.". Should it be "Select key attributes (keys) of the plant you wish to identify. " i.e. wish instead of with?

**Comment by ChrisPalmer1** [comment]
yep, definitely a typo; should be '.....you wish to identify'. 

Don't think the text as written above ('Select key attributes (keys) of the plant you wish to identify. Matching taxa will be displayed on the right. The path you have chosen will be displayed underneath as links back to those steps.') has been added. identify button on homepage currently has 'You can identify plant [sic] based on answering questions about their characteristics (keys). This probably needs further refinement. How about 'You can identify plants using keys based on their characteristics'.

**Comment by RobinaSanderson** [comment]
Hi @temi - Just noticed a couple things in the ALA Test collection:
* The heading weight is different between this page and the search page. 
* The text has not been added. Please use the text provided by Chris: You can identify plants using keys based on their characteristics.

Tested that the identify button is not visible on the homepage when there is no keybase project associated with the collection - this is working.

**Comment by ChrisPalmer1** [comment]
If possible please revise to: Identify plants based on their characteristics using keys
I think this reads a bit better. Thanks (don’t think we need ‘you can…’ in any of that hover text; good to keep as succinct as possible)

**Comment by temi** [comment]
@ChrisPalmer1 & @RobinaSanderson , the identify button's help text can be changed on the collection's edit configuration. I have changed it for FOA in dev.

Heading weight has been changed.

**Comment by RobinaSanderson** [comment]
Hi @ChrisPalmer1 - @temi  has added the help text to the Identify button on the homepage (using the configuration option) rather than to an in line help icon on the Identify page. This would keep this page consistent with the Search and Filter pages. Let me know if this is sufficient. Otherwise, we could add this text to the page, but probably not with in line help icon.

**Comment by temi** [comment]
@RobinaSanderson & @ChrisPalmer1 - I had also added the "question mark" help icon but it is visible after keybase player loads. However, I changed this feature and made it visible on page view.  It will be available on dev soon.
![image](https://user-images.githubusercontent.com/1152259/27362395-8d656fec-5671-11e7-9f94-851ba3824176.png)

**Comment by RobinaSanderson** [comment]
Complete.
