### ISSUE TITLE
UI - Taxon page - header and footer (visible regardless of which tab is selected)

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#458]
Changes:

- Remove the nomenclature concept from header (currently displayed underneath the Common names), this will be displayed on the nomenclature tab. 
- In footer, make the punctuation consistent by using "...(s)" to provide a plural option. (Note: need to determine punctuation when concatenating Author fields)
- Use the current font and text size.
- Change the "Last updated:" to include the name of the person logged in that made the edits. Do not include the publication action when calculating the "Last updated:" date and user.

remove profile  (stuff not in header or footer) aspects to separate issue
Screen mockups: https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release

**Comment by ChrisPalmer1** [comment]
High priority

**Comment by RobinaSanderson** [comment]
Hi @ChrisPalmer1  - Regarding the suggestion for users to see the "Options" button as "Downloads", this would mean the view supplied will change for whether the logged in user only has the user the role or not. Editors and above will still need to see "Options" as the editing actions are held in the same menu. This will add time and complexity to renaming the drop down menu.

**Comment by ChrisPalmer1** [comment]
Ah I see. I wasn’t sure whether you could have just ‘Download’ for users, and ‘Options’ for editors, which would be clearer for each......

**Comment by RobinaSanderson** [comment]
Hi @ChrisPalmer1 
Just checking what you are expecting in the Last updated: information. 
Currently, we store:
- the person who last saved an edit on the profile as the last updater, but we don't store the person who published the profile
- we store as the last update date either the last time the profile was saved or the last time it was published whichever was most recent.
Last time we spoke, I think you said that you would prefer to see in the Last updated information:
- the name of the person who last edited the profile
- the date of the last profile edit 
In effect, ignoring the name and person who published the profile.

Let me know if this is the correct.

I think we will still need to store the publication date, if only for reporting?

**Comment by ChrisPalmer1** [comment]
Hi Robina, also had a chat with Russell about this. We both think that the person and date published for each profile is more of an administrative step and probably doesn't need to be captured at the profile level. In effect, the person updating the profile is likely to be the publisher anyway, and won't publish until they've finished the update. Maybe date published would be good recorded/stored (but not displayed) for internal reporting....hope this answers the question.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-136

**Comment by ChrisPalmer1** [comment]
Header and footer consistently visible with all tabs in all taxon profiles tested. Both contain the elements described at the top of this issue.

**Comment by RobinaSanderson** [comment]
Issue complete.
