### ISSUE TITLE
UI - Identify page - Add link or button to open Glossary in separate browser tab

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#460]
As a taxonomist 
I want to easily reference information in the Glossary
So i can understand the differences provided in the keys.

https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release?preview=/382665949/388931818/eflora%20-%20identify%2001.png

Note: this issue is dependent on the bug in issue: #468 being fixed.

**Comment by ChrisPalmer1** [comment]
High priority

**Comment by RobinaSanderson** [comment]
No longer required.
