### ISSUE TITLE
UI - Identify page - view taxa below Family

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#461]
Currently in Flora of Australia Dev, the keys seem to only take the user as far as family, e.g.
![image](https://cloud.githubusercontent.com/assets/23368496/23193423/0d93ab98-f8fd-11e6-9160-c486d7baeb9b.png)

Is this as far as it goes? Keybase appears to go down to species.

If so we made need the link provided to resolve to the Browse page at that Taxa as we don't have profile pages for most of the family.

**Comment by m-hope** [comment]
I think this is to do with the keybase project chosen... you will see in the image that FoA dev uses the Flora of South Australia project...

**Comment by KevinThiele** [comment]
Michael is correct - the Flora of South Australia project seems to have a families key only. Look at the FoA in prod and the keys behave as expected
