### ISSUE TITLE
Profile - Distribution tab - unable to get distribution where supplied name isn't matched name

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#462]
Steps to recreate:
1. select create profile 
2. match to valid name
3. Enter a different name then the matched name for the profile
4. Profile is created but distribution isn't given

When the profile is created, the service uses the entered name rather than the matched name to get the distribution, and can't find it by the entered name.

It needs to pass through the matched name instead.

**Comment by RobinaSanderson** [comment]
Need to know if this has to be done before the import so that the profiles entered with old names can be updated.

**Comment by ben3000** [comment]
@RobinaSanderson Why would you want the distribution from the matched name to be used? Is it expected that there would be a close relationship between the matched name and the entered name?

**Comment by RobinaSanderson** [comment]
Hi @ben3000 - The profile name will refer to the same concept as the matched name, hence wanting the same distribution. The profile name will be different to the matched name in the eFlora of Australia if the it is updated in the eFlora but not yet updated in APNI or if the collection is for another jurisdiction (e.g. SA, QLD or WA) that recognises a different name. Basically, by matching the name the editor is saying the concept for profile is that of the matched name, therefore the matched name distribution should be used for that profile. Give me a call if I am as clear as mud, and i'll try to explain better. :-)

**Comment by patkyn** [comment]
Can't replicate this issue. I can still see the distribution for internally matched profile.

**Comment by patkyn** [comment]
There seems to be a problem if I rematch the matched profile to another name via Edit Profile -> Edit Name -> Match to name. The distribution is still reflecting the previous profile distribution.

**Comment by patkyn** [comment]
This is already fixed as part of #522

**Comment by RobinaSanderson** [comment]
Tested in ALA Test by:
* Entered new profile name: Arabidella newnamia
* Matched to: Arabidella trisecta
* Created new profile and published
* Checked distribution map against Arabidella trisecta in Flora of Australia - maps matched

Issue resolved.
