### ISSUE TITLE
Glossary - can't access glossary

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#468]
Clicking on the Glossary link produces the following error:

![image](https://cloud.githubusercontent.com/assets/23368496/23531800/62f571b0-fffc-11e6-896e-da521ce360d4.png)

Regardless of the role of the person logged in.

Something to do with the glossary opening on a new tab and the new tab doesn't inherit the log in details of the user.

**Comment by m-hope** [comment]
@ben3000 if I go to any collection on profiles-dev and at the home page, click on the 'Glossary' menu item (I have just used https://profiles-dev.ala.org.au/opus/5124793e-7c63-46f4-9ac9-fb8e1b0e63ca), it will open a new tab in my browser that (once loaded) displays the error "You do not have the necessary permissions to perform this action."  as per the image below.

![image](https://cloud.githubusercontent.com/assets/8856025/26089474/7788fc3a-3a41-11e7-91d5-264a46a1958a.png)

In thinking about this... I wonder if this is an auth issue or simply that there isn't a glossary file available and it gives an inappropriate error...

**Comment by ben3000** [comment]
It is interesting that it loads the page, displaying the expected glossary layout, but then fails and displays the "You do not have the necessary permissions" error.

**Comment by ben3000** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-169

**Comment by ben3000** [comment]
A probable issue in AccessControlFilters may be the root cause of this issue.

**Comment by RobinaSanderson** [comment]
Not sure if this a problem with this issue or with #490 but I can't upload a csv file for updating the glossary.
This will need to be solved before production release.

**Comment by ben3000** [comment]
The underlying cause of this issue appears to be (at least in my dev environment) a permissions problem (403 error) on profile-service/opus/$opusId/glossary/a.

**Comment by m-hope** [comment]
It appears that anonymous users (ie: not logged in) are able to edit and delete glossary items... needs to be fixed asap.

**Comment by m-hope** [comment]
Further investigation shows that while the buttons are visible, the anonymous user is not able to save any changes (comes back with a general error message).

**Comment by m-hope** [comment]
Testing confirms that glossary files can now be loaded to both public and private collections, however two issues remain and will be documented as separate issues:
 - #593 - Glossary edit buttons are visible to all users
 - #??? - uploading a badly configured glossary file will cause a recurring error

With these two separate issues documented, this issue can be closed once reviewed.
