### ISSUE TITLE
UI - Footer - Allow multiple logos with links

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#469]
As a collection administrator
I need to include multiple logos in the eFlora footer
So that the eFlora can be branded with contributing logos.

Business Requirements
1. On the collection administration page, allow the administrator to enter multiple logo images
2. On the collection administration page, allow the administrator to enter a linked URL for each image
3. Display images in the eFlora footer
4. When a logo is entered and has a linked URL, clicking on the URL will open the linked page in a new tab.

**Comment by ChrisPalmer1** [comment]
High priority

**Comment by RobinaSanderson** [comment]
Need to be able to resize footer space depending on number of logos added.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-138
https://upsource.ala.org.au/profiles/review/PRFLS-CR-139

**Comment by ChrisPalmer1** [comment]
Aust Government and ABRS logos added to homepage footer (though without linked URLs).

**Comment by temi** [comment]
@sbearcsiro why in code review?

**Comment by sbearcsiro** [comment]
Because the code review is not complete.

**Comment by RobinaSanderson** [comment]
Complete.
