### ISSUE TITLE
State-level censuses (names) have some differences from national-level (APC) accepted names. Applies to a few % of names in each jurisdiction. State-level censuses will need to be supported.

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#47]
http://www.bugherd.com/projects/58735/tasks/33

**Comment by ala-bugherd** [comment]
for further discussion

**Comment by ala-bugherd** [comment]
Has this requirement been met by the new name matching rules? (https://github.com/AtlasOfLivingAustralia/profile-hub#name-matching)

**Comment by m-hope** [comment]
States could also potentially have different hierarchies (trees)... 

Need to investigate ability to use a custom tree for each collection...  then need to 
be able to import (from NSL) a specific tree for each collection.

Have been advised this is a fundamental requirement for the creation of State Flora.

**Comment by m-r-c** [comment]
This will be solved by #345 and #258
