### ISSUE TITLE
UI - Home page - Edit configuration  button should only appear on home page

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#474]
Remove "Edit configuration" from Administrator view on any page except the home page.

**Comment by temi** [comment]
The edit configuration only appears on collection home page. No change is required.

**Comment by ChrisPalmer1** [comment]
Yes, appears to be present only on homepage in production site. Not present once user goes into profile pages.

**Comment by RobinaSanderson** [comment]
The configuration options will now appear in the header menu under the "hamburger" icon for a logged in user. To see this option:
* Log in
* the login option will change to a menu (hamburger) icon
* click on menu
* the Edit configuration option will be available.

Issue resolved.
