### ISSUE TITLE
UI - home page and taxon profile page - "Add new profile" button should be available in both places 

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#475]
For administrators, super editors and editors, the "Add new profile" button should be available on the home page and on any taxon profile page. It should not appear on other pages.

**Comment by RobinaSanderson** [comment]
This issue will be superseded if the master list functionality - #480 - is successful as new profiles will be created by adding a new name in the masterlist rather than adding via the Add new profile button.

**Comment by m-hope** [comment]
This issue is also superseded by #524 ... as the 'Add New Profile' button will be 'moved' into the User Settings menu on the universal header bar (ie: it will be available from any page for those with the appropriate permissions).

**Comment by RobinaSanderson** [comment]
Not required as now in the header menu.
