### ISSUE TITLE
Profile - Status of profile

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#477]
As an editor or user of the eFlora
I need to know the status of each profile
So that I can identify which ones require further work

Minimum: 
System field with picklist, editor can change value for profile from picklist

Preferable:
picklist values determined at collection level by administrator

1. By preference this should be a custom attribute available as a picklist configurable by the administrator.
2. If it is not possible for the administrator to define the picklist values, it should be system attribute with the following picklist:

- Empty
- Partial
- Legacy
- Complete
- In review

3. The attribute will appear on each profile 
4. The attribute can be edited by administrators, supereditors and editors.
5. The default profile status for stubs should be "Empty"
6. The default profile status for an edited profile should be "Partial" 
7. The editor can overwrite the default and save to change the status.
8. The set value with save if the individual attribute is saved or if it is set and the user chooses "Save All"

**Comment by RobinaSanderson** [comment]
On import:
- a record with no attributes will have status set to Empty
- a record with any attributes will have status set to Legacy
Manually created profiles:
- with no attributes will have status set to Empty
- if any attributes are entered but nothing has been selected by the editor, status will be set to "Partial"
- otherwise, status will reflect the value given by the editor
Manually updated profiles:
- if any attributes are entered but nothing has been selected by the editor, status will be set to "Partial"
- otherwise, status will reflect the value given by the editor

**Comment by RobinaSanderson** [comment]
Need a option in search to select what status to display in results. Could be "Do not display empty profiles" but not sure if all other statuses are equally useful.

Include above logic in import

Would be good to be able to report on taxa by status.

**Comment by ChrisPalmer1** [comment]
High priority for reviewing what's possible. Reporting on outcome would be important for FoA Advisory Group

**Comment by RobinaSanderson** [comment]
Hi @ChrisPalmer1: 
Could you please check the values and let me know if you need any changes?

**Comment by ChrisPalmer1** [comment]
The values for importing, manually creating and updating profiles look good to me. Just to clarify, the 'legacy' label for partially completed profiles is just to let the system know to expect some attributes to be present on import, but with the understanding that these will be ignored and overwritten, because profiles are only imported as complete entities...? Thanks, Chris

**Comment by RobinaSanderson** [comment]
Hi Chris, no, I had understood that the "Legacy" designation was for all imported profiles.

As these were manually reviewed and updated an editor would change their status to "Partial", "Under review", or "Complete" as required.

I am assuming that the "Legacy" status will be in use for a very long time as it will take a very long time for all imported profiles to be reviewed.

Let me know if this is not what is required.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-133

**Comment by m-hope** [comment]
Could we please add some comment text under the Additional Statuses section of the 'Edit Collection' settings page to say something like:

Note: the "Legacy" and "Partial" statuses are defined by the system and can not be removed or modified.

**Comment by ChrisPalmer1** [comment]
Many species checked, and profile status present for each (always partial).

**Comment by RobinaSanderson** [comment]
Tested using masterlist test collection:
* imported profile "Anthrocarapa nitidula" has status of "Legacy"
* edited imported profile "Azadirachta indica" so that status was partial, was able to save this and have the status display change in public view of the profile
* checked profile added as aname in the masterlist - stub had status of "Empty" - was able to update to status of "partial"
