### ISSUE TITLE
UI - Taxon page - Citation statement in footer

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#478]
As an eFlora user
I need to know how to cite eFlora pages 
So that I can provide correct acknowledgement

Business requirements:
1. Each taxon page should generate a citation statement specific to that page
2. The citation statement should be automatically generated in the following format:

> Cite this profile as: ‘Profile Author(s)’ (‘YEAR’) ‘Profile Name’. In: ‘Profile Editor’. (ed.) eFlora of Australia. Australian Biological Resources Study, Department of Environment and Energy, Canberra. ‘Profile URL’ [Date Accessed: ‘dd Month yyyy’] 

Where:

- Profile Authors should be taken from the values entered in "Type of contribution = Author", "Type of contribution = Author/s". Where mutiple fields are used on a profile, combine authors in the citation statement in the order they have been entered in the profile, separated by commas.
- YEAR is the year the profile was published
- Profile Editor should be taken from the values entered in "Type of contribution = Editor/s"
- Profile URL is the URL for this profile

Note: need story to remove Author option and just use Author/s field.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-153
https://upsource.ala.org.au/profiles/review/PRFLS-CR-154

**Comment by RobinaSanderson** [comment]
Checked in profiles dev environment, Flora of Australia collection. Citation present at bottom of the profiles page.
Profile: https://profiles-dev.ala.org.au/opus/foa/profile/Acacia%20hystrix
Citation:
Cite this profile as: B.R.Maslin, Minor edits by B.R.Maslin & J.Rogers (2016) Acacia hystrix. In: (ed.) eFlora of Australia. Australian Biological Resources Study, Department of Environment and Energy, Canberra. https://profiles-dev.ala.org.au/opus/foa/profile/Acacia+hystrix [Date Accessed: 08 June 2017]

Hi @ChrisPalmer1 - I'm not sure that the (ed.) is required unless there is an editor for the profile as well as an author, could you please check?

**Comment by ChrisPalmer1** [comment]
Yes, you're right Robina; the ed. isn't required; and also the citation should just come in as the author. Citing minor edits shouldn't be necessary. If there are major edits then it could be cited as such or better as a combined authorship. Therefore, for the above example, probably should be cited as B.R.Maslin (2016) Acacia hystrix. In: Flora of Australia. Australian Biological Resources Study, Department of Environment and Energy, Canberra. https://profiles-dev.ala.org.au/opus/foa/profile/Acacia+hystrix [Date Accessed: 08 June 2017]. (By the way, will be just Flora of Australia rather than eFlora of Australia. eFlora is just an informal term).

**Comment by RobinaSanderson** [comment]
Hi @temi - My apologies I didn't pickup the (ed.) until this was done.

Do you want me to raise a separate issue (as you developed this one as per the original requirements)? Or are you happy for me to put this one back into to do?

**Comment by temi** [comment]
@RobinaSanderson @ChrisPalmer1 please test the changes on dev system

**Comment by ChrisPalmer1** [comment]
Almost there. Note that the full dept name is ‘Department of the Environment and Energy’. Sounds trivial I know, but thems the facts.

**Comment by RobinaSanderson** [comment]
Checked citation statement in profiles-dev > Flora of Australia collection. 
1. (ed.)  has been removed
2. "Department of the Environment and Energy" appears in the statement and is part of the administrator configuration.
