### ISSUE TITLE
UI - search and browse pages - provide option to hide incomplete profiles in results

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#483]
Allows the user to check a box or toggle an option to hide profiles with the following status:
- empty

Michael [5/5/17]: have removed 'partial' profiles from this functionality... now option is there to remove stub profiles from the displayed results of search and browse.

**Comment by ChrisPalmer1** [comment]
park issue until discussion on partial profiles/stubs by FoA Advisory Group

**Comment by RobinaSanderson** [comment]
Estimate is for implementing as a search option before search is performed. Not a persistent user setting that would be remembered across sessions.

**Comment by m-hope** [comment]
#481 is a prerequisite for this issue.

**Comment by RobinaSanderson** [comment]
This issue is no superseded by #530
