### ISSUE TITLE
UI - Taxon page - Remove option to export as JSON

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#485]
Currently a user can export a profile as either .pdf or JSON. Remove option to export as JSON as this was used for system testing.

**Comment by ChrisPalmer1** [comment]
High priority

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-140

**Comment by ChrisPalmer1** [comment]
This looks like it's fixed in Chrome and Firefox. Tested many taxa at multiple ranks (species, genera, families, orders), and in all cases the JSON export option was absent.

**Comment by RobinaSanderson** [comment]
Tested in ALA Test collection. No option to export a profile as JSON.

Issue resolved.
