### ISSUE TITLE
UI - Remove scaling of the banner image at the top of all pages

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#486]
Not sure where to put this, but the current functionality of the banner at the top of each page is to scale as the browser window is resized... depending on the size of the banner image this can lead to some ugly versions of the banner:  EG:

![image](https://cloud.githubusercontent.com/assets/8856025/23926304/92181dfc-0967-11e7-8544-4f46dc85087e.png)

As part of the revamp of the UI for eFlora, the banner needs to be handled properly so the ugly black lines don't appear.

**Comment by ChrisPalmer1** [comment]
To be addressed with web design of site

**Comment by RobinaSanderson** [comment]
Not sure if the solution to this is to fix the scaling for this banner so that the lines don't appear, or chose a banner that scales better e.g. the banner for the dev site Flora of Australia (this banner seems to scale fine).

**Comment by RobinaSanderson** [comment]
Could turn scaling off and define the size of the banner or allow the admin to specify background colour.

**Comment by m-hope** [comment]
Confirm this is still a problem for profile pages and will need to be fixed for the new UI implementation (see: https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release#UserInterfaceforProductionRelease-Mockup-12) as they will continue to use the small profile page banner.

As the current mockup banner image uses text, it is recommended that the vertical height of the banner is maintained so the text doesn't distort... this will mean that as the browser window gets smaller, the image will be cropped on the right hand side.

**Comment by RobinaSanderson** [comment]
Wait for graphic design input.

**Comment by ben3000** [comment]
@m-hope Seeking confirmation that this issue is now about creating a smaller banner for the profile pages in the same style as @sbearcsiro created for the collection front page.

**Comment by m-hope** [comment]
@ben3000 from the draft mock-up that came through, I suspect they'll want the small banner on non-homepages to be full width (especially now that Simon has allowed that for the hompage)... I don't think we need to have the ability for the banner to be created from the homepage image, just use the current functionality which lets the collection admin upload profile page banners and use that banner for any page other than the homepage, but we do need to fix the 'scaling' so that the banner doesn't produce the black lines top and bottom if the browser window is too wide...  If making sure that the uploaded profile banner image is over x numbers of pixels fixes this problem then that is a simple solution.

**Comment by ben3000** [comment]
@m-hope, @RobinaSanderson it looks as if the left-hand logo image is to be used alongside each banner, is this correct?

**Comment by temi** [comment]
@ben3000 / @sbearcsiro - can you create an code review item in Upsource for this?

**Comment by ben3000** [comment]
Yep: https://upsource.ala.org.au/profiles/review/PRFLS-CR-180

**Comment by javier-molina** [comment]
Images don't leave any black bars anymore and the gradient look awesome
