### ISSUE TITLE
UI - Taxon page - remove "Contributed by..." auto text in profile sections

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#487]
The auto text "Contributed by <name of logged in user>" for the individual sections on the taxon page needs to be removed. However, any text entered in the source for the sections needs to remain as is. 

This is because the person editing the Flora may simply be doing data entry, rather than being the contributor of the intellectual content.

**Comment by ben3000** [comment]
@RobinaSanderson Do you have an example from the profiles dev instance that I can see?

**Comment by ben3000** [comment]
@m-hope, @RobinaSanderson so I'm proposing to remove the "Contributed by " prefix text from the front of the list of creators of a profile's attribute in two places: the web profile and the PDF document. These only appear if "Show contributors and editors for attributes" of the Authorship and attribution controls is enabled.

Is that the correct response to this issue?

**Comment by RobinaSanderson** [comment]
Hi @ben3000  - Sorry, I didn't see this configuration setting before you pointed it out. We want to get rid of the contribution statement appearing in the attribute altogether (both on the profile page and the .pdf), this information is provided separately in the acknowledgements for the profile. If unticking this option means we can get rid of the "Contributed by XXXX" appearing in each attribute that is all we need. However, when I tried to untick this option in ALA Test Collection I got an error, perhaps because it had already been used? I will be at the Symposium for most of today, but should have a chance to look at comments first thing tomorrow.

**Comment by ben3000** [comment]
@RobinaSanderson OK, so it is definitely the case that if a project disables "Show contributors and editors for attributes" in the opus configuration then nothing is output below individual attributes.

If this functionality is suitable, perhaps you can screenshot and/or copy-paste any error messages you get when attempting to disable the above configuration so I can try to correct that?

**Comment by RobinaSanderson** [comment]
Righto. Will take screenshot 1st thing tomorrow.

**Comment by ben3000** [comment]
@RobinaSanderson enable Chrome's developer tools and note any error messages that get logged on the Console tab when you attempt to do disable the config option.

**Comment by RobinaSanderson** [comment]
![image](https://cloud.githubusercontent.com/assets/23368496/26226500/d9d28692-3c6f-11e7-82d3-541e83d81ba4.png)

Hi @ben3000 thanks for the link. Let me know if this is OK.

**Comment by ben3000** [comment]
Yep, that's the stuff. Now, take a copy of the POST and the "Failed to invoke URL" items, and hopefully that will copy the entire error trace including what is being currently hidden. (You can show the rest by clicking on the little grey triangle.)

**Comment by RobinaSanderson** [comment]
application.unminified.js:12751 Failed to invoke URL /opus/bfb23cb2-0459-4223-b943-225331016411/update: Response code 500
(anonymous) @ application.unminified.js:12751
(anonymous) @ application.unminified.js:46525
(anonymous) @ application.unminified.js:12729
(anonymous) @ application.unminified.js:12761
$eval @ application.unminified.js:12774
$digest @ application.unminified.js:12771
$apply @ application.unminified.js:12775
g @ application.unminified.js:12730
C @ application.unminified.js:12734
F.onload @ application.unminified.js:12735
application.unminified.js:12751 AlertController is now deprecated. Use UibAlertController instead.
(anonymous) @ application.unminified.js:12751
(anonymous) @ application.unminified.js:13069
g @ application.unminified.js:12685
p.instance @ application.unminified.js:12724
(anonymous) @ application.unminified.js:12707
d @ application.unminified.js:12656
F @ application.unminified.js:12707
(anonymous) @ application.unminified.js:12715
p @ application.unminified.js:12700
(anonymous) @ application.unminified.js:12699
(anonymous) @ application.unminified.js:12701
h @ application.unminified.js:12705
(anonymous) @ application.unminified.js:12882
(anonymous) @ application.unminified.js:12771
$digest @ application.unminified.js:12772
$apply @ application.unminified.js:12775
g @ application.unminified.js:12730
C @ application.unminified.js:12734
F.onload @ application.unminified.js:12735

**Comment by RobinaSanderson** [comment]
this is what it looked like in the console:
![image](https://cloud.githubusercontent.com/assets/23368496/26229455/2d5b0d92-3c85-11e7-9ec1-847fea64b7ae.png)
When I copied and pasted into the above comment, it seemed to lose some of the information.
Am I doing something wrong?

**Comment by ben3000** [comment]
@RobinaSanderson no, that's fine, it has just lost the formatting. Either way it is clear we're not going to get this issue fixed without being able to replicate it on a developer's machine, as we need to be able to see where the failure occurs in a controller or service.

**Comment by RobinaSanderson** [comment]
Righto - Thanks for your patience.

**Comment by sbearcsiro** [comment]
@RobinaSanderson @ben3000 the issue was that the ALA Test collection still had references to some deleted collections via the 'sharing data with' attribute*.  I've removed the entries from the collection manually and I can now successfully change the 'Show contributors and editors for attributes.' checkbox.

* - We should test whether there is a bug here, when a collection that is being shared to is deleted then the sharing data with reference should be removed.  It looks like there is code in place to do this already but maybe there is an issue for whatever reason

**Comment by RobinaSanderson** [comment]
Hi @ben3000  and @sbearcsiro 
I've done a little more testing with the Collection "Masterlist test" and think I have found a bug.

Steps to recreate:
1. opened collection configuration, selected Authorship and attribution controls and unchecked the "Show contributors and editors for attributes"  checkbox.
2. navigated to a profile and added a new attribute "Phenology", saved my change
3. In the Public view, the contributed by ... text is still visible
![image](https://cloud.githubusercontent.com/assets/23368496/26336511/411cde26-3fb6-11e7-8d09-dbbd1691df74.png)
4. on reopening the configuration for the collection, the "Show contributors and editors for attributes"  checkbox is once again checked.
Interestingly, when I updated an existing attribute, rather than adding a new one, the "Contributed by - XXX" text didn't get added (I didn't check the configuration for the collection to see if it had reset before adding the new attribute).

**Comment by RobinaSanderson** [comment]
Checked this in ALA Test collection - looks good. :-)

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-170

**Comment by RobinaSanderson** [comment]
Tested in dev environment, ALA Test collection.

Set the configuration to not "Show contributors and editors for attributes." Checked profile and contributors for attributes were not displayed. Checked pdf and contributors for attributes were not displayed.
