### ISSUE TITLE
User roles - rename super editor and editor roles

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#488]
As an eFlora user
I want the role names to intuitively reflect the roles
So it clear what I can do

Business Requirements:
1. Rename the Editor role to Author
2. Rename the Super Editor role to Editor

Resulting list of user roles:
- Administrator
- Editor
- Author
- Reviewer
- User

**Comment by ChrisPalmer1** [comment]
High priority

**Comment by ben3000** [comment]
Some app endpoints accept parameters that themselves mirror the above set of roles with the values params.isOpusEditor and params.isOpusEditorPlus, so I'll have to change these to, for consistency.

**Comment by sbearcsiro** [comment]
@ben3000 Please create a review with all commits from both profile-hub and profile-service for this change at https://upsource.ala.org.au

**Comment by ben3000** [comment]
Hi @sbearcsiro, already done, see https://upsource.ala.org.au/profiles/review/PRFLS-CR-145

**Comment by temi** [comment]
@ben3000  the fix seems to have hidden the capability to publish a draft profile. Hence reopening it.

**Comment by ben3000** [comment]
Thanks @temi, that code is now corrected, and I've done a regex search for any other remaining code that wasn't updated.

**Comment by ChrisPalmer1** [comment]
When you go into 'Edit configuration' (here: https://profiles.ala.org.au/opus/foa/update), the list of possible roles is: Admin, Editor Plus, Editor, Reviewer, and User. Would be good to ensure the names of the roles are correct everywhere to avoid confusion.

**Comment by ben3000** [comment]
Hi @ChrisPalmer1, production looks like it is still running an older release of the code; https://profiles-dev.ala.org.au/opus/845def7a-5082-4750-b4fe-c360f73232fc/update contains a fix for this issue.

**Comment by RobinaSanderson** [comment]
Checked in profiles-dev environment, ALA Import test 2 collection. List of profile roles are correct in configuration options. Changed my role to Author and it appears correctly in the logged in profile.
