### ISSUE TITLE
PDF Upload - unable to upload in Production to a profile (documents tab) using Firefox and Google Chrome

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#490]
From Russell Barrett: 
under the ‘Documents’ tab for the new profile ‘Euphorbiaceae’ on the Production site.

I got the following generic error message.
![image](https://cloud.githubusercontent.com/assets/23368496/24121465/706339cc-0e0c-11e7-9f72-98f64fa0df8a.png)

I could only then select cancel and the file failed to load.

I am running Firefox ESR 24.5.0.

cheers,

Russell

**Comment by RobinaSanderson** [comment]
I was unable to reproduce this issue in dev using Firefox version 52.0.1

**Comment by ChrisPalmer1** [comment]
I tested this in Google Chrome, and after one false start where it didn't load, I was apparently able to load the three PDF docs. However, when I click on each file or try to download, in each case the following error comes up in a new web page:
Not Found
Profile Services
The requested page does not exist, view the list of available services.

**Comment by ChrisPalmer1** [comment]
This is still an issue.  Looked again in Euphorbiaceae in Prod site in both Chrome and Firefox. Interestingly, the PDFs Russell tried to load using Firefox are now there (so must have loaded themselves after a time when a bug was fixed). However, the uploaded files cannot be opened, as for Chrome (see above comment from 21 March). In both Chrome and Firefox,  user is redirected to another page (see image below): 
![euphorbiaceae pdfs](https://user-images.githubusercontent.com/26078913/26907234-7669c2c0-4c35-11e7-829c-3e09d3419e3d.png)

Also tried adding another PDF to another species profile, with the same result. Document uploads but unable to be opened.

**Comment by RobinaSanderson** [comment]
Not sure if this is related to this issue or to #468 but I can't upload a .csv file for the glossary, this will need to be done before production release.

**Comment by ben3000** [comment]
I am unable to reproduce this in dev or on https://profiles-dev.ala.org.au/opus/foa/documents, could this be a production configuration issue?

I note though, that if I add a document, the Date created displayed afterwards is the day before the one I typed into the form. This is usually because the date being entered gets converted from my time zone at 12am into the equivalent date/time in AEST/AEDT, thus resulting in a time in the previous day. The value should be converted into a localdate not a date/time when handling the form.

**Comment by m-hope** [comment]
@ben3000 , tested this an found the same as you... can upload a document without any issues.  However, I get a permissions error if I try and access any of the documents (my own or others)... could this be the same problem as the glossary permission error?

**Comment by RobinaSanderson** [comment]
The permissions error is given on a document being accessed from the Context page, whereas the profile page when you click on the document downloads it rather than views it. Could we make the context page also download rather than view as a short term easy fix?

**Comment by RobinaSanderson** [comment]
The upload works and this issue will be closed.
