### ISSUE TITLE
NSL services - NSL nomenclature is not being loaded on profile creation.

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#492]
Since early February, the NSL nomenclature information from NSL is no longer being added to a profile when it is created.

The issue is that the service call to the NSL from Profiles currently encloses the profile name in quotes (eg: https://biodiversity.org.au/nsl/services/api/name/acceptable-name.json?name="Silene+uniflora")... this causes a 400 HTTP response code (Bad request) and the nomenclature info is not returned (as seen in profile-service.log).  These quotes need to be removed from the call (eg: https://biodiversity.org.au/nsl/services/api/name/acceptable-name.json?name=Silene+uniflora).

If the NSL service is not available, the profile should still be created.

Note: this issue needs to be resolved prior to the import of profiles from FOA.

**Comment by RobinaSanderson** [comment]
If the service is not available should the profile creation fail? TBD

**Comment by RobinaSanderson** [comment]
Discussed with @ChrisPalmer1, the user should still be able to create the profile even if the NSL service is not available to populate the nomenclature.

It would be good to have a report to identify profiles without nomenclature information, I will create a story for this to be prioritised in the next session of the weekly eFLora meeting.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-132

**Comment by m-hope** [comment]
Can confirm that nomenclature information is now being added to new profiles and previously affected profiles can be 'corrected' by clicking 'Edit Name' in edit mode, selecting the 'Check Name' action and then clicking 'Update Name'.

**Comment by m-hope** [comment]
Also confirm that a forced index rematch on an entire collection will NOT fix affected profiles... at this stage only a manual edit as above will fix it.
