### ISSUE TITLE
Import - Set status of imported profiles to "Legacy"

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#496]
All imported profiles need to have the status of "Legacy".

This could be done by updating the import script to set the status. I think this would work best, as the default for non imported profiles should either be "Empty" or "Partial".

**Comment by RobinaSanderson** [comment]
Hi @m-hope I've added this to the To Do column. I've talked to Chris about this and left a message for Kevin, but I thought it would be good to get this in the list of things to do before Wednesday so that one of the devs could pick it up earlier rather than later. Happy for it to move to new issues if you would prefer to discuss it first.

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-134

**Comment by m-hope** [comment]
Can confirm that profiles are given the 'Legacy' status on the latest import.
