### ISSUE TITLE
profiles NSL name matches only plant names

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/profile-hub#499]
Currently, profiles looks up to the following URL for matching names (https://biodiversity.org.au/nsl/services/api/name/acceptable-name.json?name=Solanum+antillarum). But this only matches plant names. In the future, we might have to match animals or other living organisms. The url will have to change.

**Comment by RobinaSanderson** [comment]
Profiles only works with the NSL not the AFD. This will not be an issue until the NSL includes the AFD. So while there will be collections that have non-plant profiles with names matched from ALA, there isn't a nomenclature source of truth for non-plant names.

This should be readdressed if a nomenclature source becomes available or we are approached by the museum community.
