### ISSUE TITLE
PDF - Profile formatting in PDF

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#500]
As an eFlora user 
I want to generate a .pdf of a profile
That is easy to read and includes the information I need.

Please refer to mockup attached to https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release under heading "PDF requirements".

Business requirements:
1. In the title of the a profile:
- the Family and genus names will be in all Caps and centred
- the species and infra species will be left justified bold lower case
2. The description field will not have a heading, instead the text in the description will begin underneath the protologue for the profile
3. All other field headings within a profile will be inline and italicised.
4. main body text will Calabri 11pt
5. Formatting within the text of fields will be preserved. For example, where italics have been used in the text, this will flow through to the .pdf
6. Changes to the map:
- the map will be smaller and right justified in line with the Distribution field. 
- the Occurrences heading is no longer required
- the map will be greyscaled
- the map will have a border
7. Protologue citations:
- for family and genus profiles will appear centred under the title
- for species and infrs species will appear left justified under the title
- will be in Calabri 9pt
- will retain the formatting from the eFlora (e.g. the name of the publication with be in italics)
8. Remove "Taxonomy" section from pdf
9. Remove "Biodiversity Heritage Library references" section from pdf
10. Images will be provided at the end of the profile
11. Ensure information entered into the following acknowledgement fields is transferred to the .pdf:
- Author/s
- Editor/s
- Contributor/s

Note: there is also an "Author" field in the acknowledgements section, need to know if this should be removed or retained, if it is to be retained it should be included in the pdf.

**Comment by patkyn** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-178

**Comment by RobinaSanderson** [comment]
Tested this story.

Confirmed the following points are complete - 2, 3, 4, 5, 6, 8, 9, 11

Following issues found:

- Formatting for Family and Genus profiles reflects that used in the profile rather than what was specified in the example (not capitalised and centred). However, given time and technical constraints this is likely to be sufficient. Need confirmation from ABRS. (Story points 1 and 7)
-  Tested generating a .pdf from a profiles with an image (https://profiles-dev.ala.org.au/opus/alatest/profile/Acacia%20leucolobia)  and didn't get the image in the .pdf at all. It should have been at the end of the profile (Story point 10). I did check that the Images checkbox was ticked when generating the .pdf, it was, but no image made it through to the .pdf.

**Comment by m-hope** [comment]
Re-tested generating a PDF with an image.  Appears to be working as follows:
 - tested using ALA Test Collection on Profiles-dev, with Acacia victoriae and the correct images appeared in the PDF (both with all images selected for viewing, and with a restricted set of images)
 - tested in MLH Test Collection, by creating an Acacia leucolobia profile, and the image for that profile appeared in the PDF.
