### ISSUE TITLE
PDF - Cover page formatting

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#501]
As a user of the eFlora 
I want to know what the .pdf is about by the front cover
So that I can distinguish between multiple pdfs

Changes to cover page:
1. Remove the image in the cover page
2. Insert the banner image (banner image to be provided, postioning to be decided when we get the image)
3. At the bottom of the cover page include all logos entered in configuration
4. For a single taxon .pdf (lower levels are NOT included), include the authors of the profile on the cover page
5. For a multiple taxa .pdf, include the authors of the highest level taxon on the cover page

**Comment by ChrisPalmer1** [comment]
Hi Robina, re Point 4, might just be worth specifying that this relates to the title. Cheers Chris

**Comment by RobinaSanderson** [comment]
Hi @ChrisPalmer1 - I asked @temi to take a look at the cover sheet image options. His preferences are:
1. having the white space with the logos at the bottom of the page rather than in a band in the middle
2. including the yellow background as part of the image, we will then superimpose the text over the image rather than have a top image and a background.
3. image format .png is fine

In addition, do you want an image as a back cover for the .pdf? Or are you happy as is with the last page of the .pdf being the last page of the profile(s)?

**Comment by ChrisPalmer1** [comment]
Hi Robina, some answers to your questions:
1. Sounds good. We were thinking the same thing from a purely aesthetic viewpoint (see attached PDF, below. Let me know if it hasn't loaded properly). This is our preferred cover page look. 
[2017-05-02_Item 8b_eFlora Draft PDF cover and web banners.pdf](https://github.com/AtlasOfLivingAustralia/profile-hub/files/945811/2017-05-02_Item.8b_eFlora.Draft.PDF.cover.and.web.banners.pdf)

 2&3. We can provide you with a cover pg with image and background in one layer as a .png. Any particular file size...?
4. Yes. We were thinking of an image for the back cover, if this is simple. It will also be a combined (slightly different) image+background , including the logos but no text at all. Can also provide as a .png

**Comment by temi** [comment]
@ChrisPalmer1 , size less than 5MB with 300 dots per inch in A4 dimension. Thanks!

**Comment by RobinaSanderson** [comment]
Hi @ChrisPalmer1 - it would be good to get a draft of the back cover image.

**Comment by ChrisPalmer1** [comment]
Our graphic designer is preparing .pngs of the front and back cover pages. basically it will be similar to the front cover, but without any text and without the dark green banner. But it will retain the logos if that's possible.

**Comment by RobinaSanderson** [comment]
Tested the following:
1. Remove the image in the cover page - complete
2. Insert the banner image - complete banner image incorporated into title of collection
3. At the bottom of the cover page include all logos entered in configuration - complete
4. For a single taxon .pdf (lower levels are NOT included), include the authors of the profile on the cover page - complete
5. For a multiple taxa .pdf, include the authors of the highest level taxon on the cover page - complete only the authors associated with the profile from which "Export as PDF" was selected are shown on the cover page, authors of lower level profiles are ignored.

Testing complete this issue can be closed when code review is complete.
