### ISSUE TITLE
PDF - Footer and header format

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#502]
Refer to mockup attached to: https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release

1. Include the following elements in the .pdf header:
- Flora of Australia: < pdf title > (left justified)
- Page number (right justified)

2. Header text will be in default 9 pt and italicised

3. Include in the footer:
- Downloaded from < URL for collection > on < date and time > (centred)

4. Footer text will be default 9 pt

**Comment by patkyn** [comment]
Is this still applicable?

**Comment by RobinaSanderson** [comment]
From Chris Palmer:  
Yes, please include them.

**Comment by RobinaSanderson** [comment]
Hi @patkyn  - Chris noted that this still needs to be done, sorry I didn't get back to you earlier.

**Comment by m-hope** [comment]
Confirm header and footer additions as outlined above correctly appear in PDF documents... can close this issue once reviewed.
