### ISSUE TITLE
PDF - Inside cover page format

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#507]
As the publisher of the eFlora
I want to make certain information available to a .pdf user
So that they understand their rights to the work and can cite the work

Changes required:
1. Include the eFlora ISSN from configuration
2. Include the copyright statement from configuration
3. Include license long description from configuration

**Comment by ChrisPalmer1** [comment]
Title of publication likely to be 'Flora of Australia'. (Consensus opinion is that this is the preferred formal title; 'eFlora' will just be an informal name.)

**Comment by patkyn** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-177

**Comment by RobinaSanderson** [comment]
Tested:
1. The ISSN as entered in the configuration has been included
2. The copyright statement from configuration has been included - note there are several further paragraphs on copyright mentioning contact the ALA if there is believed to be an infringement which cannot be edited or deleted by the Administrator.
3. The license long description from configuration has been included.

Testing complete, this issue can be closed once code review is complete.
