### ISSUE TITLE
PDF - Include keys in PDF

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#508]
As a eFlora pdf creator
I want to include keys in the pdf
So that I can take the pdf into the field and refer to the keys when identifying plants

Requirements
1. Insert keys in the pdf document after the common names and before the images
2. Use Calabri 9pt for text
3. Format as numbered couplets (this is the bracketed option when viewing online)
4. Species names will be spelled out in full (e.g. Arenaria leptoclados rather than A. leptoclados)
5. Species names will be in bold formatting

Does this need to be attribute that can be selected/deselected by an user for inclusion in the PDF? Yes, if it doesn't require more than 1/2 a day of work. If it will take longer we'll split it into it's own story and include later if there's time.

**Comment by ChrisPalmer1** [comment]
Yes. I think any attribute that can be switched on or off really adds to user functionality, and this includes keys. Some users will rely on them, but others may just want text and/or images in the field or elsewhere.

**Comment by RobinaSanderson** [comment]
@m-hope check with Neils whether this has been done before.

**Comment by patkyn** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-150

**Comment by ChrisPalmer1** [comment]
Tested with Albizia (key included just before the first species profile, which is appropriate. Couplets are numbered, species names spelled out in full, but not in bold text. But they're clear enough. May not be as clear for a larger genus). 

Arabidella: same result as above, although species names in key sometimes split into 2 lines (ideally, both genus and species names would be on the same line. Is a bit clearer).

**Comment by RobinaSanderson** [comment]
Confirmed that .pdf is generated with keys appearing after the images and with species name text not in bold.

@ChrisPalmer1 @KevinThiele - does this need to be fixed before production release?

Confirmed also that where a key leads to a single species the text [link through] appears and the species name is listed at the end of the line. The link through text could simply be removed with the already available species name completing the line of the key. If a link would be preferred, we'd need to know if the link should be within the .pdf document (this seems logical to me) or to a profile within the collection. This would need to be prioritised.
@ChrisPalmer1 @KevinThiele  let me know what you think.

**Comment by ChrisPalmer1** [comment]
To me, species name not in bold text is not critical, though would be nice to fix as it stands out more in doc. Yes, [link through] text should be removed, leaving the species name. My feeling is that a link is not essential if it will take time to implement. What do you think on these Kevin..?

**Comment by RobinaSanderson** [comment]
Problem of not dealing with genus's with only one species has been raised as bug #552.
Problem with bold formatting raised as bug #555
