### ISSUE TITLE
UI - Direct profile display if one search result and an accepted name was entered

### ISSUE THREAD

**Issue by KevinThiele** [AtlasOfLivingAustralia/profile-hub#509]
If a user searches for a profile and the result is only one profile, display the profile directly (and skip the "search results" page - this then becomes essentially a disambiguation page when there are multiple results).

**Comment by RobinaSanderson** [comment]
This makes sense if the majority of users will open the single search result and performance is good so that seeing a summary on the search results view takes the same amount of time as opening the profile.

Just wondering if users would prefer to remain on the search results page with a summary so that they can easily do another search without navigating to the search page?

**Comment by KevinThiele** [comment]
Again - the case where a user does a search, looks at the minimal information displayed on the search results page, then decides to do a different search, will be less frequent than the case where a user does a search, one result is returned, then they click on the link to go to the page. So the behaviour suggested above I think is optimal for the most common case.

**Comment by sbearcsiro** [comment]
IMHO this would be technically straight forward to add and the idea definitely has merit (I like anything that reduces the amount of mousing), however I worry about not matching user expectations (especially novice users), ie having different actions for different search results.  For better or worse Google has taught us to expect a page of results when performing a search.

Additionally if it was applied to all single result searches and we had a synonymous profile as the one result (or misapplied, etc) then I think that we'd also want to carry the explanatory info of why this profile was returned to the profile page.  This would require passing of the search context to the profile page (which AFAIK are pretty context free right now) and probably introduce additional noise in the profile URL (which I find aesthetically displeasing) and if the URL is shared then folks are left wondering why they're being told this thing is a synonym of a search term which wasn't theirs).

We could also consider the following:

1) Explanatory text explaining why the user is being redirected to the profile (the system might even be slow enough 😳 for this to be readable on the search results page).
2a) A "I'm feeling lucky" type button that has this behaviour (or perhaps always redirects to an exact match)
2b) A stored preference for the user that would enable this behaviour (which allows advanced users to "opt-in")
2c) Yet another checkbox in the search options (perhaps with 2b as a default)?

**Comment by RobinaSanderson** [comment]
Spoke to Simon - estimate for the original request 0.5 days, if we want to do any of Simon's other suggestions it will be more time.

**Comment by KevinThiele** [comment]
Re Simon's comments - good to have these thoughts. A couple of responses:

1. Re Google creating an expectation of a results page - Google very, very rarely provides a single return, so I think this is not a good comparison. A better comparison is Wikipedia - search on an item there and you'll be taken straight to the matching page (unless there are multiple returns in which case you may be directed to a disambiguation page instead). To me this is a good comparison, as single-result returns are most common, as in our case.

2. Your point about a synonym search, where a user is directed to a page with a different name to the one they searched for, is a good one. An option here would be to restrict the direct-navigation to cases where the match is straightforward - the system will know whether or not this is the case, so can behave accordingly.

Let's talk this through with the wider group when we next meet.

Cheers - Kevin

**Comment by KevinThiele** [comment]
A minor change to the original proposal - if the user searches for a profile and the result is a single profile that is nomenclaturally straightforward (e.g. Acacia leucolobia -> Acacia leucolobia), then they should be directed straight to that profile. If however the search returns a single profile that may be nomenclaturally surprising for the user (e.g. Acacia abietina -> Acacia linifolia) then they should be taken to the results page, as this is the opportunity to explain what's going on.

**Comment by m-hope** [comment]
This issue has now been superseded with issue #529
