### ISSUE TITLE
Home page - Help pages point to wordpress site (site to be created by ABRS in cloud) 

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#513]
Currently, help pages are accessed via the small help icon in the header.

Content so far is about collection administration and editing profiles.

Generic user help topics should include the following as they can't be customised by the collection administrator:
* search
* browse
* using a list to filter
* glossary
* configure collection
* reports

Collection specific content should include the following customisable features: 
* collection home page
* collection about page
* Identify page
* profile page - create
* profile page - edit
* profile page - view

Flora of Australia help is at: https://ausflora.net/

**Comment by ChrisPalmer1** [comment]
Hi Pat. I'm looking into WordPress at the moment. Am I correct in thinking that all you'll need is a web address and when the user clicks on the appropriate icon (wherever they are) they will be taken to the already-prepared WordPress site..? Thanks

**Comment by patkyn** [comment]
While looking at the code, there's an existing config in /data/profile-hub/config/help-mappings.json where the baseUrl config is currently pointing to https://atlasoflivingaustralia.github.io/profile-hub/
We can simply change the baseUrl to point to a new wordpress site web address if we have the link.

**Comment by ChrisPalmer1** [comment]
No problem. Currently working on procurement procedures for the lowest-cost version to avoid the ads.

**Comment by RobinaSanderson** [comment]
Hi @ChrisPalmer1  - let me know when the wordpress URL is avaialble so we can test this.

**Comment by RobinaSanderson** [comment]
From Chris:

Here’s the link to the draft WordPress help site:  https://ausflora.net/

**Comment by RobinaSanderson** [comment]
Hi @patkyn and @m-hope  - I've gone through the pages in a collection identified whether i think they should point to generic platform help or to collection specific help.  See the list above.

I think we need to set the help up so that by default it points to the GiTHub help we maintain, but then the help for each collection page (Search, Identify, Profiles page - edit, profile page - view, etc.) can be configured by the collection administrator to a URL of their choice (an intermediary step might be for this to be configured in the code).
I'm not sure how difficult this would be, what are your thoughts?

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-179
