### ISSUE TITLE
Error message on screens caused by Keybase error

### ISSUE THREAD

**Issue by ben3000** [AtlasOfLivingAustralia/profile-hub#515]
Whenever I load a profile-hub project today, I'm getting an error from http://keybase.rbg.vic.gov.au/ws/projects:

<pre>A Database Error Occurred

Error Number: 1055

Expression #7 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'keybase.fk.KeysID' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

SELECT p.ProjectsID, p.Name AS ProjectName, p.TaxonomicScopeID, p.TaxonomicScope, p.GeographicScope, p.ProjectIcon, fk.KeysID AS FirstKeyID, fk.Title AS FirstKeyName, count(DISTINCT k.KeysID) AS NumKeys, count(DISTINCT coalesce(gi.MemberID, l.ItemsID)) AS NumTaxa FROM (`projects` p) JOIN `keys` k ON `p`.`ProjectsID`=`k`.`ProjectsID` LEFT JOIN `keys` fk ON `p`.`TaxonomicScopeID`=`fk`.`TaxonomicScopeID` AND p.ProjectsID=fk.ProjectsID LEFT JOIN `leads` l ON `k`.`KeysID`=`l`.`KeysID` LEFT JOIN `groupitem` gi ON `l`.`ItemsID`=`gi`.`GroupID` GROUP BY `p`.`ProjectsID` ORDER BY `NumKeys` desc

Filename: /var/www/keybase/models/webservicesmodel.php

Line Number: 305</pre>

**Comment by RobinaSanderson** [comment]
All known bugs related to keybase are fixed. If any more occur, they should be documented separately.
