### ISSUE TITLE
Collection configuration - deleting Author field stops profiles from loading (this may be more about deleting an attribute with data)

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#516]
As a Collection administrator
I want to be prevented from deleting the Author field
As this will stop profiles from loading

The ALA Test Design collection had 2 author fields, in the Authors and Acknowledgements vocabulary for the collection configuration. I deleted one and the profiles stopped loading.

**Comment by RobinaSanderson** [comment]
Closing as issue covered in #551

**Comment by RobinaSanderson** [comment]
Closed by mistake, this is not a duplicate issue.

**Comment by m-hope** [comment]
This issue may related/superceded by #374 or #375.

**Comment by RobinaSanderson** [comment]
Tested by:
1. create new collection
2, in the configuration settings - Acknowledgements vocabulary, ensure there is an author term
3. Add a profile with an author
4. Delete the author term from the Acknowledgements vocabulary
5. Ensure you can open the profile

Result:
The system forces you to move any values using the selected acknowledgements term to another. You are unable to delete a term with any values already assigned to it. This means you cannot make the collections unusable and provides the user a pathway to delete the term, a better result than simply not allowing the Author field to be deleted.

However, deleting the Author term means that the Author field in the .pdf for a profile is populated with a null value. I will raise a separate issue for this.

**Comment by m-hope** [comment]
Can also confirm that this functionality is unaffected by a masterlist being active... ie: profiles that are currently hidden by a masterlist will still be updated with the data being moved to another term.

Close once reviewed.
