### ISSUE TITLE
UI - Links to home page not working

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#517]
Since the new home page has been implemented, the links to the collection home page on search, browse, identify and context pages are not working.

![image](https://cloud.githubusercontent.com/assets/23368496/25876902/7a0d36e8-3563-11e7-9a79-f789feafcae8.png)

**Comment by ben3000** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-155

**Comment by RobinaSanderson** [comment]
Home link is now in header for all function page. I checked search, browse, identify and context, home links work from each. Checked profile page home links are in header and in breadcrumbs, in both cases links took me back to home page. Also checked from a published profile and from a draft profile, Checked home link from reports page and Edit configuration page, both worked.
