### ISSUE TITLE
Consolidation of search and other items on the main menu bar

### ISSUE THREAD

**Issue by KevinThiele** [AtlasOfLivingAustralia/profile-hub#519]
A number of items on the main menu bar are redundant and/or contextually problematic and/or can perhaps be dealt with in better ways.

1. Identify. This is problematic, as identification is context-sensitive. Every profile for which there is a key (families, genera, species with infraspecies) will have an Identify tab. The Home page has the Identify button, which appropriately opens the top-level key (the key to families). Identify in the header also opens the top-level key. Hence, if this stays we have an Identify tab that opens the key for the page, and an Identify header item that opens a different key. I think this is confusing as the two are not differentiated. One could argue that being able to open the top-level key from any page would be marginally useful, but it will be readily (and less confusably) accessible by going Home.

2. Context. Ditto for context. This opens a "library" page that gives access to extra documents relevant to the page. Profiles that have attache documents will have a tab for this. Again, the item in the header opens the top-level documents (those accessible from the Home page). If someone wants to open these documents rather than the ones in context for the page, they can go Home.

3. Profile Collections. This is also in the footer. I think that's the better place for it.

4. Glossary. This should stay in the header (and be removed from the footer)

5. Flora of Australia. I think this should stay, but be replaced by "Home"

6. Search - see #520 for issues around this.

**Comment by m-hope** [comment]
This issue is now covered by #524
