### ISSUE TITLE
review how biostatus, naturalised status, weed status, conservation status etc is being handled. Legal status needs to be seen upfront

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#52]
http://www.bugherd.com/projects/58735/tasks/38

**Comment by ala-bugherd** [comment]
This is probably out of scope as far as the profile editor is concerned. These data are managed in the lists tool.

**Comment by ala-bugherd** [comment]
Can biostatus etc be displayed on the profile page drawing from data in list tool then?

**Comment by ala-bugherd** [comment]
Yes, absolutely. I discussed this with Mark C.  The various statuses for a taxon should be accessible via a webservice.

**Comment by ala-bugherd** [comment]
Thanks for your message. I will be out of the office on 24 April and in meetings with only intermittent email contact 27-30 April.

**Comment by m-r-c** [comment]
This has been done. Implementation is via a list that the collection admin maintains (in specieslist). This list can contain any status information, and will be displayed on the profile pages.
