### ISSUE TITLE
Search access

### ISSUE THREAD

**Issue by KevinThiele** [AtlasOfLivingAustralia/profile-hub#520]
Currently, there are two Search options on the header, a Search link and the search box. These either:

1. perform the same search and give the same result, in which case one is redundant; or
2. perform differently, in which case we have a problem

Assuming that they perform the same search, there is one other small difference: the Search link navigates to the Search page which provides a range of search options, while the Search box gives only limited options (Text vs name search).

If the options are important, then the search box should either be removed or the two differentiated by e.g. renaming the search box "Quick Search" and the Search item "Advanced Search". I don't think this differentiation makes much sense, as the "advanced" options are pretty minimal.

Note that a number of the options on the Search page I think can and should be removed (see #521), making the difference even more minimal.

I recommend that we:

- keep the search box 'cos it's cool
- remove the Search item
- add a few options to the search box to make it fully functional (see #521)

**Comment by m-hope** [comment]
Note that this issue is now covered under #524 and #528
