### ISSUE TITLE
Search options

### ISSUE THREAD

**Issue by KevinThiele** [AtlasOfLivingAustralia/profile-hub#521]
There are currently six Search options, four for Name search and two for Text search.

Name search options are:
- Include alternate names   
- Look for matching names in the ALA   
- Look for matching names in the NSL   
- Include archived profiles

Text search options are:
- Must contain all terms
- Include archived profiles

The "Include alternate names" checkbox qualifies a name search, allowing the user to include/exclude vernacular name matches in the search result. However, consider "spinifex": this is both a genus name (it's a widespread genus of coastal sand-dune grasses) _and_ a vernacular name for, confusingly, a different genus (_Triodia_) of arid-zone grasses. At the moment, a name search for "spinifex" with "alternate names" off would presumably return the genus _Spinifex_ only; with "alternate names" on it would return both _Spinifex_ and _Triodia_; there is currently no way to search for it in its vernacular sense only. This could be fixed by having three top-level search options "by scientific name", "by vernacular (common) name" and "with text". This helps differentiate the search behaviour more precisely, and allows a "spinifex" search to return more precise results.

"Look for matching names in the ALA/NSL" I think is a problematic option, which is there mainly for historical reasons. The name matching using the NSL directly is now working as expected. Either adding the ALA to the search function returns the same result (in which case it's redundant) or a different result (in which case it's problematic). Some collections (e.g. indigenous knowledge) may wish to use the ALA only; others (e.g. Floras) will want to use the NSL only. I recommend that this option be removed from here and be optioned in collections admin instead. 

That leaves "must contain all terms" and "include archive" as the only remaining options.

If there's a way to deal with these in the Search box dropdown, I think that would be best.

**Comment by m-hope** [comment]
This issue is superseded by issue #530
