### ISSUE TITLE
Distribution map is not working

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/profile-hub#522]
It appears that when re matching names, occurrence query field is not updated with the latest LSID. updating occurrenceQuery field should fix this issue.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-161

**Comment by RobinaSanderson** [comment]
Tested by:
* in profiles -dev, ALA Test collection, created new profile Dysoxylum Craziness
* matched to Dysolxylum spectabile
* distribution map shows distribution for Dysolxylum spectabile
