### ISSUE TITLE
UI - new Home Page

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#523]
Rearrange current Home Page components to meet the new design as displayed here: <https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release#UserInterfaceforProductionRelease-Mockup-10>

Tasks include:
 - Splitting the current banner into two adjoining frames (note: no special join between the frames is required, just hard edges):
         - Frame 1 (lefthand side) to contain a static image (provided as the current home page banner image in the collection settings
         - Frame 2 (righthand side) to contain the carousel of sliding images.
 - Rearranging the remaining items (button list, blurb, and blog display) side by side in the area below the banner
 - The previous buttons for "Add new Profile" and "Edit Collection" need to be removed and added to the menu in the header (see #524 )

Notes:
 - The header and footer components will be the same for all pages (see #524 )

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-164

**Comment by RobinaSanderson** [comment]
Issue complete.
