### ISSUE TITLE
UI - new Header

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#524]
Rearrange the current header to match the new UI mockups here: <https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release#UserInterfaceforProductionRelease-Mockup-11>

Tasks include:
 - move all menu items to right align against right margin.
 - move the current search box to the left-most positon (note: at this stage keep the current search box functionality... enhancements for this search box will be covered in #528 )
 - replace the 'profile name' menu item to "Home" and link to that collection's home page
 - remove the 'Search' menu item (it is now replaced with the search box)
 - Keep the Browse menu item linking to the Browse functional page
 - Remove the 'Context' menu item (it makes sense for it to be only accessible from the home page via the buttons)
 - Remove the 'Profile Collections' menu item (Collections can be accessed via the Footer entry)
 - Remove the 'More' menu item and replace it with the 'About' item in the 'More' submenu drop down.  The 'Reports' submenu item should be moved to the 'User Settings' menu (see below)
 - Retain the 'User Settings' menu item, but add the Reports link and the previous Home Page "Add new profile" and "Edit Collection" buttons to the bottom of the menu drop down, for those users with the appropriate permissions (ie: add the buttons to the menu, but retain the user permissions check)
            - if adding the Reports page link and the old home page buttons to the 'User Settings' menu is not possible, then keep the 'User Settings' menu as is, and a new menu item needs to be created with the gear/cog symbol that will display those three items if the user has the appropriate permissions.
 - Retain the help icon linking to the collections help page.

Note:
 - This header is still to be used for all collection pages.

**Comment by m-hope** [comment]
Once this issue is implemented then close #475 as it will no longer apply.

**Comment by temi** [comment]
@m-hope creating new collection has an additional option "copy an existing profile". Should I include it by creating a sub menu or ignore it?
![image](https://cloud.githubusercontent.com/assets/1152259/26392945/a0287024-40ab-11e7-9998-65354724e265.png)

**Comment by m-hope** [comment]
@temi - ah yes, I had forgotten that command.  Please include it as another item in the user settings menu for now (directly under the Add new profile item)... no need for an extra submenu.

**Comment by temi** [comment]
@m-hope is there a specific header nav items when rendering all collections? at the moment there is only search box and user setting icon. should there be anything else?
![image](https://cloud.githubusercontent.com/assets/1152259/26437577/53a30140-4161-11e7-8e03-96d0a98fb9e0.png)

**Comment by m-hope** [comment]
@temi, can't think of any others, but I'll come and talk to you tomorrow.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-165

**Comment by sbearcsiro** [comment]
@m-hope the person icon for the drop down menu is misleading and no longer relevant to the contents of the menu.  I would replace it with a ['hamburger' icon](http://fontawesome.io/icon/bars/) (aka the three vertically stacked horizontal lines icons you see in Firefox) or the [three vertically stacked dots](http://fontawesome.io/icon/ellipsis-v/) you see in Chrome / Android apps.  It should also have title / label for screen readers, probably something like 'Settings' (it's undefined at the moment).

**Comment by temi** [comment]
We already have a hamburger icon. It appears for small screen sizes. how about [ cogs ](http://fontawesome.io/icon/cogs/) or [wrench](http://fontawesome.io/icon/wrench/)?

**Comment by sbearcsiro** [comment]
Cogs or wrench have the wrong correlation since the drop down contains no controls, a label with the users role, links off site, etc.  So hamburger is fine but we should fix the drop down in the collapsed nav to either be auto expanded (in which case the icon can be hidden) or replace the icon with text since there is no need to preserve horizontal space (and reinstate and right / end align the caret).

**Comment by KevinThiele** [comment]
Are we still talking about the menu shown at top-right in https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release?preview=/382665949/403677782/EFlora%20Home%20page%20(with%20menus)%20mockup.jpg#UserInterfaceforProductionRelease-Mockup-11

If so, the person icon still seems OK to me. This will be context sensitive - for a non-logged-in user it will only give the login link. For logged-in users, the first items are about the user and their role, the remaining items are things that the logged-in user can do because of their role.

**Comment by RobinaSanderson** [comment]
Hi @temi  and @sbearcsiro - I've been looking for the Copy existing profile action and can't find it either under the hamburger or the options when on a profile page. I'm using ALA Test and I'm an admin in that collection so it shouldn't be a permissions issue.

If I've just missed it, let me know and I'll close this issue. If it is no longer visible, I'll raise a separate bug for it.

**Comment by temi** [comment]
@RobinaSanderson That is interesting. I did some testing right now. I was able to add an account to ALA Test as admin and I got all the options including Copy existing profile.

**Comment by RobinaSanderson** [comment]
Sorry @temi  - Now I see it. My apologies.
![image](https://user-images.githubusercontent.com/23368496/28091463-308d4976-66d3-11e7-8e55-ed62fb95055c.png)
 
This issue is complete.
