### ISSUE TITLE
UI - new Footer

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#525]
Rearrange the current footer to match the new UI mockups here: https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release#UserInterfaceforProductionRelease-Mockup-11

Tasks include:
 - Retain all logo functionality
 - Remove the 'Site information' heading and the 'About Us' link.
 - Move the 'Site navigation' heading to the right margin (ie: in the same place as the 'Site information' heading)
 - Remove the 'Glossary' item
 - Add a 'Contact Us' item under 'Site navigation' heading that links to the Collection contact email address.

Note: 
 - This footer is still to be used for all pages and page types.

**Comment by ben3000** [comment]
Should the social icons remain in the footer?

**Comment by ben3000** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-159

**Comment by RobinaSanderson** [comment]
Hi @ben3000  - I just had a quick discussion with @m-hope, and we think the default logo should be the ALA as the profiles tool may be used for a range of purposes not just the Flora of Australia. Sorry to be a pain but could you please change it to the ALA logo?

**Comment by ben3000** [comment]
@RobinaSanderson OK, so swap the position of the ALA and the Australian government logos?

**Comment by RobinaSanderson** [comment]
Yes please.

**Comment by temi** [comment]
@m-hope | @RobinaSanderson - Footer text and license (added in #450) are no longer required?

**Comment by m-hope** [comment]
@temi, ah thanks for spotting that... both the ISSN and license should still be included in the new footer... they are missing from the mockup because it was based on an old image prior to #450 being implemented.

**Comment by temi** [comment]
@m-hope - how about 'footer text'? This is a configurable item for an opus in branding section.
In production [profiles](https://profiles.ala.org.au/opus/foa), it renders the text "Australian Biological Resources Study".

**Comment by m-hope** [comment]
@temi - yes that should be included too.

**Comment by temi** [comment]
@m-hope sorry, one last question - contact us - The mock up shows it should be in the site navigation section but previously it was rendering with social icons. Which is the right one?

**Comment by m-hope** [comment]
No problems @temi... For now I would include both... some people might recognise the email icon, but others are more familiar with the "Contact Us" text link... I suspect the graphic designer might have an answer for us in the future.

**Comment by RobinaSanderson** [comment]
Hi @m-hope Just want to check the logo requirements. We need the atlas logo, and the logo of the state or department producing the collection content (which they can upload in the configuration), do we need the Australian coat of arms? As far as I know the other ALA applications don't have the Australian coat of arms.

**Comment by m-hope** [comment]
No, we can remove the coat of arms...  If people want it, they can include it as a logo...

**Comment by RobinaSanderson** [comment]
Hi @ben3000 - Sorry, to make you come back to this, but could you please remove the Australian coat of arms logo?

**Comment by ben3000** [comment]
OK, will do.

**Comment by ben3000** [comment]
@RobinaSanderson OK, the coat of arms has been removed. This now means that the ALA logo only appears if no other logos have been added by a collection editor.

**Comment by RobinaSanderson** [comment]
This issue is complete.
