### ISSUE TITLE
UI - remove breadcrumb from all functional pages

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#526]
For all functional pages (eg: Search, Browse, Identify, Library/Context, Reports, etc), remove the "PROFILE COLLECTIONS/FLORA OF AUSTRALIA" breadcrumb.

The reasoning is that the 'FLORA OF AUSTRALIA' link will be replaced with the 'Home' menu item, and that the link to other collections should be done via the link in the Footer.

Clarification:
 - breadcrumbs are still required for the profile/taxa pages.
 - the breadcrumb should also be removed from the Home page (see #523 )

**Comment by ben3000** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-160

**Comment by RobinaSanderson** [comment]
Checked search, browse, about, reports, identify and context pages - breadcrumb is no longer on the page.

Checked taxon page - breadcrumb works.

Issue complete.
