### ISSUE TITLE
UI - Menu Search Box enhancements

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#528]
Need to enhance the functionality of the menu bar search box so that users have the ability to select options that are available on the Search page:

The suggestion is to modify the current search box drop down menu as follows:
 - Retain both the 'Search for profiles by Scientific Name' and 'Search for profiles containing text' items
 - Add an additional 'Search for profiles by Common Name' option which works as a text search specifically on all attributes marked as a name (it should not search the profile name or the matched name). This option replaces the current name search on the Search Page with the 'include Alternate Names' option checked on.
 - Additionally have two check box items at the bottom of the drop down menu.  ... when either of these check boxes are selected, the drop down menu should not disappear... only selecting any of the 'Search for profiles...' items will remove the drop down box  The options below have the same functionality as the equivalent options on the Search Page:
                 - 'Must use all items in text searches' 
            - Note: if this check box functionality is not possible, then we need to explore other options to allow users to access the two options available.

A mock-up of the intended look can be found here: <https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release#UserInterfaceforProductionRelease-Mockup-11>

**Comment by temi** [comment]
all issues in #530
