### ISSUE TITLE
Masterlist - Stubs created by masterlist need NSL nomenclature information

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#532]
This assumes stubs created by the masterlist can be automatically matched to NSL concepts.
If so, the NSL nomenclature information needs to be populated on the stub.

Hi @m-hope should we expect automatic matching, or should stubs be manually matched?

**Comment by RobinaSanderson** [comment]
check with business representatives

**Comment by m-hope** [comment]
General consensus from business owners is that auto generated NSL nomenclature info *should* be included with profile stubs.

They acknowledge that if the auto name match is incorrect for a stub profile then we will also generate an incorrect nomenclature.

**Comment by KevinThiele** [comment]
It this stage, if it's easier to not have stubs at all (i.e., hide all stubs), then this issue should be parked

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-166

**Comment by m-hope** [comment]
need to confirm once name matching has been investigated and fixed (see issue #591)

**Comment by m-hope** [comment]
Have confirmed that in a collection with a masterlist assigned, that nomenclature info (eg: protologue) is displayed and that if you edit a stub, the nomenclature attribute is available for selection.

 Note: using "Masterlist test 2 (22052017)" as this has a selection of acacia species with a variety of name issues), as follows:
 - Acacia victoriae (current accepted name),
 - Acacia atrox (accepted name, but also inval. synonym of itself),
 - Acacia michaeliae (unknown name)

**Comment by m-hope** [comment]
Reconfirmed that stub profiles are inheriting their nomenclature from the NSL.

It is noted that this information is currently only available in a profile edit mode.  Issue #644 is in place to display this information on the public view.
