### ISSUE TITLE
Masterlist - Autocomplete should only show names in masterlist

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#533]
At the moment, autocomplete name options include profiles not in the masterlist. If the names is not in the masterlist, it should not display as an autocomplete option.

**Comment by patkyn** [comment]
Autocomplete search is already searching profiles by Opus id.  After doing Sync Now on Masterlist, this takes some time to complete, and after few minutes, the deleted profile will eventually be removed from Masterlist and you won't see it appear in the autocomplete list anymore.

**Comment by RobinaSanderson** [comment]
Tested by:
* in masterlist test collection, performed scientific name search for Dysoxylum acutangulum
* Dysoxylum acutangulum was available in the autocomplete and produced 2 results when the search was done
* created masterlist test 3 in ala lists tool - this is a copy of masterlist test 2 with the name Dysoxylum acutangulum removed
* went into masterlist test collection configuration
* selected masterlist test 3 list as the masterlist for the collection
* clicked Sync (sync took approx 2 minutes)
* 15 minutes later Dysoxylum acutangulum is still in the autocomplete options

**Comment by RobinaSanderson** [comment]
Tested again and 1.5 hours after the masterlist had been applied, the name still appeared in the autocomplete where the profile was any status that was not Empty. That is, this worked if the profile had only been created as a stub, but not if it had any data added. 

Note: I tested this using Sync not Regen to apply the masterlist.

**Comment by RobinaSanderson** [comment]
Tested by:
1. checked there was no masterlist applied to https://profiles-dev.ala.org.au/opus/alatest 
2. Searched for "Acacia robinaii"
3. Found profile
4. Checked the term was provided when doing a scientific name search as part of the autocomplete options
![image](https://user-images.githubusercontent.com/23368496/32254183-4400d7d4-bef3-11e7-8aab-759bcffe6449.png)

5. selected "Masterlist test 3 20170609" as the masterlist to the collection and saved
6. selected "Sync now"
7. Typed "acacia" into the scientific name search and autocomplete only provided links to those profiles on the masterlist.
![image](https://user-images.githubusercontent.com/23368496/32256624-3140b1bc-bf04-11e7-805e-f4db11df05c7.png)

Test complete.

**Comment by m-hope** [comment]
Also tested and confirmed this works as expected.
