### ISSUE TITLE
rematch names does not update guid, classification of draft

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/profile-hub#538]

**Comment by temi** [comment]
@m-hope what are your thoughts on this? should draft profile guid and classification be updated?

**Comment by m-hope** [comment]
@temi ... as you are supposed to be change the draft when you're in edit mode it makes sense that the name rematch applies to the draft as well.  In fact the name rematch shouldn't actually apply to the public view page but I suspect that is going to cause a few problems if the two aren't in sync...

**Comment by temi** [comment]
@m-hope "In fact the name rematch shouldn't actually apply to the public view page" - this  would cause map, link to ALA and possibly other things to be broken on public view. Do we want such a situation?

**Comment by m-hope** [comment]
@temi no we don't... I was just pointing out that technically when a profile is in draft mode it means that any edits shouldn't be 'visible' until the profile is released to public view... but in this case I think it is more important to ensure that both versions of a profile (public view and draft) are in sync with the name matched.
We need to document this for the ABRS staff so they know that in this case it is the exception to the rule.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-162

**Comment by m-hope** [comment]
Need to test once the name rematching works again...

**Comment by m-hope** [comment]
Using a profile that needed a name rematch, placed it into draft mode and re-matched the name.

Confirmed that the new rematched name was visible in the edit and public views in both draft mode and once the draft changes are published.
