### ISSUE TITLE
Deleting the first attribute on a profile causes a display error

### ISSUE THREAD

**Issue by ben3000** [AtlasOfLivingAustralia/profile-hub#539]
Edit a profile with at least 2 attributes:

![screenshot from 2017-05-23 16 52 54](https://cloud.githubusercontent.com/assets/1963681/26346344/7568da78-3fd8-11e7-8083-5bd3e10f88df.png)

Delete the first attribute listed on the page:

![screenshot from 2017-05-23 16 53 21](https://cloud.githubusercontent.com/assets/1963681/26346365/8e16a834-3fd8-11e7-9db3-49de2d5e7fe0.png)

Note that the attribute that remains no longer has a styled in-page editor. By comparison, editing a profile with only one attribute, then adding another attribute, then deleting the first works fine.

**Comment by m-hope** [comment]
Can recreate this issue.  Edit any profile that has more than one attribute and delete the attribute at the top... the bottom attribute will then lose the formatting bar and the text is displayed with the html codes visible.  

Note: if you leave the editing page and then re-enter edit mode (or even just reload the edit page), the affected attribute is displayed properly, so if this is a complicated fix, probably okay to park this issue and move onto something higher priority.

**Comment by RobinaSanderson** [comment]
Tested by:

1. opened existing profile
2. selected "Title" attribute
3. entered a phrase
4. Saved attribute
5. moved to second attribute "description"
6. entered a phrase
7. saved attribute
8. Deleted title attribute

The title attribute deleted with no problems, the description attribute display did not have any problems.

Test successful.

**Comment by Rita-C** [comment]
Code reviewed.
