### ISSUE TITLE
Mobile UI - Search page

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#541]
As a mobile user of profiles
I want the search page design to be useable on mobile devices
So that I can access the functions I need

Requirements:
1. The size of the search button bar leaves almost no room for the search text.
![image](https://cloud.githubusercontent.com/assets/23368496/26382126/5d57cf62-406d-11e7-8790-e70216ec16ff.png)

**Comment by RobinaSanderson** [comment]
This issue has been added to #530 and will be resolved there.

**Comment by m-hope** [comment]
Reopening this issues as #530 didn't change the search icons on the Search page.

**Comment by m-hope** [comment]
Can confirm the magnifying glass icon only appears on the Search page if the window is narrow.
