### ISSUE TITLE
Content load

### ISSUE THREAD

**Issue by KevinThiele** [AtlasOfLivingAustralia/profile-hub#544]
This epic covers issues that directly relate to the main load of existing content from the ABRS databases into the Flora of Australia project in the eFlora platform

**Comment by RobinaSanderson** [comment]
The goal is to be able to load into Production.
Need to be able to identify the issues required before the load can be done
Will be able to load into test prior to production load if worthwhile. Would be good to see what the performance is like with a collection of 20K profiles.

**Comment by m-hope** [comment]
Also need to test the mongo db backup plan in both the dev and prod environments. ie:
 - have a collection with a few profiles
 - backup database 
 - initiate a load of more profiles... and confirm they exist
 - restore backup of database
 - test profiles have reverted to prior to import state.

**Comment by sbearcsiro** [comment]
Theoretically the search index will also need to be deleted and rebuilt after a database restore

**Comment by m-hope** [comment]
Tested the backup/restore function in both Dev and Prod... works as required.

**Comment by m-hope** [comment]
Full load of the FOA data into the production FOA collection completed.  

A dump of the Pittospraceae family in Dev needs to be exported and imported into production, but that will be a separate issue.
