### ISSUE TITLE
Filter UI - User selects list for filter

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#547]
As a profiles user (taxonomist, ecologist etc)
I want to be able to select the list used to provide a filtered view of the collection (Florula)
So that I can limit the filter to a useful set of taxa

Note: This story assumes that the ALA species list tool will include lists for each IBRA region

User Steps:
1. On the collection homepage select the filter option (this option is not required on other pages)
2. This will open the Filter page
3. The user will select the list they need from an alphabetically sorted type ahead drop down list of items - these will be from the ALA lists tool, saved as type Profile list
4. They will select an OK button or other option to apply the list to their view of the collection
5. They would then move to the search, browse or identify pages as normal.

Business Requirements:
1. The filter page includes the header and footer elements used by search, browse and other pages (the home page is slightly different)
2. At the top of the page is a heading in the same font as the search and browse pages "Filter"
3. Underneath the heading is the text:
Select filter:
4. under the text is an alphabetically sorted type ahead drop down box that displays all the lists saved as Profile lists in the ALA lists tool
5. The user can select only one of the list options provided
6. Underneath the drop down is an OK button or other option to apply the list to the user's view of the collection
7. Next to this ia a button or option to Clear the selected list
8. Underneath the OK button is the text:
This collection will be filtered by the current list (for you only). Filtering only allows profiles within the collection that have an a matched name in the list to be returned in search, browse results, and as keys; and shown as a profile page. If a filter is currently active on the current collection an indicator will be present near the filter item in the nav bar.
9. Once a list is applied as a filter an indicator will appear next to the Filter option in the navigation bar.
10. To turn off the filter, the user will need to open the Filter page and clear the selected list.

Note: I assume help content will provide further information about selecting a list and include information about creating your own list in the ALA species lists space.

Mockup 14 on https://confluence.csiro.au/display/ALAEP/User+Interface+for+Production+Release

**Comment by KevinThiele** [comment]
In answer to Robina's questions:

Does there need to be a dialogue box to say their view is now filtered?

**No, I don't think so - see below

Should there be a notification in the header to say that their view is filtered? Or is this only necessary if in later work we allow the user to save the filtered view, currently they would need to apply the filtered view in each new session.

**See the way we do this in KeyBase. There should be an indication in the Header that the view is currently being filtered, and the option to turn the filter off (that is, to restore the entire Flora). For example, a fairly prominent coloured link in the Header "Turn current filter off" or somesuch. If a filter is turned off, this link should be removed (a user would then return Home to choose another filter if they want.

**Comment by KevinThiele** [comment]
Note that because of the way this is planned (for initial release) where a single drop-down list will display the names of all lists of type "Profile", we may need to restrict this to just IBRA regions. There are already 91 IBRA regions. There are several hundred LGAs. One option would be to include them all, with a prefix "IBRA: region name" and "LGA: region name" - that way someone could start typing to find the one they need in the list, or could scroll through more easily than having LGAs and IBRAs miced by name in a single list box,

**Comment by KevinThiele** [comment]
Note that it may be better to put the elements described by Robina above (under "Business requirements") in a dialog box rather than on a separate page? There are relatively few elements.

**Comment by RobinaSanderson** [comment]
@KevinThiele Thanks for picking up the need to clear the masterlist. If you want to give the filter option on the homepage the same weight as the other options I think you'll need to option a page, I also think there are some accessibility issues associated with actions in pop up screens and dialogue boxes, however we could get around that by opening a hidden section on the page rather than a new page? this would mean more functionality changes on the home page and may take more time.
@m-hope what do you think?

**Comment by m-hope** [comment]
I think the filter button needs to bring up its own functional page... if the end goal is to have the user either select a list in a field box, or cut/paste a list into a import box then we'll need the room of a full page to do that.  This also keeps the interface functionality the same for each of the home page buttons

**Comment by KevinThiele** [comment]
Agreed

**Comment by sbearcsiro** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-172

**Comment by RobinaSanderson** [comment]
Tested in profiles-dev using the ALA Test collection.

Pretest:
1. ensure the collection includes profiles not in the filtered list to be applied
2. navigate to browse and note the number of profiles in the collection
3. be aware of a couple profiles in the collection that are not included in the list you will use
4. identify a key leading to a profile in the collection but not included in the filter list that will be applied

Test without masterlist, steps:
1. Ensure a masterlist is not applied to the collection
2. Opened collection landing page
3. Selected "Filter" button
4. Filter page opened
5. Selected the list "IBRA Arnhem Coast - Flora"
6. Selected "Submit"
7. Navigate to browse and check that profiles not in the list no longer display
8. Click in the search box with the "T" option selected and enter the name of a profile not in the filter list, click search. The profile not in the filter list should not be found.
NOTE: If you search using the "SN" (Scientific Name) option, the profile name will appear in the search autocomplete options, but selecting the option will not find the profile
9.

**Comment by RobinaSanderson** [comment]
Hi @m-hope - do you want me to create an issue for the link from the key to the profile working when the name is not in the filter list?

**Comment by m-hope** [comment]
Just removed the Testing complete tag, as I want to check out the profile access from the key issue above.

**Comment by m-hope** [comment]
Have reconfirmed that the filter option operates as above.

Also confirmed that the Identify key links will ignore the filter (ie: if a user clicks on a species in the key results that has a profile but is not in the filter, the profile still is displayed).  This is a known problem with our ability to limit the keybase keys and results.  I have included this problem in the issue covering the general keybase/masterlist interaction (#514).
