### ISSUE TITLE
Deleting an attribute is impossible in some cases

### ISSUE THREAD

**Issue by ben3000** [AtlasOfLivingAustralia/profile-hub#551]
While looking into other issues, I was able to create an attribute without any text that is apparently not able to be deleted. It appears that the attribute does not have a uuid, which explains why it can't be deleted, but I'm currently unable to reproduce this by creating another attribute.

**Comment by ben3000** [comment]
The attribute is linked to another of the same title in another collection.

**Comment by RobinaSanderson** [comment]
If you accidentally create 2 attributes with the same name and you delete one you will have this problem. There is no recovery for the collection if you do this.

**Comment by patkyn** [comment]
Cannot reproduce this issue

**Comment by m-hope** [comment]
Need to confirm if the other attribute deletion issues have either fixed this issue, or made it impossible for this situation (ie: two attributes of the same name) can't exist.

**Comment by Rita-C** [comment]
This ticket is closed because:
1. no duplicate attributes can be entered anymore, ref #585 
2. there is no duplication currently in prod:

- db.term.aggregate([     
	{"$group" : {_id:{name:"$name",vocab:"$vocab"}, count:{$sum:1}}}, 
	{ $sort : { "_id.vocab": 1, "_id.name": 1 } } 
])
