### ISSUE TITLE
PDF - Keys - Bug with how keys are displayed

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#552]
When keys that would link to a species are displayed, they appear on a numbered line as if they are part of a new key couplet. This should not happen.

Instead:
1. display the genus name and species name on the original couplet line
2. make sure the species name doesn't result in a newly numbered key
2. remove the text [link through]

Key currently displaying as: 
![image](https://user-images.githubusercontent.com/23368496/26861313-5a112d70-4b86-11e7-9e54-12d14b2c35d6.png)

Keys should display as (ignore colour of formatting as taken from keybase, this example shows how the key points to a species:
![image](https://user-images.githubusercontent.com/23368496/26861100-fe19b484-4b84-11e7-8cd5-d66d8eb8b5b2.png)

Note: If it will be difficult to show both genus name and species name, use just the species name

**Comment by RobinaSanderson** [comment]
From Kevin:
Thinking about this more: if it’s simplest to show it as it comes from KeyBase (with both names), then do that. 

If it’s simpler to show one or other name, then it’s probably better to show the species name and drop the genus.

Reason is that there are cases in keys when a lead keys out a particular species in a non-monotypic genus, and we use the same form in that case as well. The species name in this case becomes a sort of short-cut in the key. If we only show the genus name, then the shortcut doesn’t happen and a user would need to go to the genus key (even though in effect we already know what the species is).

**Comment by patkyn** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-176

**Comment by RobinaSanderson** [comment]
Checked in the collection https://profiles-dev.ala.org.au/opus/alatest using the Arabidella Genus.

Keys appear in the .pdf with the species name, the genus name is not displayed. This was an acceptable option in the comment above.

Testing for the issue is complete, it can be released/once review is complete.

![image](https://user-images.githubusercontent.com/23368496/32420618-1c895af4-c2e1-11e7-8a77-3ca033e21451.png)

**Comment by m-hope** [comment]
Using the example Cannabaceae family profile as provided in the original story, can confirm this issue (in the case that a key identifies down to a single species from the genus level) is fixed.  In this case, both the genus and the species name are displayed separated by a colon (as per the suggested solution in the original story):
![image](https://user-images.githubusercontent.com/8856025/33002160-6dba95b6-ce06-11e7-95fa-393c29505d84.png)

**Comment by m-hope** [comment]
This issues can be closed once code review is completed.
