### ISSUE TITLE
UI - Browse page - Change to text

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#553]
Change the text displayed on the browse page to:

Browse the taxonomic hierarchy using the navigation pane to the left. You can also jump to a particular taxon in the hierarchy by typing the beginning of the name into the 'Quick browse' option at the bottom of the pane.

Alternatively, you can select the 'Search' navigator at the top of this page and perform a text or name-based search.

The 'Identify' button on the homepage will help you select the appropriate profile using dichotomous keys.

**Comment by ben3000** [comment]
For smartphones, the navigation pane is not "to the left", so when the viewport is at xs or sm breakpoints, the text needs to read "above" instead.

**Comment by ben3000** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-174

**Comment by RobinaSanderson** [comment]
Text is correct in both desktop and mobile screen sizes. tested in  https://profiles-dev.ala.org.au/opus/foa/browse
