### ISSUE TITLE
pdf - positioning and size of map

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#559]
As a .pdf user of the Flora of Australia
I need to map to be of a size that I can easily read it
So that I can at a glance determine the distribution of the taxa

Requirements:
Make map bigger next to distribution attribute. Other attributes to appear below.

**Comment by RobinaSanderson** [comment]
Hi @ChrisPalmer1  - I've just discussed this with @patkyn - It will be difficult to get multiple attributes wrapping beside the map. We could more easily make the map larger, but still only have the Distribution information wrapping next to it as a compromise.

**Comment by ChrisPalmer1** [comment]
Ok, is it possible to add the map as an image to the other images? That way it would be about as big as the other images, and no need to wrap anything around it. If this is possible then it would be preferable for it to be the default first image. This would save a lot of room, especially within a many-species PDF, with no map among the text. And if it’s the default first image then the user will know where to look for it (to some extent).

If not possible, perhaps making the map larger is the only option, but may still be ok if left-aligned against the distribution text.
Cheers

**Comment by KevinThiele** [comment]
I agree with Chris re positioning as the first image.

**Comment by m-hope** [comment]
Investigation indicated that moving the distribution map into the images section meant the map was too small to clearly see the occurrence points... Enlarging the map and wrapping the Distribution attribute text around it has been implemented and works well.
