### ISSUE TITLE
semantic mark up of content - text is marked such that e.g. names used within the text can be located and updated.

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#56]
http://www.bugherd.com/projects/58735/tasks/42

**Comment by ala-bugherd** [comment]
for further discussion

**Comment by ben3000** [comment]
This needs probably to use [HTML microdata](https://en.wikipedia.org/wiki/Microdata_%28HTML%29).

**Comment by ben3000** [comment]
The Google-, Yahoo-, Bing- and Yandex-supported vocabularies currently in use are available at https://github.com/schemaorg/schemaorg.

**Comment by RobinaSanderson** [comment]
Would need a use case that shows value of a particular element to markup above a simple ctrl-F, as the effort required to markup all text that could change would be prohibitive.
