### ISSUE TITLE
pdf - order of profiles in multi-profile pdfs

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#560]
As a user of a multi profile .pdf
I want the order of profiles to reflect the hierarchy of taxa in my selection
So that related concepts occur together in the .pdf and it is clear how they ordered.

Requirements:
1. the hierarchy of taxa should be preserved, i.e.:
- all varieties and subspecies for one species within a species should be grouped and listed alphabetically (if there are any sub nodes, their hierarchy should be preserved)
- all species for one genus within that genus should be grouped (but with their related sub nodes)
- all genera for one family within that family should be grouped (but with their related sub nodes)
and so on up the tree to Kingdom.
2. taxa within a grouping should be presented alphabetically, except for where subspecies and variety are at the same level. Where this occurs they should be ordered alphabetically by epithet, e.g.:
Sandersonia robinae var. barrettii
Sandersonia robinae subsp. hopei
Sandersonia robinae subsp. palmeri
Sandersonia robinae var. whaleni

rather than by full string - i.e. not:

Sandersonia robinae subsp. hopei
Sandersonia robinae subsp. palmeri
Sandersonia robinae var. barrettii
Sandersonia robinae var. whaleni

(Depth first traversal of the taxanomic tree rather than breadth first)
see also comments on #479 for discussion of this issue

**Comment by RobinaSanderson** [comment]
Hi @m-hope - both @patkyn  and I think this should be done. Currently, the ordering groups the items at one level (i.e. all genus taxa, then all species taxa, then all subspecies etc.) rather than replicating the hierarchy. are you happy for this to proceed.

**Comment by m-hope** [comment]
Yes @RobinaSanderson & @patkyn , I think the ordering definitely needs to be hierarchical both release...

**Comment by patkyn** [comment]
As discussed, this will require some reformatting in the PDF and will require some time. 
As agreed for now, the ordering should follow the ordering under the Browse function.

**Comment by RobinaSanderson** [comment]
Check the order is the same as in the browse function - moving to test.

**Comment by m-hope** [comment]
Confirmed in ALA Full Load Test... PDF of Pandanales has all child taxa in the same order as listed in the Browse page.
