### ISSUE TITLE
UI and pdf - Family names should not be italicised

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#561]
As a user of the Flora of Australia
I want family names to appear unitalicised 
As this will follow the convention for the appearance of names and provide consistency with other sources

Requirements:
* Family names should appear without italics in both:
** the profile pages online and
** in generated pdfs.

This may be most easily done by applying this formatting to the profile and allowing the pdf to pick up formatting from the profile when the pdf is generated.

Perhaps we could have italics by default on profiles and have the editor able to turn italics on or off for individual profiles, so that the editor could decide if a particular taxa should appear with an italicsied name or not? - Not sure how this would work with stubs since these profiles are being generated automatically.

Currently, in the ALA full test load collection has family names italicised:
![image](https://user-images.githubusercontent.com/23368496/27563064-d400dc98-5b12-11e7-80fb-1883e0589810.png)

I think this formatting may be applied when the profile is matched?

See comments on #479 for discussion generating this issue.

**Comment by RobinaSanderson** [comment]
Hi @m-hope 
@temi has estimated this will take 2.5 days. I think it is worth doing given the community's emphasis on consistent formatting. Temi will start on it unless we hear from you not to.

**Comment by javier-molina** [comment]
The implementation should consist of adding a config flag per profile, the default value is to display in italics as currently all profiles do.

Presumably all the changes for profile-service are committed including tests.

The remaining work should be around profile-hub only.

Moving ticket back to TODO column

**Comment by RobinaSanderson** [comment]
In addition:
1. if the name of the taxon is updated in the national species list, this should flow through to the profile page and the formatting should reset to the default.
2. the editor can only use this function to change the formatting of the name, if they want to change the text used in the name, they will need to use the existing functionality around matching names.

@m-hope could you please check these changes?

**Comment by m-hope** [comment]
Yes, agree with Robina's changes above.
 - changing the name of a profile should reset the formatting.
 - this issue only refers to the formatting of a profile name and should not allow editors an alternative way of changing the name of a profile outside of current fuinctionality... I am envisioning either:
     - a simple remove italics check box for the profile name (as a first step for implementation), or
     - the ability to select any part of a profile name and allow the editor to set italic/non-italic for that part, but not change the text in any other way.

**Comment by m-hope** [comment]
Tested by selecting a family profile (eg: Poaceae), manually formatting the name to remove the italics, then exporting the PDF.  Confirmed the title of the PDF is not in italics.
