### ISSUE TITLE
Glossary - Error when trying to upload a glossary

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#565]
Steps to test:
* logged in as a collection administrator (not platform administrator)
* Selected "Edit Configuration"
* Selected "Glossary"
* attempted to upload .csv 
* .csv file uploaded
* selected "Save"
* got error message at top of page
* Save button still activated
* navigated to Glossary tab
* Glossary doesn't display

**Comment by m-hope** [comment]
Tested successfully with collection FOA in profiles-dev..
