### ISSUE TITLE
UI - Homepage - mouseover text for Filter is not saving

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#566]
Steps to test:
* log in as collection admin
* Edit configuration
* Select Homepage
* Enter mouseover text for Filter
* Save
* Navigate to Home page
* Mouseover Filter option
* Text is not displayed

When navigated back to configuration, the text entered in the homepage Filter mouseover field has disappeared.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-183

**Comment by m-hope** [comment]
Confirm Filter mouse over text is now saving and visible.

Issue can be closed once reviewed.
