### ISSUE TITLE
Library page - Download documents doesn't work

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#571]
Both clicking on the title of a document on the Library page or clicking on the Download action for a document attempts to download the document. The user gets a Do not have permission error.

![image](https://user-images.githubusercontent.com/23368496/27998326-5c137cc0-6550-11e7-8a6c-7b69e3b75f0c.png)

Note: this does work for documents associated with a profile.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-181

**Comment by m-hope** [comment]
Tested by opening "Flora of Australia" private collection on profiles-dev, selecting the Library tab and clicking on the download link for both PDF documents... both documents appear in Acrobat.

Also tested in "MLH Test Collection" on profiles-dev, by uploading a PDF and testing the download button... confirmed it opens the PDF in acrobat.
