### ISSUE TITLE
UI - Homepage - Hide "Updates" heading if there is no content

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#572]
As a collection Admin
I don't want the updates Heading to display if there is no content
So I don't have to generate irrelevant content to make the heading look useful.

**Comment by RobinaSanderson** [comment]
This would mean there is a column on the home page mot being used, it might be better to allow an admin to upload a picture into this space with the updates headings still not displayed?

**Comment by m-hope** [comment]
Initially just leave the Update area as white space if no content.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-182

**Comment by m-hope** [comment]
tested... works fine... Updates heading is not visible if there is no text in the updates box within the config settings.  
At the moment, the space for updates is left blank and this is acceptable.

This issue can be closed once code is reviewed.
