### ISSUE TITLE
About page content not saving in collection settings

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#576]
If a collection admin adds "About page content" information into the collection settings, it won't save (ie: the text won't be there if you re-enter the collection settings) and it does not display on the About page.

Note: the Citation text saves and displays as expected.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-184

**Comment by m-hope** [comment]
Confirm About text is now being saved...

Issue can be closed once reviewed.
