### ISSUE TITLE
Ability to turn off using a masterlist and go back to original functionality

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#582]
When investigating the Masterlist functionality, I found  that you couldn't turn off the masterlist functionality once one has been selected... 

In the current profiles-dev environment, if you select the option "-- No master list --" when a masterlist has previously been selected, the "Sync now" and "Regen stubs" buttons remain greyed out after you've saved the list change... which means that you can't remove the auto-generated stubs. I suspect there is a reason those buttons are greyed out, but we do need an ability to turn off the masterlist and go back to original functionality if required... but not sure the best way to do this??

**Comment by javier-molina** [comment]
This is a summary of what needs to be documented for the new master list functionality

- An entry in ALA Profiles Online Help needs to be created for master list for this url https://atlasoflivingaustralia.github.io/profile-hub/opusConfig.html#masterlist

- The first thing to add is an explanation of what master lists are and the three different scenarios when using a master list and matching or not existing profiles.


Refer to screenshot below for the next paragraphs.

- Clear master list button is a shortcut to unselect any current masterlist

- When a new list (or none) have been selected and then saved or a user has explicitly clicked Sync now or Regen stubs then the message 'The master list is currently being updated for this collection.' will be displayed and all controls in this section will be disabled. This will minimise the likelihood of the user (or another user in a different window) firing another update as this is a long running operation.   
- Related to the above it is very important to emphasise in the documentation that the update is a long running operation that could take several minutes. 
- Sync now and Regen stubs button where moved below Save button to emphasise that those don't depend or change the current master list selected.

- Sync now will run from scratch a comparison of local profiles against 
![screen shot 2017-10-11 at 9 35 59 am](https://user-images.githubusercontent.com/8326394/31414124-2a617630-ae68-11e7-92e0-70da4a8f7ddc.png)

**Comment by m-hope** [comment]
Thanks @javier-molina.  How soon can this code be deployed to Profiles-dev?  I think knowing when a Sync is complete and the ability to clear a masterlist, may resolve a couple of other masterlist issues, including #533, and a duplicate stub bug (which I haven't created an issue for yet as I suspect it is just a case of multiple clicks on the Sync button).

**Comment by javier-molina** [comment]
Sorry @m-hope  I just saw your message here, as discussed, the changes are now in dev.

**Comment by javier-molina** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-185

**Comment by RobinaSanderson** [comment]
Tested in https://profiles-dev.ala.org.au/opus/alatest

Tested by:
1. apply masterlist which includes and entry that will create a stub and does not include a entry for a profile that exists in the collection (i.e applying the masterlist will "hide" a profile)
2. check that the stub is created
3. check that the non-included profile is hidden
4. remove masterlist
5. check that the stub no longer is viewable
6. check that the profile is not longer "hidden"

**Comment by m-hope** [comment]
Also tested and confirmed this works.
