### ISSUE TITLE
Shouldn't be able to duplicate attributes in the Attribute Vocabulary

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#585]
In the Edit Configuration page in the Attribute Vocabulary section, you shouldn’t be able to duplicate an existing attribute name (ie: shouldn’t have two attribute vocab entries of the same name), as the system can’t deal with it (eg: treats both as the same entity… eg: duplicate an existing attribute in the vocab, then go to a profile and attempt to add a new attribute… you will only see one entry for the duplicated attribute in the drop down list,… also if you go back to editing the configuration and delete the duplicate, both will be deleted).

Note: it is okay for an individual profile to have more than one entry for a particular attribute (this allows different contributors to add data to the same section), but there shouldn't be more than one attribute of the same name displayed (except where there are inherited attributes from a supporting collection).

**Comment by m-hope** [comment]
Use this collection to test:
https://profiles-dev.ala.org.au/opus/919a4d41-ee7a-4634-ae6d-0afa3723f233

**Comment by Rita-C** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-194

**Comment by Rita-C** [comment]
Checking duplicates on Add term and edit term actions.
Also fixed issue that an empty entry is accepted while editing.

**Comment by RobinaSanderson** [comment]
Tested in profiles-dev using collection ALA Test

Testing with strict vocabulary. Steps:
1. log in as admin
2. open Configuration - Attribute vocabulary
3. select strict vocabulary
4. in the "Add" area enter an existing attribute term.

Results
1. An error message displays with the following text - The specified term already exists. Terms must be unique across the attribute vocabulary.
2. The duplicate term is not added to the vocabulary

Testing with non-strict vocabulary. Steps:
as above with non strict vocabulary selection

Results
as above

Also checked:
1. if the Add field is blank and the Add button is clicked, no attributes are added
2. if the Add field has only spaces entered and the Add button is clicked, no attributes are added

**Comment by m-hope** [comment]
Also confirmed this function works correctly.

**Comment by elywallis** [comment]
Reconfirmed testing done by Robina, now on aws-profiles. Same result.
