### ISSUE TITLE
Profiles producing errors when displayed or edited

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#592]
On both prod and dev systems, when (some?) profiles are displayed or edited, several (4-5, up to 7?) pink error bars come up as follows:

![image](https://user-images.githubusercontent.com/8856025/33410014-627c8b22-d5d2-11e7-8ef2-983520a845a9.png)

Is this something to do with the number of child taxa or at least the call/response to/from NSL?

**Comment by m-hope** [comment]
Note: the number of errors varies between profiles (eg: Passiflora mollissima gives 1 error but Acacia Victoriae gives 5).

Also renaming profiles in Draft mode can produce up to 9 errors (eg: renaming Passiflora mollissima to Passiflora tarminiana)

**Comment by Rita-C** [comment]
sample error:
Failed calling web service. class javax.net.ssl.SSLHandshakeException Received fatal alert: handshake_failure URL= https://biodiversity.org.au/nsl/services/name/apni/71773.json, method GET.

**Comment by Rita-C** [comment]
Upgraded developer's local JDK to 1.8 seems resolved this issue. @m-hope is going to test it on the new server which runs 1.8.

**Comment by RobinaSanderson** [comment]
Tested in profiles-dev ALA Test collection.

Checked the following and not getting error messages:
* stub profile
* profile with status partial, includes images

**Comment by m-hope** [comment]
Confirmed... in testing all other issues in Profiles-dev, I have not encountered the "An error occurred" message when viewing profiles.

**Comment by elywallis** [comment]
Reconfirmed. Testing in aws-profiles, I have not encountered any error message when viewing or switching to edit mode for profiles.
