### ISSUE TITLE
Glossary - edit/delete buttons visible to anyone

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#593]
As documented in #468, any user (including anonymous users) can see the edit and delete buttons when viewing the glossary.  

Note: even though the buttons are visible and will bring up a dialog box to make the changes, when the user clicks on the final "Ok" button, an error is generated if the user does not have the permission to perform the action.

To fix this, only users who have the admin role for that collection should see the glossary edit/delete buttons.  
[27/02/18] - For clarification, the "Add item" button should also only be visible to users with the admin role.

**Comment by m-hope** [comment]
Is it worth fixing #597 while working on this issue?

**Comment by Rita-C** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-192

**Comment by m-hope** [comment]
Tested in Chrome and Firefox:
- as an admin user check I can see the "Add Item" button and the edit/delete buttons in the Glossary. (also confirmed that the functionality of these buttons works).
- Logout as current user, confirming the "Add Item" button and the edit/delete buttons in the Glossary are no longer visible.
- Login as an "Editor" and confirm the "Add Item" button and the edit/delete buttons in the Glossary are still not visible.

Testing passed.
