### ISSUE TITLE
Error messages for profile page

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/profile-hub#594]
https://profiles.ala.org.au/opus/foa/profile/Chromolaena%20odorata

shows 5 error messages "An error occurred".

<img width="1179" alt="chromolaena_odorata___flora_of_australia" src="https://user-images.githubusercontent.com/532845/34546114-e8f840b8-f145-11e7-9f0c-f5f523b1fcb0.png">

Reported by user with ticket: https://support.ehelp.edu.au/helpdesk/tickets/13257

**Comment by m-hope** [comment]
duplicate of #592
