### ISSUE TITLE
Confirm editor/author roles - editor doesn't seem to be different

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#595]

**Comment by m-hope** [comment]
Confirmed from ABRS that the roles are not working correctly:
 - Author appears to be same as User
 - Editor only has Author permissions
 - Admin, User and Reviewer appear to be correct.

Need to check that Admins can add users (only in Dev Flora of Australia collection, nit in Prod or other Dev collections... is this a user limit issue?).

[Add role descriptions here to confirm what each role should be able to do]

**Comment by m-hope** [comment]
I'm moving this issue up to the top of the To Do list as the Yugul Mangi Rangers seem to have deleted their collection again.  This issue will fix the functionality that will stop this from happening in the future.

**Comment by RobinaSanderson** [comment]
Checked with Zoe today, They need to Author role to be able to:
* create a profile
* edit the content of a profile

An author should not be able to:
* Publish a profile
* Delete a profile

Eventually creation may be handled by the masterlist but until then Authos need to be able to create profiles or Zoe's team will end up with a lot of extra work.

**Comment by patkyn** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-190

**Comment by Rita-C** [comment]
Reviewed code, didn't test all the scenarios.

**Comment by RobinaSanderson** [comment]
Tested in the profiles-dev environment, collection ALA test

2 user accounts are needed for the test collection: an admin account and a another account that roles can be granted to.

Without a masterlist applied. Steps:
1. Choose a collection that is not Public. Without logging in, check to see that the collection is not visible. 
2. As an Admin to the collection, login and set a login to User. Check that the collection profiles are visible by can't be commented on, edited or deleted. Check this login can't create a new profile.
3. As an Admin to the collection, login and set a login to Reviewer. Login as a reviewer and leave a comment on a profile. login as the administrator and check the comment is saved and displays.
4. As an Admin to the collection, login and set a login to Author. Login as an Author and check the login can edit and create profiles, but not publish or delete.
5. As an Admin to the collection, login and set a login to Editor. Login as editor and check the login can publish a profile, and delete a profile.
6.

**Comment by RobinaSanderson** [comment]
Hi @m-hope - when you get a chance, can we go through the editing options with the masterlist on? My memory is that we wouldn't add or delete profiles with the masterlist engaged, but I might be wrong or your thinking might have moved on...

**Comment by m-hope** [comment]
Tested on Public collection:
 - Anonymous (not logged in) user: profiles visible/browsable/searchable, PDF exportable, filter works (only for session). Can not see comments.
 - User: (confirmed not available for Public collections)
 - Reviewer: can browse/search/view profiles; filter working and is retained between sessions; has no option to create profiles; can add/view/delete (own?) comments; can export PDF; has no option to edit profiles.
 - Author: can create a profile (all editting functions okay, but can't manually format name when the profile is first created... need to view the profile first then re-enter edit mode). Can not put profile into draft mode.  No option to publish/delete/archive profile available. No option to edit collection configuration available. Can add/view/delete (own?) comment.
 - Editor: As per Author... can put profiles into draft mode.  Can publish/delete/archive profiles. Can not edit collection configuration.

**Comment by m-hope** [comment]
@RobinaSanderson, agreed, if a masterlist is active then the add profile option in the hamburger icon should be removed, as should the delete profile options from the Edit Profile menu.  This is documented in the issue #590, which is currently in the To Do column.

Note: that while the functionality (adding/deleting profiles when a masterlist is active) is still possible, as far as I can see, it doesn't cause any problems, other than confusion and inconsistent user experience.

**Comment by elywallis** [comment]
This issue has now been replaced by #637 as the permissions requirements for Authors and Editors have been further refined.
