### ISSUE TITLE
Profiles not displaying on iPad devices

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#596]

**Comment by elywallis** [comment]
Sprint planning meeting: issue was that the species profile didn't seem to work at all on an iPad. Could be related to iOS version?

**Comment by elywallis** [comment]
Tested on iPad running version 11.2.2 and iPad running version 12.1
Tested using aws-profiles.ala.org.au
Tested Browse funtion, filters function, pull in menus, pinch to zoom on map display function, search function.
There are some minor display issues (e.g. text running under images on profiles display in landscape under Nomenclature) but the platform definitely works on the iOS platform now.
