### ISSUE TITLE
Open Glossary on separate page.

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#597]
Currently, when you click on a Glossary link the glossary opens in the current page... as the user will always want to return to the original page it would be better to open it in a separate window or popup.

**Comment by Rita-C** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-191

**Comment by m-hope** [comment]
Tested on Chrome and Firefox, by:
- selecting the Glossary menu item at the Home page and confirming that a new window is created to open the glossary
- browsing to an example profile, then selecting the Glossary menu item confirming a new window is created.
- initiating an Identification using the Identify page, then selecting the Glossary menu, confirming a new window is created.

It is noted that while a new window is created, this window/tab in both browsers is 'remembered' and all future requests to display the Glossary will use this window (even if the user has used the Glossary window for another task), replacing whatever page was displayed.  I think this behaviour is acceptable for the time being.

Test passed.
