### ISSUE TITLE
Exporting PDF always generates an error

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#601]
Any request to generate a PDF causes a "An unexpected error has occurred while processing your request." error, regardless of whether images are in the profile or not (see issue #589).

**Comment by Rita-C** [comment]
On my local, navigated to a profile, selected "Export as PDF" from Options menu, PDF version was generated without error.
This issue may have been fixed by other changes.

**Comment by RobinaSanderson** [comment]
Tested with the profile:https://profiles-dev.ala.org.au/opus/alatest/profile/Adenia%20heterophylla

No errors found. Profile has map, images and lower level taxa. 

Tested with profile: https://profiles-dev.ala.org.au/opus/alatest/profile/Abrotanella
The .pdf included the keys for the genus.

**Comment by m-hope** [comment]
Confirmed.  Generating a PDFs while testing other issues, has not generated any errors or unexpected behaviour.

**Comment by elywallis** [comment]
Retested with the profile: https://aws-profiles.ala.org.au/opus/foa/profile/Acacia%20acuaria 
No errors found. Profile successfully produced with map, images. 

Retested with the profile: https://aws-profiles.ala.org.au/opus/foa/profile/Abrotanella 
The pdf included keys.
