### ISSUE TITLE
Map query filtering is not saving between sessions

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#603]
Need to get examples (seems to sometimes work and not others)... get examples from ABRS.

https://profiles.ala.org.au/opus/foa/profile/Acacia%20ashbyae seemed to work (removed ACT and Carnarvon points)... 

Sometimes map config would only last for a week???

**Comment by sbearcsiro** [comment]
Unable to reproduce.
