### ISSUE TITLE
Profile name formatting - not handling "Hook. F" properly

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#605]
Profiles where the author is "Hook.f." (which is the son of "Hook."), the Hook part gets italisied which is incorrect.

**Comment by m-hope** [comment]
Examples:
https://profiles-dev.ala.org.au/opus/mlh/profile/Helichrysum%20depressum

https://profiles-dev.ala.org.au/opus/mlh/profile/Agrostis%20subulata

**Comment by RobinaSanderson** [comment]
From Zoe Knapp:
For the most part we use the general formatting you’ve noted below: plain text, italics and capitals as well as some punctuation (full stops, brackets). In addition, it would be good to have the following formatting options for names, which would allow for proper formatting of phrase names and hybrids (Phillip has provided some example names):

•	hybrid symbol, as is provided in the profile attributes (the x symbol), i.e. Salix ×fragilis L.
•	, (commas)
•	& (e.g. where there are more than two authors)
•	Numbers e.g. as in Acacia sp. Airlie Island (V.Long VL 163)
•	+ e.g. as in Acacia sp. Charters Towers (E.J.Thompson+ 347)
•	Single quotations e.g. as in Acacia sp. 'Beeron'
•	Hyphens for hyphenated plant names and authors e.g. as in Acacia sp. Gimbat (J.Russell-Smith 5223)
•	En dash if used in phrase names

Some of the options listed above may be available already, e.g. commas. We haven’t seen names with underlining, bold, superscript or subscript.

**Comment by patkyn** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-199

**Comment by m-hope** [comment]
While testing this feature, I managed to kill the Mongo database service, removing access to all collections on the server... Until this is investigated do not try to manually configure the name of a profile on Profiles-dev.

The actions that led to this issue are as follows:
 - open a profile and go into 'Edit' mode.
 - select the 'Manual' formatting option, and in the formatting box italisize a section of the title.
 - click on 'Update Manual Formatting' (note this does not change the formatting as expected).
 - while the manual formatting window is open, make a change to another attribute and then click the (now active) 'Save' button.
 - at this point the browser will be redirected to the 'Collections' page, but no collections will be shown... a number (two?) of error bars will also be displayed.

**Comment by patkyn** [comment]
There were some Mongodb timing out issues in profile-service logs. The mongod service was not started with the correct dbpath. When I started the mongod service with the correct dbpath, the feature was retested without any issues to the mongodb. 
However, I found out that the feature was deployed in profile-hub whereelse, the profile-service which does the saving was not deployed with the changes.

**Comment by m-hope** [comment]
This issue is now fixed.  Testing confirmed that profile names could be manually formatted correctly with and without a MasterList.  Note, stub profile names can be manually formatted and the changes will be retained until either a new MasterList is assigned or the current MasterList is re-synced (this is acceptable).
