### ISSUE TITLE
Retest attribute deletion/transfer capabilily

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#607]
Currently FoA in production there are a lot of attributes that are the same thing with slight variations in name.

We need to make sure that the new attribution deletion functionality is rock solid to allow ABRS to:
 - delete unwanted attributes safely
 - merge data in two (or more) similar attributes into a single attribute (and delete the unused one)
 - ensure that data is not overwritten if there is data in both similar attributes in the same profile.

**Comment by RobinaSanderson** [comment]
Do you want me to see if I can bust a collection again? :-)

**Comment by m-hope** [comment]
I think we need to have a standard way to create a 'full' collection quickly (ie: with a standard set of data to import) then you can bust away :-).

**Comment by Rita-C** [comment]
To check if there is any duplicated attributes, run the following script against MongoDB:
db.term.aggregate([     
	{"$group" : {_id:{name:"$name",vocab:"$vocab"}, count:{$sum:1}}}, 
	{ $sort : { "_id.vocab": 1, "_id.name": 1 } } 
])

related issue #551

**Comment by m-hope** [comment]
As a finial test whether duplicate attribute issues have been fixed, I have used the aws-profiles server as follows:
- with an old version of the profile-hub, created a number of duplicate attributes in two collections:
    - ALA Design Test:
        - Added duplicate attributes: Description, Habitat, Type, Common (with and without spaces at end)
        - Added some data to Description attribute in the Acacia profile (already has some Desc. data)
        - Added data to Type attribute in (new) Acacia victoriae profile
    - ALA Test Collection:
        - Added duplicate attributes: Description, Habitat, Type, Common (with and without spaces at end)
        - Added data to Description and Habitat attributes (no existing data)
        - Added data to Type and Description attributes (existing data for Desc)
- updated code to latest dev version to incorporate changes
     - Test ability to delete attributes as follows:

**Comment by m-hope** [comment]
Closing this issue as testing is complete... issue #652 documents the only bug found.
