### ISSUE TITLE
Migrate profiles.ala.org.au to AWS infrastructure

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#610]

**Comment by Rita-C** [comment]
@m-hope , l'll re-run scripts in #640 once the migration is complete.

**Comment by m-hope** [comment]
Thanks @Rita-C, the database on AWS should be ready for your #640 scripts now.

**Comment by Rita-C** [comment]
#640 scripts has been re-run.

**Comment by m-hope** [comment]
Thanks Rita.

**Comment by m-hope** [comment]
Profiles prod has been running successfully on AWS infrastructure for 12 months now. Closing this issue.
