### ISSUE TITLE
Map filter bug if exclude is used?

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#616]
There is an problem with the 'Edit Map Configuration' feature  when editing a profile.  It seems to occur when facets are excluded using the 'Choose More' option.

This issue can be recreated by:
-	Selecting the Acacia buxifolia profile in the MLH test collection on profiles-dev,
-	Limiting the taxonomy to only the Acacia buxifolia species.
-	Excluding all records with country = unknown (Note: this displays two lines under the Selected filters which is an error).
-	Trying to include only “Goobang” option for Capad 2014 terrestrial facet...

At which point all the points disappear and the Selected filters haven’t updated...  I also can’t select additional options... the only option that seems to work is to clear the filters and start again... interestingly, after a short while we get a couple of error messages which may be related.

**Comment by Rita-C** [comment]
upsource TBA

**Comment by m-hope** [comment]
Am not able to test this as it appears that when you use the "choose more" pop-up and select the "exclude" option, the grey background behind the popup doesn't disappear and you can't get back to edit the map further (including saving the excluded facet).

**Comment by Rita-C** [comment]
https://upsource.ala.org.au/ala-map-plugin/review/AMP-CR-20

**Comment by m-hope** [comment]
I've tried the original test case above, plus two other profiles and various combinations of included and excluded facets (up to about six at a time) and facets are able to be deleted individually and cleared altogether without issues.

Note: there are some peculiarities in the display of the facets (ie: sometimes the facet options don't reappear when a selection is made), but this is fixed by saving the current filtering and reloading the page.
