### ISSUE TITLE
Flora of Australia Dev collection - can't add more users

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#617]
Steps to recreate:
1. As an Admin in the Flora of Australia dev environment, select Edit configuration
2. Add a user by entering the email of a person with an ALA login and selecting the person
3. Assign the role of Viewer
4. click Save
An error message appears

If you follow the same steps in another collection in dev (I used ALA test 2), the user will save with the selected role.

Not sure if the FoA dev site just has too many dev users identified, or if roles and permissions have got corrupted at some point for this collection only. This will need to be investigated.

**Comment by m-hope** [comment]
Issue is to do with the fact that the collection is public and the user being added was already registered as a user (these users are hidden on public collections).  The workaround is to check the Private collection box (which will display all users), alter the 'new' user's role, then uncheck the Private collection box.
