### ISSUE TITLE
Need to insert the _blank HTML code for all URLs in old attributes from prod.

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#640]
Zoe [8/10/18]: Web links that were created to open at new window do not; they open in the same page (though glossary now opens in a new window).
 - This was a bug in the old production, but is now fixed (the _blank html code wasn’t being added to the URL string in the attribute when the URL is added)... all the links in the old production data will need to have the _blank parameter added... the only way to do this is manually.  I’m not even sure there is an easy way to find attributes with a URL...

**Comment by m-hope** [comment]
Based on the discussion at the sprint planning session.  This issue can only be solved by editing the database directly (which I'm not sure we want to do).  I would suggest that the most we do for this job would be to do a search the attribute database and create a list of all profiles that have attributes containing a URL to give to ABRS to go in and manually fix the URLs.

This may be something I can do.

**Comment by Rita-C** [comment]
Checked in scripts to update database values, reviewed by @m-hope , executed on aws on 13/12/2018.
