### ISSUE TITLE
Move the "Delete Collection" button

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#647]
Currently the "Delete Collection" button is located in such a position that it is beneath the Close (X) button on any warning/error message.  
Given that the warning/error message window can auto-close, it is possible for a collection admin to be in the act of closing the message window when it auto-closes and the click is then registered on the Delete Collection button.  If the Collection Admin is aware of what is going on, the delete can be cancelled via the confirmation, but new admins may not pick this up.

**Comment by temi** [comment]
Move delete button to bottom of page.
