### ISSUE TITLE
Map filters - Ability to apply default filters across collection

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#651]
As a collection administrator
I want to set filters to apply across all maps on profiles in the collection
So that I don't have to set these filters each time.

Background:
ABRS apply the following filters to all profiles:
- exclude "Establishment means - Cultivated"
- include "Country = Australia"

it would be good if they could be applied at collection rather than individually on each profile.

Requirements:
1. Must be Admin to set the filters to apply by default
2. on the collection configuration page, add a section which lists all available filters
3. Allow the administrator to select the filters that will apply by default (could be checkboxes or some other way to select)
4. allow the administrator to save the setting
5. on clicking the save option, apply those filters to all occurrence maps on profiles in the collection.

**Comment by m-hope** [comment]
#650
