### ISSUE TITLE
Need to move Profiles DOI (snapshots) to ALA DOI service.

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#659]
As the DOI capability in Profiles (centred on the creation of snapshot versions of profiles) was built prior to ALA having a central DOI service, Profiles is coded to obtain DOIs directly from ANDS using the config settings in /data/profile-service/config/profile-service-config.properties.

We need to reconfigure Profiles to use the ALA DOI service instead of going directly to ANDS. And, user DataCite to generate DOIs since ANDS infrastructure will not be supported after 31st December, 2020

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-2
