### ISSUE TITLE
AWS environment - Error when down loading pdf from Documents tab on a profile

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#668]
Preconditions:
1. Need to have a profile with a pdf document attached. These can be see on the "Literature and Links" tab. e.g. https://aws-profiles.ala.org.au/opus/alatest/profile/Lomandra%20glauca
Note: if you need to add a pdf to a profile: 
* have a pdf you can browse to
* open profile
* select edit
* click on Documents tab
* add document
* Save

Steps to replicate:
1. Open a profile with a pdf attached
2. click on Literature and Links
3. Click on title of document

Actual result:
New page opens and error displays

Expected result:
New page opens and document displays

**Comment by RobinaSanderson** [comment]
Hi @m-hope - I can confirm this is an issue using Chrome.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-213
