### ISSUE TITLE
Placeholder - PDF map ignoring option to not include map

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#676]
When a user selects the option to export/create a PDF, the resulting dialog box allows the user to deselect the Map (ie: not include the Map in the PDF).  This option is currently ignored and the resulting PDF will contain the map regardless of whether the check box is selected or not.

**Comment by Rita-C** [comment]
@sbearcsiro, could you please review the change?

**Comment by sbearcsiro** [comment]
LGTM
