### ISSUE TITLE
Need to upgrade Profiles to Grails 3

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#699]
The current implementation of grails on Profiles breaks the ALA build mechnaism (Travis), so all deployments of new code new to be done manually... apart from being inefficient, this workaround may not be available in the future.  
It should be noted that there was a major exercise within ALA to update most products to Grails 3.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-5
