### ISSUE TITLE
Enhanced searching

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#70]
* Install and configure Elastic Search
* Create 2 indexes: 1 for names, and one for free text
  * Names index to include the guid, profile name, matched name, NSL name, and any attributes with "name" in the title
  * Free text search to include the above + all attributes

Create a search tab for the Collection with two options: name and text search.
Name search:

* Search the BIE to get all synonyms etc and the guid
* Pass all those fields to the ES search using the name index

Text search:

* Search the free text index

**Comment by m-r-c** [comment]
Initial implementation (integration with elastic search + basic free text search) is done.

Name related searching will come later.
