### ISSUE TITLE
Search function not working on private collections

### ISSUE THREAD

**Issue by RobinaSanderson** [AtlasOfLivingAustralia/profile-hub#710]
Steps to recreate:
1. log into collection as ALA admin
2. open a collection where the user access is set to Private and the login has not separately been added to the user access list
3. identify a profile within the collection
4. search for the profile by scientific name, common name or term

Expected result:
- results matching the search will display

Actual result:
- no results are displayed 
- there is no error message displayed

Notes: 
- this less serious than originally thought as it only affects ALA Admin and the work around is to add the login to the user access list
- searching doesn't work on the search page or using the search box in the nav bar
- searching doesn't work on any of the search options - scientific name, common name, term, hide empty profiles, match all terms

**Comment by RobinaSanderson** [comment]
Testing this today and adding a user login allows them to find the profile in a search but they don't have the permission to open the profile.

This is an issue for Nat and Bernadette in that they can't demonstrate the search properly.

**Comment by temi** [comment]
This appears to be fixed.
