### ISSUE TITLE
minor bug - setting short name stops other config changes being saved

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#719]
Just a minor bug... as a collection admin if the "short name" field is set (or changed) and then saved, all future saves in that configuration editting session will not work as an error is returned saying the shortname is already in use.  The workaround is to return to public view and re-enter the config editor.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-6
