### ISSUE TITLE
glossary link to pictures and other terms

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#72]
http://www.bugherd.com/projects/58735/tasks/58

**Comment by ala-bugherd** [comment]
search function for glossary would be useful to avoid having to scroll

**Comment by ala-bugherd** [comment]
﻿Please note that I am travelling and in a workshop all day Fri 12 Jun 2015 and will have limited access to emails.

Regards,
Peter D.
Mobile: 0423 040043

**Comment by ala-bugherd** [comment]
Thanks for your message. I am out of the office with limited email access until Tuesday 23rd June. If the matter is urgent, please contact peter.doherty@csiro.au

**Comment by RobinaSanderson** [comment]
Closed for now, create new story if raised again.
