### ISSUE TITLE
Setting master list on profiles-dev doesn't create stubs

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#721]
Setting a collection wide MasterList in the Edit Configuration page should do two things: (a) pre-filter out any existing profile for a taxa that is not in the list for all functions, and (b) create a "stub" (ie: empty) profile for any taxa in the list that doesn't have an existing profile.

Currently on Dev, the MasterList setting only does the pre-filtering and doesn't create the stubs.

EG: using https://profiles-dev.ala.org.au/opus/alatest with normally has 19 entries under Genus in the Browse function.  When the MasterList of "IBRA Arnham Coast - Flora" is applied only 2 genera are listed.  When this list is applied to the production version of the collection (https://profiles.ala.org.au/opus/alatest), 686 genera are listed (most of which are stubs).

Note: the MangroveWatch collection currently uses the MasterList function on Prod.

**Comment by temi** [comment]
@m-hope I am not able to explain why the above issue occurred. It is possible the sync took time. Tried the same master list settings on profiles-dev and profiles prod, the number of genera (686) matches.

**Comment by m-hope** [comment]
Apologies, I thought I had waited long enough (and the masterlist option in the edit config page had indicated it was complete), but I can confirm after 10+ minutes or so, the stubs do appear.  This issue can be closed.
