### ISSUE TITLE
Search not finding profile with changed name

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/profile-hub#725]
Search doesn’t find new profiles or profiles that have had name changes (eg:  https://profiles-dev.ala.org.au/opus/alatest/profile/Some%20tree, which was Acacia hystrix).  Search will only bring up this profile as a result if you search on Acacia hystrix, but the link is broken as the link contains the old name (https://profiles-dev.ala.org.au/opus/alatest/profile/Acacia%20hystrix).  Searching for “Some tree” doesn’t bring back a result even though there is a autopick value for it.

**Comment by temi** [comment]
This is an exisiting bug.

**Comment by schoicsiro** [comment]
It seems to be fixed
