### ISSUE TITLE
Profile title font and point size needs to be retained when manual formatting of name is applied.

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#729]
When a profile name/title is manually formatted, the new profile name is in a font much smaller than the auto-formatted text, but there are no options to manually set the font size (which is correct... users shouldn't be allowed to change the font or font size as this should be set by the system).

Eg: https://profiles-dev.ala.org.au/opus/michael/profile/Fabaceae.

Note: as all family level profiles need to be manually formatted to remove the incorrectly applied auto-italics, this is a significant bug.
Note 2: it appears that profiles that have pre-exsiting manually formatted names display correctly (eg: https://profiles-dev.ala.org.au/opus/foa/profile/Fabaceae), suggesting in the past the font/size has been set by the system and this format info has been retained.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-6
