### ISSUE TITLE
Deleting attribute or acknowledgement term throws error

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/profile-hub#733]
Deleting an attribute from collection configuration should prompt user to replace it with another attribute. Similarly for acknowledgement term. However, this throws an error.

**Comment by m-hope** [comment]
Tested changing an attribute and acknowledgement as both ALA Admin and "normal" admin, and now functions as expected and without errors.  A dialog asking for the replacement term is displayed and when selected the relevant data then appears under the new term.

**Comment by temi** [comment]
https://upsource.ala.org.au/profiles/review/PRFLS-CR-9
