### ISSUE TITLE
"My Profile" menu item displays error (page not found)

### ISSUE THREAD

**Issue by m-hope** [AtlasOfLivingAustralia/profile-hub#735]
If a user selects the "My Profile" option on the hamburger menu, it produces an error.  On the current production system the error message indicates that the page doesn't exist and on the dev system, a "Access to profiles-dev.ala.org.au was denied" message is displayed.

This occurred for both ALA Admin and "normal" user accounts.

**Comment by temi** [comment]
should point to https://AUTH-SERVER/userdetails/myprofile
where AUTH-SERVER is the auth server the system is connected to.
