### ISSUE TITLE
Renaming/deleting a profile not updating search results

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/profile-hub#743]
There is a bug with elasticsearch indexing which prevents updates or deletes from triggering a search index update.

**Comment by m-hope** [comment]
Confirm this is fixed. Tested the following on both profiles and profiles-dev versions of the SE Arnham Plants and Animals collection (https://profiles.ala.org.au/opus/896e4aa1-72a7-46d9-beb3-7c30f5f96016 and https://profiles-dev.ala.org.au/opus/896e4aa1-72a7-46d9-beb3-7c30f5f96016):
 - creating a new profile
 - renaming a profile
 - deleting a profile

In all cases, the production collection did not reflect the changes in the search function, while the changes correctly changed on the dev version.
