### ISSUE TITLE
Migrate Analytics to Fathom from GA

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/profile-hub#773]
https://usefathom.com/docs/script/script-advanced
https://usefathom.com/api#aggregation
Following reports are used by Profiles
1. Most Viewed Profile of a collection
2. Total Visitor Count of a collection
3. Total Download Count of a collection
4. Monthly Visitor Count of a collection
5. Monthly Download Count of a collection

Server side page view used by
1. /opus/$opusId/profile/$profileId/pdf
2. /opus/$opusId/profile/$profileId/publication/$publicationId/file

Linked to https://github.com/AtlasOfLivingAustralia/commonui-bs3-2019/issues/11

**Comment by temi** [comment]
How to test

- [ ]  Check pages are sending page view pings to Fathom analytics . Can be checked on browser's network tab.
- [ ] Downloading publications sends a page view request to Fathom - https://profiles-dev.ala.org.au/publication/ecdca35a-fb85-4152-a065-11dd28acd058
- [ ] Generating pdf also sends a page view request to Fathom - https://profiles-dev.ala.org.au/opus/foa/profile/Arenaria
- [ ] About page lists analytics of a collection - https://profiles-dev.ala.org.au/opus/foa/about

**Comment by pbrenton** [comment]
tested successfully
