### ISSUE TITLE
Remove PDF export feature

### ISSUE THREAD

**Issue by temi** [AtlasOfLivingAustralia/profile-hub#781]
Places to remove it are -

- [x] Profile view page - see image 1
- [x] Profile edit - Versions - Remove "created snapshot version" - See image 2
- [x] Remove ExportController
- [x] Remove ExportService
- [x] Remove action ProfileController.savePublication
- [ ] Remove reference in URL mapping
- [x] Remove jasper soft files

### Image 1
![Image 1](https://github.com/AtlasOfLivingAustralia/profile-hub/assets/1152259/819ab4e7-8cb2-4f0c-b6a2-0fdc728d1674)
### Image 2
<img width="1054" alt="image" src="https://github.com/AtlasOfLivingAustralia/profile-hub/assets/1152259/e436dcb4-b655-42d3-8813-2846a5432304">
Versions

**Comment by temi** [comment]
@schoicsiro I could not find existing publications on profile edit page. can you send me an example on profile-dev?

**Comment by schoicsiro** [comment]
Hi guy,

Can you please try this “https://profiles-dev.ala.org.au/opus/foa/profile/Abrus%20precatorius/update”?

Regards,

Steven

From: temi ***@***.***>
Date: Tuesday, 14 November 2023 at 10:58 pm
To: AtlasOfLivingAustralia/profile-hub ***@***.***>
Cc: Choi, Steven (NCMI, Black Mountain) ***@***.***>, Mention ***@***.***>
Subject: Re: [AtlasOfLivingAustralia/profile-hub] Remove PDF export feature (Issue #781)

@schoicsiro<https://github.com/schoicsiro> I could not find existing publications on profile edit page. can you send me an example on profile-dev?

**Comment by temi** [comment]
@schoicsiro the example you provided does not have any published snapshot.

**Comment by temi** [comment]
@schoicsiro i have tested this on dev server and most of it is correct. One issue I found was versions not being displayed on profile edit page. See image below for an example from production system. This ticket require all the publications to be listed except for create button on edit mode. 

The example profile is https://profiles-dev.ala.org.au/opus/alatest/profile/Cynoglossum%20creticum/update.
See production profile - https://profiles-dev.ala.org.au/opus/alatest/profile/Cynoglossum%20creticum/update.

![image](https://github.com/AtlasOfLivingAustralia/profile-hub/assets/1152259/5beb1b68-2c2c-44f2-8ad0-af10b74d4dae)
