### ISSUE TITLE
Add field for citation (e.g. Bloggs 2001) of source material for an Attribute, for use where this material is copied from somewhere other than 'an approved collection". e.g. a book.
Change words "Originally copied from:" to "Source:"

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#80]
http://www.bugherd.com/projects/58735/tasks/66

**Comment by ala-bugherd** [comment]
Comment from Kevin Thiele: This would work except that being a freetext box it would be tedious to have to paste in the same string for each attribute. If a picklist (listing the current entries in the page’s bibliography) was easy to implement, would this be better? It could be less tedious, would create more internal consistency, and would effectively force a user to add source references into the bibliography. On the other hand it would be less flexible (e.g. if multiple third-party sources are pasted to one attribute) unless the picklist were multi-choice.

**Comment by ala-bugherd** [comment]
suggest that enhancements to improve link between citation bibliography etc be a later phase consideration

**Comment by m-r-c** [comment]
This has been implemented
