### ISSUE TITLE
For authorship and attribution, PDFs should contain: Flora logo and banner, collection name, taxon name, author of profile, version number, date, and (probably) author organisation, copyright/citation statement.

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#82]
http://www.bugherd.com/projects/58735/tasks/68

**Comment by m-r-c** [comment]
This has been implemented

**Comment by ala-bugherd** [comment]
this is included in our intentions for phase 1, but is a lower priority in comparison to having the fundamentals working.

**Comment by ala-bugherd** [comment]
oops, last comment posted against wrong task, please ignore.

**Comment by ala-bugherd** [comment]
will be addressed under #84
