### ISSUE TITLE
search using synonyms is considered important.
Possibly also search using common name or other elements (e.g. indigenous name)

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#93]
http://www.bugherd.com/projects/58735/tasks/79

**Comment by ala-bugherd** [comment]
also search using excluded and doubtful names

**Comment by rp-ala** [comment]
also navigate/browse using index of indigenous language name/common name.

**Comment by m-r-c** [comment]
See #254 - this could potentially be covered by the 'broad name' search idea

**Comment by m-r-c** [comment]
This has been covered by the various search related issues: e.g. #70, #254, #354
