### ISSUE TITLE
should names update automatically in eFloras?

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#94]
http://www.bugherd.com/projects/58735/tasks/80

**Comment by AaronWilton** [comment]
Is this question about "pure" name changes or does it include taxonomic change too?

If it is the latter then I think this may not be a straight yes/no answer.  There may be some changes to "names" that may be able to rolled through automatically (e.g., spelling or other orthographic corrections; addition of synonyms in some cases), however where there is taxonomic change this will probably need to be vetted as this may have impact on elements of the descriptive content, profiles may need to be added/withdrawn etc.  

However that in itself (vetting and delay in doing so) has the potential (if not controlled) to create problems if the taxonomy in a profile collection is "out-of-step" with the NSL view of the world  - what synonymy will be displayed on the profile?  and for searching?  (e.g., you could have a profile for a taxon in a collection that is listed as a synonym under another taxon within the same collection based on NSL taxonomy?).

If these have not already be considered/controlled, then this topic probably needs some good discussion and analysis to consider implications...

**Comment by ala-bugherd** [comment]
nomenclature group feedback is that names should not update automatically in eFlora

**Comment by ala-bugherd** [comment]
Thanks for your message. I am out of the office with limited email access until Tuesday 23rd June. If the matter is urgent, please contact peter.doherty@csiro.au
