### ISSUE TITLE
Refine format of PDF output. Consider preface sheet that goes with PDF collection.

### ISSUE THREAD

**Issue by ala-bugherd** [AtlasOfLivingAustralia/profile-hub#98]
http://www.bugherd.com/projects/58735/tasks/84

**Comment by ala-bugherd** [comment]
For authorship and attribution, PDFs should contain: Flora logo and banner, collection name, taxon name, author of profile, version number, date, and (probably) author organisation, copyright/citation statement.

**Comment by m-r-c** [comment]
This has been done.
